### ISSUE TITLE
[Feature] 订阅管理界面订阅项支持右键菜单

### ISSUE THREAD

**Issue by Jonnyan404** [pompurin404/mihomo-party#100]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

现在必须左键点击三个点,才能触发相应菜单选项.

期望可以支持鼠标右键操作,谢谢!

**Comment by ghost** [comment]
没啥必要
