### ISSUE TITLE
[Feature] 建议日志页面加入清空全部日志记录按钮

### ISSUE THREAD

**Issue by ChaoJieGo** [pompurin404/mihomo-party#101]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [x] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

    <BasePage
      title="实时日志"
      header={
        <Button
          size="sm"
          color="primary"
          onPress={() => {
            setLogs([]);
          }}
        >
          清空
        </Button>
      }
    >

**Comment by pompurin404** [comment]
没必要
