### ISSUE TITLE
[Bug] 系统代理开关失效

### ISSUE THREAD

**Issue by zwl55555** [pompurin404/mihomo-party#104]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

v1.0.9

### 发生问题 mihomo-party 版本

mihomo-party-windows-1.0.9-x64-setup.exe

### 描述

![bug](https://github.com/user-attachments/assets/9caf5eda-efcc-44d7-b032-e86438cf3fb0)
这个开关点击失效 无法显示打开状态 的vpn却已经是链接状态

### 重现方式

打开 开关状态不会更改

**Comment by xishang0128** [comment]
录制视频,单凭一张图看不出什么,并且无法复现

**Comment by zwl55555** [comment]
> ### Verify steps
> * [x]  我已在标题简短的描述了我所遇到的问题
> * [x]  我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
> * [x]  我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
> * [x]  这是GUI程序的问题,而不是内核程序的问题
> * [x]  我已经使用最新的测试版本测试过，问题依旧存在
> 
> ### 操作系统
> Windows
> 
> ### 系统版本
> v1.0.9
> 
> ### 发生问题 mihomo-party 版本
> mihomo-party-windows-1.0.9-x64-setup.exe
> 
> ### 描述
> ![bug](https://private-user-images.githubusercontent.com/97514275/362265330-9caf5eda-efcc-44d7-b032-e86438cf3fb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTU3ODAsIm5iZiI6MTcyNDg5NTQ4MCwicGF0aCI6Ii85NzUxNDI3NS8zNjIyNjUzMzAtOWNhZjVlZGEtZWZjYy00NGQ3LWIwMzItZTg2NDM4Y2YzZmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAxMzgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZjUyOTRhNDlhNTgxNDFhNmU1YjI1YTM1Y2QwMDk5YTk3NzhhOWJkMWM3ZDczODkwODRjNDFiNzBmMzA4YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CuNPdmJnxn78pN_XCm5APxrZ3F8o_63wx4vx6NpgHFQ) 这个开关点击失效 无法显示打开状态 的vpn却已经是链接状态
> 
> ### 重现方式
> 打开 开关状态不会更改


https://github.com/user-attachments/assets/2b82116a-e21a-4b30-bd1f-b44b9ecb6a64

**Comment by zwl55555** [comment]
可以看到鼠标点击了开关 但是状态并没有改变

**Comment by ghost** [comment]
点击系统代理页面的保存看看有无报错

**Comment by zwl55555** [comment]
之前是有的  现在修复了 貌似没有报错了

**Comment by ghost** [comment]
之前的报错内容是什么，方便的话安装旧版反馈一下报错内容
