### ISSUE TITLE
[Feature] 更新节点能否加入使用代理更新，有些节点只能使用代理进行更新

### ISSUE THREAD

**Issue by fresh-men** [pompurin404/mihomo-party#105]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

![image](https://github.com/user-attachments/assets/5b9edcb5-3a1d-4b04-8b26-90c3758d7089)
在更新全部代理附近加入一个使用代理更新

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/eca966e8-8fa5-4b7c-b623-d84a6cfbb2d7)
