### ISSUE TITLE
[Feature] 隐藏超时节点

### ISSUE THREAD

**Issue by it-glen** [pompurin404/mihomo-party#107]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

希望能够隐藏超时节点，测试延迟后隐藏timeout节点，Metacubexd面板有隐藏不可用节点的功能，不知道能不能借鉴一下

**Comment by JoeyLearnsToCode** [comment]
需要这个功能😭
