### ISSUE TITLE
[Bug] 内容显示重叠

### ISSUE THREAD

**Issue by DUDUACM** [pompurin404/mihomo-party#108]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

windows11

### 发生问题 mihomo-party 版本

v1.1.1

### 描述

![123](https://github.com/user-attachments/assets/0b94c850-87b8-4bdd-b324-a431cdb910a1)

### 重现方式

滚动即可重现
![123](https://github.com/user-attachments/assets/c7aa6d6d-c7fa-40f4-8f2d-27a46be8c27b)

**Comment by ghost** [comment]
是分组的粘性布局，不是bug

![recording](https://github.com/user-attachments/assets/fb9ecd90-1f7d-41eb-ad8b-52e99edbfcae)
