### ISSUE TITLE
[Bug] 每次启动程序要访问钥匙串中的mihomo-party safe storage

### ISSUE THREAD

**Issue by aLIEz-xue** [pompurin404/mihomo-party#110]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

14.6.1 (23G93)

### 发生问题 mihomo-party 版本

1.1.2

### 描述

这个访问是做什么的呢，能不能禁止掉，已经设置始终允许了但是还是弹出
![image](https://github.com/user-attachments/assets/72b36c57-85f8-4498-b881-f9a919cf9e52)
![image](https://github.com/user-attachments/assets/d0018cd5-6bc6-41ab-928a-4b833a041c6a)
![image](https://github.com/user-attachments/assets/8882444f-004b-4464-98db-160891c26c3a)

### 重现方式

每次启动软件就有

**Comment by ghost** [comment]
是不是还有其他什么系统设置，我这边无法复现

**Comment by Changwei1996** [comment]
我的mac是 14.6.1，也遇到过这个问题，也不清楚为什么会出现。
唯一确定的是，这个问题并不是每次都出现，近期几个版本更新后，都没有复现该问题。

**Comment by aLIEz-xue** [comment]
> 是不是还有其他什么系统设置，我这边无法复现

使用AppCleaner删除软件，然后进钥匙串删除mihomo-party safe storage，重新安装，目前正常了，不知道后面还会不会出现，因为虚拟网卡开启后还不支持修改系统DNS，目前没有把mihomo-party当主力使用。可能之前做了什么操作记不得了。
