### ISSUE TITLE
[Feature] 请求连接里面加上每个请求的上传下载速度

### ISSUE THREAD

**Issue by m174460635** [pompurin404/mihomo-party#111]
### Verify steps

- [ ] 我已在标题简短的描述了我所需的功能
- [ ] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [ ] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

<img width="1280" alt="微信图片_20240831025721" src="https://github.com/user-attachments/assets/d20cdf51-e819-46c1-8377-de4237e25b9b">
请求在连接里面加上不同目标的上传下载速度。

**Comment by xishang0128** [comment]
https://github.com/pompurin404/mihomo-party/issues/89
