### ISSUE TITLE
[Bug] m1  打开软件电脑机身发烫严重

### ISSUE THREAD

**Issue by kafeixiang** [pompurin404/mihomo-party#112]
### Verify steps

- [ ] 我已在标题简短的描述了我所遇到的问题
- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

macOS Sequoiia 15

### 发生问题 mihomo-party 版本

1.12.0

### 描述

Mac 在默认设置 没添加任何配置的情况下 过一两分钟机身发烫严重，cpu占用上百（mihomo-party helper （renderer），在导入代理后 几分钟时间读取超G
<img width="679" alt="截屏2024-08-31 06 59 17" src="https://github.com/user-attachments/assets/4a012115-fa9d-460d-8a78-d4781f1814ad">
<img width="1113" alt="截屏2024-08-31 07 17 16" src="https://github.com/user-attachments/assets/f1cc3731-12a9-4059-b356-869b865ffc7d">
<img width="954" alt="截屏2024-08-31 07 28 33" src="https://github.com/user-attachments/assets/a5ed6a07-a06d-433a-8ab5-d6f5110e7731">
<img width="740" alt="截屏2024-08-31 07 33 02" src="https://github.com/user-attachments/assets/395ff766-343e-4e29-9861-a5b303c14963">

### 重现方式

正常打开

**Comment by zhonghb** [comment]
我这边是非常吃内存，一下吃了 4g 多，只能用轻量模式了

**Comment by PctAIGM** [comment]
1.2.15 内存优化，windows下效果挺明显，可以更新看看

**Comment by ghost** [comment]
现在呢
