### ISSUE TITLE
[Bug] 安装版更新也会显示便携版无法更新

### ISSUE THREAD

**Issue by WENMINGZHUFAN** [pompurin404/mihomo-party#114]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win10

### 发生问题 mihomo-party 版本

1.2.0

### 描述

安装版更新也会显示便携版无法更新

### 重现方式

装了几次都这样

**Comment by ghost** [comment]
注意看，说的是便携模式，不要把数据放在安装目录
