### ISSUE TITLE
[Feature] Subscription updates can be modified, for example, v2ray content can be converted into clash subscription content through scripts.

### ISSUE THREAD

**Issue by ipsfsw** [pompurin404/mihomo-party#116]
### Verify steps

- [ ] 我已在标题简短的描述了我所需的功能
- [ ] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [ ] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

https://github.com/GUI-for-Cores/GUI.for.Clash : The functionality that includes the subscription transformation also has some triggers to modify the configuration. 
Official plugin:  Plugins developed by developers for subscription content conversion.
![PixPin_2024-09-02_06-27-48](https://github.com/user-attachments/assets/c20f6ad2-0427-4493-b7e9-789ecda2d1b1)
Self-written plugin for converting illegal content ： 
![PixPin_2024-09-02_06-28-09](https://github.com/user-attachments/assets/05e7ff82-c428-4976-a03a-07339188123a)

Hope developers can consider the relevant features, thank you!!!

**Comment by ghost** [comment]
覆写功能就可以实现
