### ISSUE TITLE
[Feature] 请教一下软件中的"DNS"和"域名嗅探"这两个功能的作用是什么呢？

### ISSUE THREAD

**Issue by MurphyZX** [pompurin404/mihomo-party#118]
### Verify steps

- [ ] 我已在标题简短的描述了我所需的功能
- [ ] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [ ] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

如题

**Comment by ghost** [comment]
https://wiki.metacubex.one/config/sniff/
