### ISSUE TITLE
[Bug] 在全局代理模式下，切换订阅，并不会记住之前订阅选中的节点，即使打开了“存储选择节点”开关。

### ISSUE THREAD

**Issue by fresh-men** [pompurin404/mihomo-party#119]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win 10

### 发生问题 mihomo-party 版本

1.2.2

### 描述

在全局代理模式下，切换订阅，并不会记住之前订阅选中的节点，切换回去会恢复成direct，即使打开了“存储选择节点”开关。
![image](https://github.com/user-attachments/assets/198d2187-ccea-4875-806b-57eb864266f8)

### 重现方式

开启全局代理，勾选global中节点，切换代理，勾选当前代理的节点，然后切换回去上一个代理，发现global选项变成了direct

**Comment by xishang0128** [comment]
如果是同名策略组,切换之后找不到该名称的节点,会切回默认第一个
