### ISSUE TITLE
[Bug] 开启虚拟网卡后系统设置中的DNS并没有被覆盖

### ISSUE THREAD

**Issue by aLIEz-xue** [pompurin404/mihomo-party#120]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

14.6.1 (23G93)

### 发生问题 mihomo-party 版本

1.2.3

### 描述

开启虚拟网卡后系统设置中的DNS并没有被覆盖
![image](https://github.com/user-attachments/assets/652e498f-094a-43cf-8513-c2342beaec2b)
![image](https://github.com/user-attachments/assets/ea06249c-6698-419d-ba66-30530fe3189a)

### 重现方式

正常启动软件，开启虚拟网卡

**Comment by ghost** [comment]
tg联系我，远程看看

**Comment by aLIEz-xue** [comment]
> tg联系我，远程看看

你TG是？我没找到

**Comment by ghost** [comment]
https://t.me/pompurin404_pm_bot
