### ISSUE TITLE
[Feature] 左侧模块可设置显示隐藏

### ISSUE THREAD

**Issue by ChaoJieGo** [pompurin404/mihomo-party#121]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

建议左侧大模块（比如内核设置）可设置显示隐藏。
平常内核设置这块基本用不着，希望加个功能可以设置这些大模块的显示与隐藏。

我希望mihomo-party的主要原因就是页面精简，功能浓缩，更符合工具定位。
就像现在的开启系统代理，切换全局规则。有很多同类软件把这些最常用功能坐在子页面，需要在二级页面去操作，这就很难受。

**Comment by pompurin404** [comment]
不用的拖到后面去就行了，隐藏模块的话左侧填不满太丑了

**Comment by ChaoJieGo** [comment]
可以拖动那也可以。
