### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by upi0** [pompurin404/mihomo-party#122]
### Verify steps

- [ ] 我已在标题简短的描述了我所遇到的问题
- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

14.6

### 发生问题 mihomo-party 版本

打不开

### 描述

M1版的air 安装完软件。打开提示文件已损坏 ，移除到垃圾桶，不能使用

### 重现方式

下载了三个版本 1.2.1。1.2.2   到最新版本

**Comment by xishang0128** [comment]
![image](https://github.com/user-attachments/assets/32e40b90-8f13-4521-899f-3b1c2a77c0be)
