### ISSUE TITLE
[Feature] 请求适配wayland环境

### ISSUE THREAD

**Issue by wxmup** [pompurin404/mihomo-party#123]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Linux

### 描述

我是arch linux,使用的是kde桌面的wayland环境,安装的包是mihomo-party-electron-bin.
我发现在覆写mihomo-party yaml代码的时候,mihomo-party闪个不停,fcitx5输入法的输入面板非常小,这些都表明当前mihomo-party不运行在wayland.
于是我给添加了--enable-features=WaylandWindowDecorations --ozone-platform-hint=auto --enable-wayland-ime这三个启动参数,但都不能生效.mihomo-party仍然是不能以wayland运行.

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by ghost** [comment]
.config/mihomo-party-flags.conf
```
--ozone-platform=wayland
--enable-wayland-ime
```

**Comment by wxmup** [comment]
> .config/mihomo-party-flags.conf
> 
> ```
> --ozone-platform=wayland
> --enable-wayland-ime
> ```

已解决,谢谢老公
