### ISSUE TITLE
[Feature] 连接 排序 记住上一次的选择

### ISSUE THREAD

**Issue by zuluion** [pompurin404/mihomo-party#124]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

连接 排序 记住上一次的选择
当前版本只要切换到其他界面回来就会被重置为按照时间排序，建议记住上次用户选择
![image](https://github.com/user-attachments/assets/0921d7ae-1f2a-4481-abc8-96a7dc59cbc4)

**Comment by ghost** [comment]
eeb3f7b30a42a1f00abba1afc12556910f3d49e7
