### ISSUE TITLE
[Feature] 能不能设置关闭窗口后不再能切出来 彻底关闭

### ISSUE THREAD

**Issue by cevin** [pompurin404/mihomo-party#125]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

窗口关闭后通过 cmd + tab 还能看到有存在。能不能彻底关闭GUI。只保留核心进程。有需要再通过菜单按钮呼出来。

**Comment by ghost** [comment]
托盘显示网速依赖渲染进程，不能关
