### ISSUE TITLE
[Feature] 是否可以添加菜单栏弹出框直接切换订阅配置，现在每次都要显示GUI才能切换太麻烦了

### ISSUE THREAD

**Issue by 1xiaocainiao** [pompurin404/mihomo-party#126]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

如图,
![QQ_1725417362995](https://github.com/user-attachments/assets/2b483cd4-162f-48ac-b585-a3deeb3d4c1a)

**Comment by psychopasss** [comment]
虽然但是，这不应该是一个高频需求吧？

**Comment by 1xiaocainiao** [comment]
不算，😄
