### ISSUE TITLE
[Bug] Sub-Store启用占用3000端口，即使在应用设置中关闭“启用SubStore”，服务依旧在运行。

### ISSUE THREAD

**Issue by xwvike** [pompurin404/mihomo-party#127]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

11

### 发生问题 mihomo-party 版本

1.2.6

### 描述

这导致的端口占用问题，只能通过退出mihomo-party来解决。
不过我尝试在设置中关闭“启用SubStore”后，重新启动mihomo-party。SubStore是不会运行的。

### 重现方式

任意

**Comment by ghost** [comment]
正常行为，开关只决定启动的时候是否启动substore服务
