### ISSUE TITLE
[Feature] 日志预加载

### ISSUE THREAD

**Issue by zuluion** [pompurin404/mihomo-party#129]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

建议预加载日志前几十条，优化使用体验，目前每次切换到日志是空的，且不会加载之前的日志。类似于CFW 
![image](https://github.com/user-attachments/assets/ee2f9474-3dbb-43d7-8a80-78c93542e7a4)

**Comment by wxchil** [comment]
是的,现在的版本,日志还没等看清楚,就消失了

**Comment by PctAIGM** [comment]
> 是的,现在的版本,日志还没等看清楚,就消失了

https://d.metacubex.one/#/logs 
可以试试webui面板看日志
