### ISSUE TITLE
[Feature] 建议 连接 显示路由的策略组

### ISSUE THREAD

**Issue by zuluion** [pompurin404/mihomo-party#130]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

建议 连接 中显示路由嵌套的策略组 ，当前仅显示了 节点信息 
![image](https://github.com/user-attachments/assets/027f1103-5e2c-40ba-be02-6270172db5f3)

建议类似于yacd的显示效果 
![image](https://github.com/user-attachments/assets/7a5b2478-5b03-4d6d-a5f3-62f071a76011)

**Comment by ghost** [comment]
点开就看到了
