### ISSUE TITLE
[Bug] tun模式下，ssh连接频繁断开

### ISSUE THREAD

**Issue by zjn1234** [pompurin404/mihomo-party#131]
### Verify steps

- [ ] 我已在标题简短的描述了我所遇到的问题
- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [x] #132
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

13.6.6 (22G630)

### 发生问题 mihomo-party 版本

最新版本

### 描述

tun模式下，ssh连接频繁断开，隔一分钟依次打开多个ssh连接，过一会这几个ssh连接会全部同时断开。。

### 重现方式

tun模式下，ssh连接频繁断开，每隔一分钟依次打开3-4个ssh连接，过一会这几个ssh连接会全部同时断开。。

**Comment by xishang0128** [comment]
请确保不是代理关闭的ssh连接,以及这不是gui产生的问题

**Comment by zjn1234** [comment]
@xishang0128 我自己写的配置文件，同样的文件在clash verge rev上[tun模式]就没问题。。但是一使用mihomo-party就频繁断开，关闭了tun就没事。
