### ISSUE TITLE
[Feature] 能否添加是否让GUI保持后台运行的选项

### ISSUE THREAD

**Issue by Alexius66** [pompurin404/mihomo-party#133]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

Mihomo Party 的 GUI 在后台会保持运行，这当然带来了点图标界面秒出的优秀体验，但是我几乎每天只会打开一两次代理软件切换节点，是否没有必要使 GUI 一直保持在后台运行呢，希望可以选择是否关闭以降低后台占用。

**Comment by ghost** [comment]
#139
