### ISSUE TITLE
[Bug] 安装 dmg 包，拖进应用程序后，打开显示软件损坏

### ISSUE THREAD

**Issue by wangdefou-dev** [pompurin404/mihomo-party#136]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

Sonoma 14.6.1

### 发生问题 mihomo-party 版本

1.2.11

### 描述

安装 dmg 包，拖进应用程序后，打开显示软件损坏
Apple M3 Max

### 重现方式

 安装 dmg 包，拖进应用程序后，打开显示软件损坏

**Comment by ghost** [comment]
https://mihomo.party/guides/issue/macos/

**Comment by tkandi** [comment]
> https://mihomo.party/guides/issue/macos/

这个网页不见了

我也遇到了这个问题

**Comment by ghost** [comment]
https://mihomo.party/docs/install
