### ISSUE TITLE
[Bug] windows 上关闭 GUI 界面下的后台内存占用较高

### ISSUE THREAD

**Issue by dyphire** [pompurin404/mihomo-party#138]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

23H2

### 发生问题 mihomo-party 版本

1.2.11

### 描述

在 windows 上当关闭 GUI 界面后 mihomo-party 的后台内存占用依然很高
![image](https://github.com/user-attachments/assets/f419e3f8-d164-4c22-842d-06e845aa82a5)
我观察了下隔壁 clash-nyanpasu 的占用情况。它在打开 GUI 界面和最小化时有着和 mihomo-party 接近的内存占用，但当关闭 GUI 界面后 clash-nyanpasu 会结束打开的 webview2 相关进程从而维持了较低的内存占用
![image](https://github.com/user-attachments/assets/a2d76407-bfc6-4e5a-9a9f-503d9295baad)

希望 mihomo-party 在关闭 GUI 界面后可以像 clash-nyanpasu 那样结束不再需要的一些 webview2 进程，保持较低的后台内存占用

### 重现方式

打开 mihomo-party 后关闭 GUI 程序界面，观察后台的内存占用

**Comment by xishang0128** [comment]
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

https://github.com/pompurin404/mihomo-party/actions/runs/10751249994

**Comment by dyphire** [comment]
> * [x]  我已经使用最新的测试版本测试过，问题依旧存在
> 
> https://github.com/pompurin404/mihomo-party/actions/runs/10751249994

轻量模式和我提出的这个问题不完全相关，轻量模式完全杀掉了主程序导致托盘程序也没了。我提的这个是想请求解决关闭 GUI 界面下的后台内存占用较高的问题，而不是彻底杀掉主程序，需要保留从托盘菜单更改设置和打开 GUI 的功能

综上，轻量模式并没有解决这个问题，请考虑重新打开它

**Comment by xishang0128** [comment]
> > * [x]   我已经使用最新的测试版本测试过，问题依旧存在
> > 
> > https://github.com/pompurin404/mihomo-party/actions/runs/10751249994
> 
> 轻量模式和我提出的这个问题不完全相关，轻量模式完全杀掉了主程序导致托盘程序也没了。我提的这个是想请求解决关闭 GUI 界面下的后台内存占用较高的问题，而不是彻底杀掉主程序，需要保留从托盘菜单更改设置和打开 GUI 的功能
> 
> 综上，轻量模式并没有解决这个问题，请考虑重新打开它

那这也不该算是bug,请重新发起issues

**Comment by dyphire** [comment]
> > > * [x]    我已经使用最新的测试版本测试过，问题依旧存在
> > > 
> > > https://github.com/pompurin404/mihomo-party/actions/runs/10751249994
> > 
> > 
> > 轻量模式和我提出的这个问题不完全相关，轻量模式完全杀掉了主程序导致托盘程序也没了。我提的这个是想请求解决关闭 GUI 界面下的后台内存占用较高的问题，而不是彻底杀掉主程序，需要保留从托盘菜单更改设置和打开 GUI 的功能
> > 综上，轻量模式并没有解决这个问题，请考虑重新打开它
> 
> 那这也不该算是 bug, 请重新发起 issues

#139
