### ISSUE TITLE
[Feature] 改善 windows 上关闭 GUI 界面下的后台内存占用

### ISSUE THREAD

**Issue by dyphire** [pompurin404/mihomo-party#139]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

目前在 windows 上关闭 GUI 界面后 mihomo-party 的后台内存占用依然很高
![image](https://github.com/user-attachments/assets/f419e3f8-d164-4c22-842d-06e845aa82a5)
我观察了下隔壁 clash-nyanpasu 的占用情况。它在打开 GUI 界面和最小化时有着和 mihomo-party 接近的内存占用，但当关闭 GUI 界面后 clash-nyanpasu 会结束打开的 webview2 相关进程从而维持了较低的内存占用
![image](https://github.com/user-attachments/assets/a2d76407-bfc6-4e5a-9a9f-503d9295baad)

希望 mihomo-party 在关闭 GUI 界面后可以像 clash-nyanpasu 那样结束不再需要的一些 webview2 进程，保持较低的后台内存占用

PS: 新的轻量模式完全杀掉了主程序导致托盘程序也没了，该功能请求只是想改善 windows 上关闭 GUI 界面下主程序的后台内存占用，想要保留从托盘菜单更改设置和打开 GUI 界面的功能

**Comment by ghost** [comment]
做不了，现在mac的托盘网速显示是依赖前端渲染的，而且之前测试过，对于electron来说，关闭窗口降低的内存也并不是很多，不会像tauri那样彻底，所以我觉得没有必要。

**Comment by subframe7536** [comment]
electron 架构决定了最低四个进程。。。这个动不了的

**Comment by dyphire** [comment]
其实 mac 上反而 mihomo-party 的占用比 clash-nyanpasu 低，因为两者都无法彻底关掉前端渲染，所以就没提  mac 上的优化。当然  mac 上 clashx.meta 的占用是最低的，它的前端就是个 webui 面板改

windows 上没法改善后台内存占用的话就算了。mihomo-party 的 ui 感觉是前端里颜值最高的，但 electron 的后台内存占用还是有点离谱了

**Comment by glassywater** [comment]
> 其实 mac 上反而 mihomo-party 的占用比 clash-nyanpasu 低，因为两者都无法彻底关掉前端渲染，所以就没提 mac 上的优化。当然 mac 上 clashx.meta 的占用是最低的，它的前端就是个 webui 面板改
> 
> windows 上没法改善后台内存占用的话就算了。mihomo-party 的 ui 感觉是前端里颜值最高的，但 electron 的后台内存占用还是有点离谱了

颜值的话也可以看看gui for c/s，跟win11的mica搭配起来非常好看，占用还非常的低
