### ISSUE TITLE
[Bug] 启动内核失败

### ISSUE THREAD

**Issue by ttc440055** [pompurin404/mihomo-party#140]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win10×64

### 发生问题 mihomo-party 版本

1.2.12

### 描述

![1c0da53ecd59b41b74996b7ab98d38d4](https://github.com/user-attachments/assets/ceeef20c-c31a-4b6f-bd3e-4906fff221b9)
![4100565e9c1beb3f5184b5a73c06e850](https://github.com/user-attachments/assets/9d8883ec-384d-4608-8a80-8213b1edbcce)

### 重现方式

添加链接显示内核启动出错

**Comment by ghost** [comment]
打开你导入的订阅文件检查一下内容是否正确
