### ISSUE TITLE
[Bug] 大佬，最新版本直连规则失效了

### ISSUE THREAD

**Issue by huasheng6656** [pompurin404/mihomo-party#141]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win11 23h2

### 发生问题 mihomo-party 版本

v1.2.13

### 描述

我今天更新后发现直连规则不生效，我去那个复写文档看了，发现直连规则的代码没变，但就是不生效，然后我退回了v1.2.12，发现可以了
![image](https://github.com/user-attachments/assets/4f71deca-c7ed-477d-b39a-5ac0687d4b78) 
![image](https://github.com/user-attachments/assets/5ae0def5-26c1-48d6-a910-f45f689e58a7)

### 重现方式

我今天更新后想登入linux do，发现登不上去

**Comment by xishang0128** [comment]
无可用信息

**Comment by ghost** [comment]
没有失效
