### ISSUE TITLE
开关

### ISSUE THREAD

**Issue by zwl55555** [pompurin404/mihomo-party#142]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

v1.2.13

### 发生问题 mihomo-party 版本

mihomo-party-windows-1.2.13-x64-setup.exe

### 描述

软件内部的关闭按钮似乎并没有起到真正的开启和关闭的作用，只要我开着软件 不论开关是关闭还是打开 都是连接状态，只有当我把软件退出运行才真正的关闭了connect

### 重现方式

https://github.com/user-attachments/assets/2378a06d-d467-44eb-82ad-0ecb3e682d9e

**Comment by xishang0128** [comment]
看任务管理器进程

**Comment by ghost** [comment]
虚拟网卡不还开着吗

**Comment by zwl55555** [comment]
Uploading 17d13117824cd14526ff829810ee24cf - Compressed with FlexClip - Compressed with FlexClip.mp4…

**Comment by zwl55555** [comment]
可以看详细的
视频

**Comment by zwl55555** [comment]
Uploading 17d13117824cd14526ff829810ee24cf - Compressed with FlexClip - Compressed with FlexClip.mp4…

**Comment by ghost** [comment]
建议看看软件内的新手引导

**Comment by zwl55555** [comment]
> 建议看看软件内的新手引导

你看新创建的 那个 里面有视频
