### ISSUE TITLE
[Feature] 使用substore后转换的链接只包含节点信息。如何用配置模板？

### ISSUE THREAD

**Issue by lionlee0724** [pompurin404/mihomo-party#143]
### Verify steps

- [ ] 我已在标题简短的描述了我所需的功能
- [ ] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [ ] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

RT 比如用肥羊转换的策略组？

**Comment by HTT0715** [comment]
请自行寻找sub-store的使用教程，而不是在一个集成sub-store的GUI项目下面提出issue！

**Comment by xream** [comment]
生成 clash.meta(mihomo) 配置示例 (https://t.me/zhetengsha/1234)

Surfboard 远程托管配置示例 (https://t.me/zhetengsha/1111)

生成 sing-box 配置 (https://t.me/zhetengsha/1070)

生成 sing-box 机场入口+落地节点 代理链 示例 (https://t.me/zhetengsha/1241)

脚本&教程合集 https://t.me/zhetengsha/214
