### ISSUE TITLE
[Feature] 能够更换开发框架，其实挺好看的，但是程序本身占用太过恐怖，知道是election的锅

### ISSUE THREAD

**Issue by cnsn521** [pompurin404/mihomo-party#144]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

能够更换开发框架，其实挺好看的，但是程序本身占用太过恐怖，知道是election的锅，所以希望开发者在未来考虑更换框架，也希望将来能够尽一份力

**Comment by xishang0128** [comment]
换不了

**Comment by cnsn521** [comment]
你又没贡献gui的开发，回答的这么不客气。。。

**Comment by Hayakee** [comment]
有没有一种可能，你看看contributors那里有没有这位呢
