### ISSUE TITLE
[Feature] 点击延迟测试可以自动弹出被测试代理组下节点列表

### ISSUE THREAD

**Issue by woodenpi** [pompurin404/mihomo-party#145]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

例如，点击下图“节点选择”代理组的延迟测试按钮
![image](https://github.com/user-attachments/assets/c2df7c17-ee42-452b-a363-bea7a937e971)
希望自动弹出下图列表
![image](https://github.com/user-attachments/assets/f342acc9-9557-438a-8a2b-4a2ea9fe9bf1)

**Comment by Hunerk** [comment]
我也希望有这功能，现在点击测试按钮是打开代理组。能改成打开代理组的同时测试已开始就更好了。谢谢

**Comment by yiteei** [comment]
> 我也希望有这功能，现在点击测试按钮是打开代理组。能改成打开代理组的同时测试已开始就更好了。谢谢

智齿
