### ISSUE TITLE
添加节点排序功能

### ISSUE THREAD

**Issue by cnfree8964** [pompurin404/mihomo-party#146]
### Verify steps

- [ ] 我已在标题简短的描述了我所需的功能
- [ ] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [ ] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

我的节点比较多，希望可以添加按照速度或者名称进行排序的按钮，谢谢大佬们。

**Comment by xishang0128** [comment]
![image](https://github.com/user-attachments/assets/b6a21674-d4fe-40c6-a0fd-a3a0277bb272)
