### ISSUE TITLE
[Bug] 在Windows开机自启后，系统代理仍不会(被)覆盖

### ISSUE THREAD

**Issue by AEDELSTAN** [pompurin404/mihomo-party#148]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

24H2

### 发生问题 mihomo-party 版本

v1.2.13

### 描述

MihomoParty已开自启，关机前软件内 _系统代理_ 开关为开启状态。开机登录且软件自启后， _系统代理_ 设置没有覆盖掉系统的代理。（似乎并不是百分百出现这个问题）

下图为开机后的截图
![0b6fca14-19fc-4a1f-8a02-9b735c0fea32](https://github.com/user-attachments/assets/bcfc20ec-4a6d-48e0-86d4-db41e2bdcad9)

### 重现方式

开启软件自启，重启前开启软件内系统代理开关

**Comment by ghost** [comment]
还有问题吗
