### ISSUE TITLE
[Bug] 没有打开系统代理的情况下不应该自动启动PAC服务

### ISSUE THREAD

**Issue by cnzgray** [pompurin404/mihomo-party#149]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

13.6.9 (22G830)

### 发生问题 mihomo-party 版本

v1.2.13

### 描述

如图未打开系统代理，但是在本地端口列表中显示了10000端口被打开。

<img width="254" alt="image" src="https://github.com/user-attachments/assets/0b393d20-d4f9-499f-91b9-61154b08a9f6">

通过查看代码发现10000端口是给PAC使用的，我认为在系统代理未启用的情况下10000端口不应该被自动创建。

PS: 系统代理打开的情况下，如果代理模式设置为**手动**是否也不应该打开？

### 重现方式

启动程序即可复现

**Comment by xishang0128** [comment]
PAC也可给局域网使用,不仅用于系统代理,所以默认监听

**Comment by cnzgray** [comment]
那是否应该给个选项让用户自行控制是否开启呢？

**Comment by zyyysxd** [comment]
+1，会被局域网内nmap扫到，返回7890端口，一下子就被看到使用了代理软件
