### ISSUE TITLE
[Feature] 有没有使用教程

### ISSUE THREAD

**Issue by fuxin-mail** [pompurin404/mihomo-party#15]
### Verify steps

- [ ] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [ ] 我已在标题简短的描述了我所需的功能
- [ ] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

有没有小白用户的使用指导？

**Comment by ghost** [comment]
暂时没有时间写文档，不过用法跟其他同类软件差不多

**Comment by misakaok** [comment]
@pompurin404 为什么安装包都很大

**Comment by ghost** [comment]
https://mihomo.party
