### ISSUE TITLE
[Feature] 开机自动开启轻量

### ISSUE THREAD

**Issue by WENMINGZHUFAN** [pompurin404/mihomo-party#150]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

希望改为开机自启默认直接进入轻量模式

**Comment by ghost** [comment]
你把延迟调低就好了
