### ISSUE TITLE
[Bug] 应用内更新按钮位置疑似异常

### ISSUE THREAD

**Issue by YifePlayte** [pompurin404/mihomo-party#151]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11 22631.4169

### 发生问题 mihomo-party 版本

v1.2.14

### 描述

更新按钮疑似位置不对，更新按钮挡住应用名称真的是预期位置吗（（
![image](https://github.com/user-attachments/assets/5c48cc54-f0fe-4edd-885f-2a3ad5c59c2a)
![image](https://github.com/user-attachments/assets/116300e5-691b-40f4-af17-28fe78477d22)

### 重现方式

留在一个旧版本，等一个新版本，然后观察应用内更新按钮

**Comment by ghost** [comment]
是正常的，悬浮在Party上面，右侧后续可能会有其他按钮，所以这么做了
