### ISSUE TITLE
[Feature] 重启面板可以实现不干扰轻量模式已启动的内核吗

### ISSUE THREAD

**Issue by WENMINGZHUFAN** [pompurin404/mihomo-party#152]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [x] 这是向GUI程序提出的功能请求,而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

重启面板可以实现不干扰轻量模式已启动的内核吗，进入轻量模式也不用重启内核，就是平时轻量模式需要时使用面板

**Comment by ghost** [comment]
做不到，不重启没法继续接管

**Comment by WENMINGZHUFAN** [comment]
> 做不到，不重启没法继续接管

好的，好快
