### ISSUE TITLE
[Bug] 1.2.15-arm64  键盘粘贴快捷键失效

### ISSUE THREAD

**Issue by jfeng018** [pompurin404/mihomo-party#155]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

14.5

### 发生问题 mihomo-party 版本

1.2.15

### 描述

 1.2.15-arm64  键盘粘贴快捷键失效

### 重现方式

打开皮套，利用键盘粘贴订阅地址

**Comment by Mr-zhaohy** [comment]
same issues

**Comment by ghost** [comment]
@jfeng018 这是新版软件导致的还是新版系统导致的
