### ISSUE TITLE
可否加入 winget package repo

### ISSUE THREAD

**Issue by sephiroth233** [pompurin404/mihomo-party#156]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [x] 这是向GUI程序提出的功能请求,而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

可否加入winget package repo，这样在windows端可以使用winget install --id Mihomo-Party安装，如图所示：
![image](https://github.com/user-attachments/assets/6b266ded-4789-4554-934b-72499b3dc864)
我向winget repo提交了 1.2.16 版本 ，请知晓 [New package: mihomo-party.mihomo-party version 1.2.16](https://github.com/microsoft/winget-pkgs/pull/173043)
@pompurin404

**Comment by sephiroth233** [comment]
![image](https://github.com/user-attachments/assets/9b967940-9434-47d8-b3f5-ae817f9abefc)
已上架winget

**Comment by JOJOforshaun** [comment]
> ![image](https://private-user-images.githubusercontent.com/102894885/367158099-9b967940-9434-47d8-b3f5-ae817f9abefc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDA0NTMsIm5iZiI6MTcyNjQwMDE1MywicGF0aCI6Ii8xMDI4OTQ4ODUvMzY3MTU4MDk5LTliOTY3OTQwLTk0MzQtNDdkOC1iM2Y1LWFlODE3ZjlhYmVmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxMTM1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWJkMWQzZDg3NmVhYTBmOWNmNjZmYWU5NDRjZTM3MThlNWUxYmFmMDc4NDIzNzdmZWVkNGNmMmM5ODZhNDBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IdT65vReOXneVb8PwxzU2PAV1IJVhyEeojFwJnqjdUs) 已上架winget

能不能也上架homebrew

**Comment by ghost** [comment]
> 能不能也上架homebrew

```bash
brew tap mihomo-party-org/mihomo-party

brew install --cask mihomo-party
```

**Comment by ghost** [comment]
winget现在可以跟随仓库发布自动更新了

**Comment by sephiroth233** [comment]
给佬点赞
