### ISSUE TITLE
开关似乎是失效的

### ISSUE THREAD

**Issue by zwl55555** [pompurin404/mihomo-party#157]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

v1.2.16

### 发生问题 mihomo-party 版本

mihomo-party-windows-1.2.16-x64-setup.exe

### 描述

软件内部的关闭按钮似乎并没有起到真正的开启和关闭的作用，只要我开着软件 不论开关是关闭还是打开 都是连接状态，只有当我把软件退出运行才真正的关闭了connect

### 重现方式
请看视频

**Comment by zwl55555** [comment]
https://github.com/user-attachments/assets/fa6c7db9-d059-42c9-8f50-4b7dcf658c2e

**Comment by zwl55555** [comment]
https://github.com/user-attachments/assets/0304edc3-26f9-4c2a-851b-2e77dbea0179

**Comment by xishang0128** [comment]
https://github.com/user-attachments/assets/8232f3c6-4ca0-4d7a-b6d3-623742787e61

无法复现,请提供更多信息

**Comment by zwl55555** [comment]
hhhh

**Comment by ghost** [comment]
@zwl55555 应该看系统设置里面系统代理的变化，只看现象啥也看不出来

**Comment by zwl55555** [comment]
https://github.com/user-attachments/assets/f61a8cfc-c722-48bb-bbd3-0314cc63d74b
找到原因了 打开系统代理的时候开起来设置里的代理开关 但是关闭系统代理时并未关闭系统设置里面的代理开关

**Comment by zwl55555** [comment]
找到原因了 打开系统代理的时候开起来设置里的代理开关 但是关闭系统代理时并未关闭系统设置里面的代理开关

**Comment by zwl55555** [comment]
![image](https://github.com/user-attachments/assets/17c3f6d0-e177-45f2-a268-b4e16795affc)

**Comment by ghost** [comment]
https://github.com/pompurin404/mihomo-party/actions/runs/10845261426

试试这个

**Comment by zwl55555** [comment]
> https://github.com/pompurin404/mihomo-party/actions/runs/10845261426
> 
> 试试这个

你这个是ok的 我所说的bug 这个关闭之后关闭了系统的代理开关

**Comment by zwl55555** [comment]
> > https://github.com/pompurin404/mihomo-party/actions/runs/10845261426
> > 试试这个
> 
> 你这个是ok的 我所说的bug 这个关闭之后关闭了系统的代理开关

bug 修复完成了 更一个版本吧
