### ISSUE TITLE
[Bug] Arch Linux上安装失败

### ISSUE THREAD

**Issue by Ithde** [pompurin404/mihomo-party#16]
### Verify steps

- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [ ] 我已在标题简短的描述了我所遇到的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Linux

### 系统版本

Arch Linux

### 发生问题 mihomo-party 版本

0.5.0-1

### 描述

在 Arch Linux 上安装时无法安装成功。
报错内容
~~~
==> Validating source_x86_64 files with sha256sums...
    mihomo-party-0.5.0-x86_64.deb ... Passed
==> Making package: mihomo-party-bin 0.5.0-1 (2024年08月14日 星期三 14时32分56秒)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found mihomo-party-0.5.0-x86_64.deb
==> Validating source_x86_64 files with sha256sums...
    mihomo-party-0.5.0-x86_64.deb ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting mihomo-party-0.5.0-x86_64.deb with bsdtar
==> Sources are ready.
mihomo-party-bin-0.5.0-1: parsing pkg list...
==> Making package: mihomo-party-bin 0.5.0-1 (2024年08月14日 星期三 14时32分58秒)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat 'mihomo-party.sh': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error: failed to build 'mihomo-party-bin-0.5.0-1': 
error: packages failed to build: mihomo-party-bin-0.5.0-1
~~~
不知道还要不要提供其他的信息。

### 重现方式

目前这个版本可以稳定触发，尝试过清空缓存也没有用

**Comment by ghost** [comment]
是从AUR安装的吗

**Comment by Ithde** [comment]
> 是不是从AUR安装的

是的，使用 paru 安装，当然也试了 clone 下来然后 `makepkg -si`，但是都失败了，报错内容都是一致的。

**Comment by ghost** [comment]
我刚刚测试了没有问题

**Comment by ghost** [comment]
https://aur.archlinux.org/packages?O=0&K=mihomo-party

不行就试试其他包

**Comment by Ithde** [comment]
> https://aur.archlinux.org/packages?O=0&K=mihomo-party
> 
> 不行就试试其他包

这些包都试了一遍，每次都清除缓存后尝试安装其他的包，但是报错内容都差不多。
大致的报错内容:
mihomo-party
~~~
Error fetching latest release version: fetch failed

 ELIFECYCLE  Command failed with exit code 1.
==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'mihomo-party-0.5.2-1':
error: packages failed to build: mihomo-party-0.5.2-1
~~~

mihomo-party-bin
~~~
install: cannot stat 'mihomo-party.sh': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error: failed to build 'mihomo-party-bin-0.5.2-1':
error: packages failed to build: mihomo-party-bin-0.5.2-1
~~~

mihomo-party-git
~~~
install: cannot stat 'mihomo-party.sh': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error: failed to build 'mihomo-party-git-0.5.2.r0.g2a4822f-1':
error: packages failed to build: mihomo-party-git-0.5.2.r0.g2a4822f-1
~~~

mihomo-party-electron
~~~
install: cannot stat 'mihomo-party.sh': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error: failed to build 'mihomo-party-electron-0.5.2-1':
error: packages failed to build: mihomo-party-electron-0.5.2-1
~~~

mihomo-party-electron-bin
~~~
install: cannot stat 'mihomo-party.sh': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error: failed to build 'mihomo-party-electron-bin-0.5.2-1':
error: packages failed to build: mihomo-party-electron-bin-0.5.2-1
~~~
这种报错原因以前在安装 AUR 中的其他软件时也出现过，然后重装系统就解决了。
实在不行的话我就等下一个版本，或者再重装一遍。

**Comment by Ithde** [comment]
> > https://aur.archlinux.org/packages?O=0&K=mihomo-party
> > 不行就试试其他包
> 
> 这些包都试了一遍，每次都清除缓存后尝试安装其他的包，但是报错内容都差不多。 大致的报错内容: mihomo-party
> 
> ```
> Error fetching latest release version: fetch failed
> 
>  ELIFECYCLE  Command failed with exit code 1.
> ==> ERROR: A failure occurred in prepare().
>     Aborting...
> error: failed to build 'mihomo-party-0.5.2-1':
> error: packages failed to build: mihomo-party-0.5.2-1
> ```
> 
> mihomo-party-bin
> 
> ```
> install: cannot stat 'mihomo-party.sh': No such file or directory
> ==> ERROR: A failure occurred in package().
>     Aborting...
> error: failed to build 'mihomo-party-bin-0.5.2-1':
> error: packages failed to build: mihomo-party-bin-0.5.2-1
> ```
> 
> mihomo-party-git
> 
> ```
> install: cannot stat 'mihomo-party.sh': No such file or directory
> ==> ERROR: A failure occurred in package().
>     Aborting...
> error: failed to build 'mihomo-party-git-0.5.2.r0.g2a4822f-1':
> error: packages failed to build: mihomo-party-git-0.5.2.r0.g2a4822f-1
> ```
> 
> mihomo-party-electron
> 
> ```
> install: cannot stat 'mihomo-party.sh': No such file or directory
> ==> ERROR: A failure occurred in package().
>     Aborting...
> error: failed to build 'mihomo-party-electron-0.5.2-1':
> error: packages failed to build: mihomo-party-electron-0.5.2-1
> ```
> 
> mihomo-party-electron-bin
> 
> ```
> install: cannot stat 'mihomo-party.sh': No such file or directory
> ==> ERROR: A failure occurred in package().
>     Aborting...
> error: failed to build 'mihomo-party-electron-bin-0.5.2-1':
> error: packages failed to build: mihomo-party-electron-bin-0.5.2-1
> ```
> 
> 这种报错原因以前在安装 AUR 中的其他软件时也出现过，然后重装系统就解决了。 实在不行的话我就等下一个版本，或者再重装一遍。

不出意外，应该是我的系统的问题，不过好像没这个能力去修。

**Comment by ghost** [comment]
clone下来的aur仓库里面没有mihomo-party.sh吗

**Comment by Ithde** [comment]
> clone下来的aur仓库里面没有mihomo-party.sh吗

有的。
有：`PKGBUILD`,  `mihomo-party.install`,  `mihomo-party.sh` 三个文件

**Comment by Grayer0113** [comment]
修改 `PKGBUILD` 中的
`cd ${pkgdir}/../..  `  为
`cd $srcdir/${pkgname}-${pkgver}/aur/${pkgname}`
可以解决问题

**Comment by ghost** [comment]
不应该从源仓库拿，文件是放在aur仓库的

**Comment by Grayer0113** [comment]
应该在 `PKGBUILD` 中包含该文件，Arch 才会将其认为是构建所必须的文件。
部分用户可能会在 tmp 目录构建软件，如果未显示声明一个文件的必要性，那么 Arch 不会将其链接到构建目录，导致构建时产生 `No such file or directory` 这样的警告。

**Comment by ghost** [comment]
OK，下个版本我加到source里面

**Comment by Ithde** [comment]
应该就是这个原因了，我去修改了一下 `makepkg.conf` 文件，把 `BUILDDIR` 重新注释掉了，然后就安装成功了。
