### ISSUE TITLE
[Bug] 时间一久就白屏

### ISSUE THREAD

**Issue by 18230** [pompurin404/mihomo-party#160]
### Verify steps

- [ ] 我已在标题简短的描述了我所遇到的问题
- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

时间一久就白屏

### 发生问题 mihomo-party 版本

时间一久就白屏

### 描述

时间一久就白屏，然后点不动

### 重现方式

时间一久就白屏

**Comment by xishang0128** [comment]
![image](https://github.com/user-attachments/assets/549381e9-ccb0-4c13-9a68-a61887e2081b)

运行十天,无法复现,请提供更多信息

**Comment by xishang0128** [comment]
由于该问题在过去的一段时间内没有得到进一步的反馈或更新，我们决定将其关闭。如果您仍然遇到此问题或有新的信息，请随时重新打开此 issue 或创建一个新的 issue
