### ISSUE TITLE
[Feature] 可以往覆写后的代理组中，添加所有已有的代理节点吗？

### ISSUE THREAD

**Issue by Kam323** [pompurin404/mihomo-party#161]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

因为每次添加新的代理组后，其中代理节点一项订阅中有很多节点，而且节点名称不确定，无法一一穷举添加到代理组中，如有方法实现还望告知，谢谢

**Comment by xishang0128** [comment]
看内核文档,或者使用js覆写
