### ISSUE TITLE
[Bug] win11安装过后打不开，也没报错

### ISSUE THREAD

**Issue by xinstart-0** [pompurin404/mihomo-party#162]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win11 23H2

### 发生问题 mihomo-party 版本

1.2.19

### 描述

win11安装过后打不开，也没报错

### 重现方式

安装1.2.19的mihomo-party-windows-1.2.19-x64-setup/mihomo-party-windows-1.2.19-x64-portable，安装完成后打开没反应

**Comment by ghost** [comment]
管理员权限启动试试

**Comment by xinstart-0** [comment]
> 管理员权限启动试试

我都试了，毫无反应的

**Comment by ghost** [comment]
@xingxin1590 任务管理器有没有进程

**Comment by gsxgmpkt9020** [comment]
为什么关了，怎么解决的？WIN 10同样无解

**Comment by AnyWAT** [comment]
WIN10PRO下V1.5.2-1.7.1便携版一直正常。。。网云：有便携版就不用安装版？

**Comment by gsxgmpkt9020** [comment]
> WIN10PRO下V1.5.2-1.7.1便携版一直正常。。。网云：有便携版就不用安装版？

全网唯一真神正解！

**Comment by myltj** [comment]
我也是一样的问题
1.win11
2.mihomo-party-windows-1.7.2-x64-setup.exe
3.安装后右击以管理员运行，还是无法运行

**Comment by AnyWAT** [comment]
如已非正常启动，在以管理员身份运行（自动建立系统计划任务）之前，务必将已在运行的任一进程“结束进程树”来终止所有相关进程。。。

**Comment by AnyWAT** [comment]
> > WIN10PRO下V1.5.2-1.7.1便携版一直正常。。。网云：有便携版就不用安装版？
> 
> 全网唯一真神正解！

[编程随想](https://program-think.blogspot.com/2014/12/gfw-privoxy.html )：俺本人比较喜欢“绿色软件”

![Image](https://github.com/user-attachments/assets/16de02bb-2680-4d1b-af40-51f973e82ad1)

**Comment by myltj** [comment]
谢谢上面的两位兄弟，回复真快，最后我就是下载绿色版，再把后台的已运行的程序关闭，再打开运行一次就可以看到程序了
