### ISSUE TITLE
[Bug] proxy-providers放在覆写里面之后，订阅里节点为0

### ISSUE THREAD

**Issue by myrshfrs** [pompurin404/mihomo-party#163]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

版本	Windows 11 企业版 版本	21H2 安装日期	‎2023/‎12/‎16 操作系统版本	22000.3197 体验	Windows 功能体验包 1000.22004.1000.0

### 发生问题 mihomo-party 版本

v1.2.19

### 描述

覆写里面内容：

p: &p {type: http, interval: 86400, health-check: {enable: true, url: http://nohttps.nl, interval: 1800, timeout: 5000}}
proxy-providers:
  sub1: # 在此将 "http://your-service-provider" 替换为你的机场订阅，推荐使用 base64 或者 node list
    url: https://jjsubmarines.com/members/
    override:
      skip-cert-verify: true
    <<: *p
  sub2: # 在此将 "http://your-service-provider" 替换为你的机场订阅，推荐使用 base64 或者 node list
    url: https://jmssub.net/members/
    override:
      skip-cert-verify: true
    <<: *p
  sub3: # 在此将 "http://your-service-provider" 替换为你的机场订阅，推荐使用 base64 或者 node list
    url: https://jjsubmarines.com/members/
    override:
      skip-cert-verify: true
    <<: *p
    #override: # 修改节点前后缀时，需移除前方的 "#" 符号
      #additional-prefix: "节点前缀"
      #additional-suffix: "节点后缀"

配置采用远程配置：https://gist.githubusercontent.com/myrshfrs/79d5e3a03cf6a5bd2083334044ace797/raw/ 已经打开了覆写

外部代理-代理集合sub0~sub3后面有更新时间但是节点数都是0，手动点击更新全部也不起作用

同样的配置方案用在verge里没有问题

### 重现方式

按照描述里新建一个覆写配置，然后订阅上面的远程配置，就可以复现

**Comment by myrshfrs** [comment]
补充一下 把覆写的配置直接跟远程配置合并 放在同一个本地配置里面 正常工作

**Comment by ghost** [comment]
https://github.com/mihomo-party-org/mihomo-party/actions/runs/10877707917

试试这个

**Comment by myrshfrs** [comment]
> https://github.com/mihomo-party-org/mihomo-party/actions/runs/10877707917
> 
> 试试这个

这个版本可以了 感谢
