### ISSUE TITLE
请修复360检测到木马等问题。

### ISSUE THREAD

**Issue by qwerzxcva** [pompurin404/mihomo-party#164]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 最新版本，首次启用

首次启动就被360拦截，后面每一次操作都会被360提示修改什么系统进程，当我全部设置完后，点击启动系统代理，又被360报木马病毒，请修复该问题。

**Comment by ghost** [comment]
1. 不是软件的问题，不会修
2. `提示修改什么系统进程` 这么模糊的信息我怎么排查
3. 请让360修复
