### ISSUE TITLE
[Bug] 苹果i内核 1.2.20版本，点击开机自启没有反应

### ISSUE THREAD

**Issue by heyzayz** [pompurin404/mihomo-party#166]
### Verify steps

- [ ] 我已在标题简短的描述了我所遇到的问题
- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

Intel Core i5   14.5 

### 发生问题 mihomo-party 版本

1.2.20

### 描述

点击开机自启按钮没有反应

### 重现方式

点击开机自启按钮没有反应

**Comment by ghost** [comment]
#83
