### ISSUE TITLE
[Bug] 使用虚拟网卡后，本机的rustdesk无法被访问

### ISSUE THREAD

**Issue by hubumulity** [pompurin404/mihomo-party#168]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

11

### 发生问题 mihomo-party 版本

1.2.20

### 描述

我在公司电脑上使用party程序并使用虚拟网卡模式进行代理，公司电脑上运行rustdesk客户端，rustdesk服务端安装于华为云国内服务器。当我在家里远程连接公司rustesk时会提示：远程主机关闭了连接。把party的虚拟网卡模式关闭后可正常远程公司电脑。

### 重现方式

第一步：在公司电脑打开party客户端开始虚拟网卡模式。
第二部：在公司电脑打开rustdesk客户端并配置好自建ID服务器。
第三步：在家里远程连接公司rustdesk客户端。

**Comment by ghost** [comment]
我测试没有问题，看日志吧

**Comment by StevenYangCoder** [comment]
我开启clash的tun模式后，就没法使用rustdesk了，我使用zerotier在公司和家里面组了局域网，然后在家里面的vps上搭建了rustdesk服务端

**Comment by kailiu42** [comment]
我也遇到了这个问题，但表现有点奇怪。

我的RustDesk是连接到自建的服务端的，搭建在自家路由器上。当我被控的笔记本在家里的时候，Clash party开启虚拟网卡模式不会影响到连入RustDesk。但当我被控笔记本在外部网络时，它上面的RustDesk会显示网络连接正常，但连入时连入端会显示连接被对方关闭（这里的对方也就是被控的笔记本）。只要关掉虚拟网卡马上就可以正常连接。

我看了连接日志，RustDesk是直连。试过把RustDesk.exe加入process-name匹配永远直连，试过tun模式堆栈3中方式，试过重设防火墙，开启/关闭严格路由，开启/关闭自动选择流量出口接口，都不行。甚至只要先关闭虚拟网卡或者退出clash party，连上RustDesk后再开启虚拟网卡，连接也不会断，但是只要关闭连接后就没有办法再新建连接。
