### ISSUE TITLE
[Bug] 使用规则覆写绕过指定域名时，配置不生效

### ISSUE THREAD

**Issue by OnceNever** [pompurin404/mihomo-party#169]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11 家庭中文版 23H2

### 发生问题 mihomo-party 版本

v1.2.20

### 重现方式

1、新建覆写规则，使用+rule的方式指定DOMAIN，使用直连方式。
2、将覆写配置导入到订阅（订阅中编辑，选择新建的覆写文件，确定）。
3、访问指定网站失败（指定网站只能直连访问）

**Comment by PctAIGM** [comment]
上周在tg群里见过有人用DOMAIN规则说覆写没生效的。
由于你的信息太少，没法给你赛博诊脉。
所以需要自己看看是否没搞清楚DOMAIN和DOMAIN-SUFFIX的区别

**Comment by OnceNever** [comment]
你好！这是我的覆写文件，并且已导入到订阅。
![image](https://github.com/user-attachments/assets/49607f1e-9f44-4602-92b1-cec98060a760)

并且可以在规则中找到这两条规则：
![image](https://github.com/user-attachments/assets/d7b03e52-79b5-4248-97ca-65d8956604f7)

但我访问 https://shared.oaifree.com/ 就是连不上，关掉代理就可以

**Comment by xishang0128** [comment]
@OnceNever 反馈连接问题请贴  连接日志

**Comment by OnceNever** [comment]
> @OnceNever 反馈连接问题请贴 连接日志

你好，出来了很多dns解析错误：
![image](https://github.com/user-attachments/assets/9f38a5a6-6c15-45c8-9921-4e6a0ed4b4d9)

**Comment by xishang0128** [comment]
@OnceNever 贴出dns配置(运行时配置)

**Comment by OnceNever** [comment]
> @OnceNever 贴出dns配置(运行时配置)

![image](https://github.com/user-attachments/assets/8bbdb8b2-e115-4800-a57e-4feec6caaa48)

**Comment by xishang0128** [comment]
@OnceNever 自行修改配置,覆盖dns没打开我们不管

**Comment by OnceNever** [comment]
@xishang0128 好的，我再排查一下，谢谢

**Comment by PctAIGM** [comment]
[nameserver-policy](https://wiki.metacubex.one/config/dns/#nameserver-policy)

nameserver-policy:
  "xxxx": system

如果是内部域名一般要用内网的dns解析吧

**Comment by OnceNever** [comment]
> [nameserver-policy](https://wiki.metacubex.one/config/dns/#nameserver-policy)
> 
> nameserver-policy: "xxxx": system
> 
> 如果是内部域名一般要用内网的dns解析吧

不是内部域名呢

**Comment by maoxiaomo** [comment]
遇到同样的问题，但是我遇到的是内网域名。

问题描述：
   xxxx.com为内网域名，在内网无法完成访问。

初步排查：
  通过覆写规则，添加 DOMAIN-SUFFIX,xxxx.com,DIRECT进行直通，不生效。
  通过客户端clash-verge V2.2.2,DNS设置均为初始参数，添加放行规则，生效，在内网xxxx.com域名可正常访问。

继续排查：
  经过查看Mihomo Party v1.7.2 日志发现域名无法解析。
ITCP] dial DlRECT (match Domainsufix/xxxx.com) 127.0.0.1:9835 --> xxxx.com:443 error: dnsresolve failed: couldn't find ip
在DNS设置中--->默认解析服务器--->添加内网DNS服务器后，在内网xxxx.com域名可正常访问。

附：clash-verge V2.2.2DNS初始参数。

![Image](https://github.com/user-attachments/assets/66e0d8e6-c766-4852-8417-5e323eecc336)


建议：希望作者可以优化此功能。
