### ISSUE TITLE
[Feature] 增加节点的排列方式

### ISSUE THREAD

**Issue by nv100** [pompurin404/mihomo-party#17]
### Verify steps

- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 我已在标题简短的描述了我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS, Windows, Linux

### 描述

希望能够增加节点的排列方式，目前只有竖向排列的列表方式，如果提供类似cfw,clash verge,flclash类似的横向节点显示排列方式，将方便电脑用户更好的利用大屏。

**Comment by ghost** [comment]
不打算做
