### ISSUE TITLE
[Feature] dns开关关闭的情况下，无法打开网页

### ISSUE THREAD

**Issue by 1xiaocainiao** [pompurin404/mihomo-party#170]
### Verify steps

- [ ] 我已在标题简短的描述了我所需的功能
- [ ] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [ ] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

dns开关关闭的情况下，无法打开网页，必须打开dns并且重启客户端才有网

**Comment by xishang0128** [comment]
@1xiaocainiao 说明你的系统dns不是很可用,打开即可,这不是bug

另外标题是功能请求,这是错误的
