### ISSUE TITLE
[Feature] Windows版本的右键复制环境变量显示多个，例如Linux/Windows，方便快速使用环境变量

### ISSUE THREAD

**Issue by opengit** [pompurin404/mihomo-party#171]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

如下图所示，在Windows下工作时，有时会远程桌面或者SSH到Linux系统，或者WSL下进行工作，希望添加Linux/Windows多个系统终端的复制环境变量，目前隐藏在设置界面中，还需要打开界面进入设置，选择终端后，再点击复制才能使用，有点不方便。谢谢。
![image](https://github.com/user-attachments/assets/a20714ad-ec3c-4077-aaf0-89f18c552551)
![image](https://github.com/user-attachments/assets/3786847f-eeed-4e70-99ce-5dae831f9aec)

**Comment by ghost** [comment]
可以多选了

**Comment by opengit** [comment]
@pompurin404 最新版，右键图标还是只有一种呀？
![image](https://github.com/user-attachments/assets/62eb81fd-42b8-42b6-8c76-7cc0fbee183b)

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/63f61ab5-36e1-4e0f-b770-132c46b3d0c8)

**Comment by opengit** [comment]
作者V587!!
