### ISSUE TITLE
[Bug] mac os 15 打开应用设置，cpu占用异常高

### ISSUE THREAD

**Issue by 1xiaocainiao** [pompurin404/mihomo-party#173]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

mac os 15

### 发生问题 mihomo-party 版本

1.22.2

### 描述

mac os 15 打开应用设置，cpu占用异常高

### 重现方式

打开应用设置就会出现 
![QQ_1726823224579](https://github.com/user-attachments/assets/55b519fe-76b3-469d-a5c5-5f8200221200)

**Comment by ghost** [comment]
修了
