### ISSUE TITLE
[Feature]  网络防火墙已经设置允许，为什么每次打开还进行提示。

### ISSUE THREAD

**Issue by wdkGitHub** [pompurin404/mihomo-party#174]
### Verify steps

- [ ] 我已在标题简短的描述了我所需的功能
- [ ] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [ ] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

<img width="296" alt="image" src="https://github.com/user-attachments/assets/8b3a3d57-7e17-4e91-a43b-68a4fc855eb1">

每次打开都有提示，防火墙已经允许也提示。系统版本 macOs Sonoma 14.6.1

**Comment by xishang0128** [comment]
这看起来不像一个功能请求

**Comment by wdkGitHub** [comment]
> 这看起来不像一个功能请求

是系统设置问题还是app的问题

**Comment by ghost** [comment]
@wdkGitHub 设置问题吧，其他人好像没听说有这问题

**Comment by Arionbat** [comment]
我也碰到了，也在防火墙里设置了允许，但是还是每次打开 Mihomo Party 的时候，会弹出 这个界面
操作系统版本： macos 13.6.9
Mihomo Party 版本：1.4.9
intel 芯片

**Comment by Arionbat** [comment]
```bash
sudo codesign --force --deep --sign - /Applications/Mihomo\ Party.app
sudo codesign --force --deep --sign - /Applications/Mihomo\ Party.app/Contents/Frameworks/Mihomo\ Party\ Helper\ \(Renderer\).app
```
执行这两条命令会解决这个问题
[How to get rid of firewall "accept incoming connections" dialog?](https://apple.stackexchange.com/questions/3271/how-to-get-rid-of-firewall-accept-incoming-connections-dialog)

**Comment by wdkGitHub** [comment]
我把Mihomo从网络防火墙中删除，后来就不提示了
