### ISSUE TITLE
[Feature] 便捷版可以升级完自动解压吗

### ISSUE THREAD

**Issue by realcirno** [pompurin404/mihomo-party#176]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

使用便捷版左上角出现小红点，点击更新之后应用自动退出了，在data目录找到了安装包，可以增加自动解压启动功能吗？

**Comment by realcirno** [comment]
如果实现起来比较困难的话就算了

**Comment by ghost** [comment]
自动解压了，等弹出的命令行窗口消失了就是解压完成了，自己打开就行

**Comment by realcirno** [comment]
好的，我试一试

**Comment by nameizzz** [comment]
> 自动解压了，等弹出的命令行窗口消失了就是解压完成了，自己打开就行
- 点左上角小红点（便携版当前版本是1.3.1，小红点显示新版本1.3.2）
- 弹出的新版本信息中，点右下方的更新按钮失败，提示502
- 错误信息如图：
![image](https://github.com/user-attachments/assets/1fa55236-0b74-4281-b695-5064da407037)

> 更新之前，当前环境已正常开启`v2rayN`，可以正常`google`等

**Comment by realcirno** [comment]
我今天早上更新的，没有这个问题，不过更新下载完直接自动退了，但是没有解压，打开后还是1.31，还是老老实实手动吧

**Comment by nameizzz** [comment]
> 我今天早上更新的，没有这个问题，不过更新下载完直接自动退了，但是没有解压，打开后还是1.31，还是老老实实手动吧

佬哥请教下，手动解压的话，是把旧版本下的`/data`搞到新版本的目录去，还是把新版本解压到旧版本目录覆盖同名文件？

**Comment by realcirno** [comment]
用便捷版本，直接删了除了data以外的文件，然后直接解压启动就可以了

**Comment by nameizzz** [comment]
好的，感谢
