### ISSUE TITLE
[Bug] macOS 15 开机自启动

### ISSUE THREAD

**Issue by leohooho** [pompurin404/mihomo-party#177]
### Verify steps

- [ ] 我已在标题简短的描述了我所遇到的问题
- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

版本15.0 (24A335)

### 发生问题 mihomo-party 版本

1.3.1

### 描述

Command failed: osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/mihomo-party.app", hidden:false}'
36:128: execution error: 未获得授权将Apple事件发送给System Events。 (-1743)

### 重现方式

<img width="912" alt="image" src="https://github.com/user-attachments/assets/81b7bc77-e203-4a76-98cf-89d78fb3c5d1">

**Comment by ghost** [comment]
看起来是应用内升级导致的，使用dmg安装可以解决，我再看看怎么修吧

**Comment by leohooho** [comment]
> 看起来是应用内升级导致的，使用dmg安装可以解决，我再看看怎么修吧

覆盖安装已解决 感谢大佬

**Comment by moekyo** [comment]
已经尝试按照上面的issue，重新下载dmg安装，仍无法解决，我的系统是macOS 15，mihomo是1.4.1
在设置开启开机自启，提示
<img width="257" alt="image" src="https://github.com/user-attachments/assets/968e2e6a-b222-4272-a4be-63c95db84c16">

**Comment by Storm-Starlight** [comment]
> 已经尝试按照上面的issue，重新下载dmg安装，仍无法解决，我的系统是macOS 15，mihomo是1.4.1 在设置开启开机自启，提示 <img alt="image" width="257" src="https://private-user-images.githubusercontent.com/12700243/373550089-968e2e6a-b222-4272-a4be-63c95db84c16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMjk2OTYsIm5iZiI6MTcyODAyOTM5NiwicGF0aCI6Ii8xMjcwMDI0My8zNzM1NTAwODktOTY4ZTJlNmEtYjIyMi00MjcyLWE0YmUtNjNjOTVkYjg0YzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDA4MDk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlYTFmNjlhN2RlMWQ1YWQ1NTllYmY3ODdiM2FhNmNmZjVhZjY3NWJkNWQ0NTIwN2MwMzRhOWEwNDU2MmQ3ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XzDcNm-Gg4-4pln_o5hTMc5jvi8hdjDDdV3siK4XHlc">

卸载干净后重装

**Comment by moekyo** [comment]
尝试了用appcleaner删除并且也删除了application support下的对应的文件夹，重新安装后还是报同样的错

**Comment by ghost** [comment]
/Applications里面有没有旧的mihomo-party.app

**Comment by moekyo** [comment]
之前安装改名版本的时候已经把这个旧的删了，我记得我在安装新版之后，是有个弹窗要什么权限之类（具体权限不太记得了），但是我没有给，后面开启开机自启就报错了，这两个有关系吗？
