### ISSUE TITLE
[Bug] 便携版新版本重新手动解压后无法打开

### ISSUE THREAD

**Issue by nameizzz** [pompurin404/mihomo-party#178]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win10 22H2

### 发生问题 mihomo-party 版本

1.3.1

### 描述

手动删除历史版本目录，重新解压新版本目录，启动失败，提示信息中的`exe`全路径为已删除的历史版本路径

> 历史版本、新版本目录信息：
![image](https://github.com/user-attachments/assets/28cbb9cf-2362-4bf7-946b-ba5d6c63870c)

### 重现方式

- 历史版本为`1.2.0`，解压路径为`D:\science\mihomo-party-windows-1.2.10-x64-portable`
- 新下载版本`1.3.1`，解压路径为`D:\science\mihomo-party-windows-1.3.1-x64-portable`
- 删除旧版本目录
- 在新版本目录中启动，失败
- 错误信息如下：
![image](https://github.com/user-attachments/assets/a0dfac53-6fd4-41a4-8545-1ed49e694730)

**Comment by ghost** [comment]
管理员权限运行即可

**Comment by nameizzz** [comment]
感谢
