### ISSUE TITLE
[Bug] 无法启动，sysproxy.win32-x64-msvc.node not found

### ISSUE THREAD

**Issue by TheresaQWQ** [pompurin404/mihomo-party#179]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Win11

### 发生问题 mihomo-party 版本

1.3.0+

### 描述

![image](https://github.com/user-attachments/assets/e478995c-d434-4438-b93c-274e598fcb22)

### 重现方式

下载 `mihomo-party-windows-1.3.0-x64-portable.7z`，解压，启动

**Comment by TheresaQWQ** [comment]
![image](https://github.com/user-attachments/assets/3efda568-7fb7-44dd-b100-1b8a94411495)
刚刚下载的1.2.22也一样的

**Comment by ghost** [comment]
检查 resources/app.asar.unpacked/node_modules/@mihomo-party/sysproxy-win32-x64-msvc 目录下的内容，检查杀毒软件日志

**Comment by TheresaQWQ** [comment]
确认了，是elastic endpoint干的，打扰了，抱歉
