### ISSUE TITLE
[Feature] 关闭窗口，就无法打开窗口了，只能完全退出，重启，希望支持窗口再打开

### ISSUE THREAD

**Issue by psychopasss** [pompurin404/mihomo-party#18]
### Verify steps

- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 我已在标题简短的描述了我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

关闭窗口，就无法打开窗口了，只能完全退出，重启，希望支持窗口再打开

**Comment by ghost** [comment]
托盘图标打不开吗

**Comment by psychopasss** [comment]
> 托盘图标打不开吗

打不开窗口。

**Comment by ghost** [comment]
是最新版吗

**Comment by psychopasss** [comment]
> 是最新版吗

0.5.2

**Comment by aLIEz-xue** [comment]
> 托盘图标打不开吗

遇到同样的情况，只能重启电脑

**Comment by aLIEz-xue** [comment]
> > 托盘图标打不开吗
> 
> 遇到同样的情况，只能重启电脑

现在重启电脑也解决不了了，完全不显示软件界面

**Comment by psychopasss** [comment]
macOS系统没有托盘，点击dock也不能显示界面。

**Comment by aLIEz-xue** [comment]
> > > 托盘图标打不开吗
> > 
> > 
> > 遇到同样的情况，只能重启电脑
> 
> 现在重启电脑也解决不了了，完全不显示软件界面

开机不显示可能是静默启动的原因，那么如果设置了静默启动，就完全无解了，只能卸载重装

**Comment by ghost** [comment]
https://github.com/pompurin404/mihomo-party/actions/runs/10386315027

试试这个，是否修复

**Comment by ghost** [comment]
0.5.3 应该修好了
