### ISSUE TITLE
[Bug] windows系统中Sub-Store 中的订阅可以显示，但是点击订阅查询不到任何节点，甚至出现“Failed to preview subscription type: InternalServerError Reason: ”错误

### ISSUE THREAD

**Issue by Nosliver** [pompurin404/mihomo-party#181]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [x] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

windows10系统

### 发生问题 mihomo-party 版本

一直以来都存在这个问题，我以为会修复

### 描述

 windows系统中Sub-Store 中的订阅可以显示，但是即时预览后查询不到任何节点，甚至出现“Failed to preview subscription type: InternalServerError Reason: ”错误，在浏览器中打开也会显示和软件中相同错误类型。

### 重现方式

点击即时预览，会显示无任何节点以及错误

**Comment by ghost** [comment]
给Sub-Store反馈
