### ISSUE TITLE
[Bug] 代理组 GIF 图标只会在第一次加载后正常播放，后续查看不播放

### ISSUE THREAD

**Issue by NuoFang6** [pompurin404/mihomo-party#183]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows11 23H2 22635.4225

### 发生问题 mihomo-party 版本

v1.3.2

### 描述

```
proxy-groups:
  - icon:  如果这里使用了GIF图片
```
当 GUI 第一次加载图标后是正常播放 GIF 图片的，但之后再次读取时不会播放。

![演示](https://github.com/user-attachments/assets/5e507d58-a374-40b3-b711-e2897ae2c132)

### 重现方式

```
proxy-groups:
  - icon: 在这里使用 GIF 图片
```

**Comment by NuoFang6** [comment]
程序似乎错误的使用了png格式：
![image](https://github.com/user-attachments/assets/8417f302-900d-470e-8c0c-c32def935528)

**Comment by xishang0128** [comment]
@NuoFang6 party从未说过支持gif,目前仅支持静态图片格式

**Comment by ghost** [comment]
处理了一下，试试这个

https://github.com/mihomo-party-org/mihomo-party/actions/runs/11013569531

记得把应用目录下的 Local Storage 删了

**Comment by NuoFang6** [comment]
https://github.com/mihomo-party-org/mihomo-party/commit/b6559cbaf9839e5c92383aab760fe5b34becca92
已修复 👍
