### ISSUE TITLE
[Bug] 自带内核在安装过程中权限错误导致无法授权内核启动tun

### ISSUE THREAD

**Issue by artefaritaKuniklo** [pompurin404/mihomo-party#184]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Linux

### 系统版本

Linux 6.3.0-kali1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.3.7-1kali1 (2023-06-29) x86_64 GNU/Linux

### 发生问题 mihomo-party 版本

v1.3.2

### 描述

由于`no_new_privilege` flag的存在，当在`～/Download`等`_apt`无写入权限的目录安装时，因`sudo`无法完成container内的提权导致tun启动失败

建议加入doc-常见问题

![3](https://github.com/user-attachments/assets/b4d96005-9142-4ae0-a702-fa1188fed331)

### 重现方式

^

**Comment by ghost** [comment]
应该是点击过重启应用导致的，正常启动是没有问题的，可以安装这一版看看有没有修复

https://github.com/mihomo-party-org/mihomo-party/actions/runs/11017581054

**Comment by artefaritaKuniklo** [comment]
> 应该是点击过重启应用导致的，正常启动是没有问题的，可以安装这一版看看有没有修复
> 
> https://github.com/mihomo-party-org/mihomo-party/actions/runs/11017581054

貌似没问题
