### ISSUE TITLE
[Question] TUN模式下连接公司的VPN后访问公司域名的服务不通, 不知道怎么配置

### ISSUE THREAD

**Issue by lixxu** [pompurin404/mihomo-party#185]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11

### 发生问题 mihomo-party 版本

1.3.2

### 描述

开启TUN模式后, 在连接公司的VPN后, 访问公司域名的服务不通.
比如, 公司域名服务为: external.abc123.com(假设IP是公司内网地址10.28.10.10)
直接用域名是不通的, 用IP就没问题, DNS里做了host映射也没问题(其实相当于用IP访问了).
这个应该不是bug, 但我不知道怎么设置, 请指点.
关闭TUN模式就正常了.

### 重现方式

开启TUN, 使用域名访问

**Comment by xishang0128** [comment]
不遵守模版,目前只接受错误反馈和功能请求,讨论请前往tg群组
