### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ghost** [pompurin404/mihomo-party#186]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

23H2 Windows 11 专业版

### 发生问题 mihomo-party 版本

v 1.3.3

### 描述

外部资源，也就是在线规则集，更新的逻辑
在规则模式更新很慢，猜测走了节点
在全局直连，和直接选择直连模式下，秒更新
本次测试的在线规则集是国内cdn，猜测和走节点有关
希望增加更新是否走节点的开关

### 重现方式

选取一个国内cdn的在线规则集（外部资源）
在不同模式更新，会得到完美的复现

**Comment by xishang0128** [comment]
外部资源由内核管理,查看内核文档

**Comment by AnyWAT** [comment]
> 外部资源由内核管理
> 在全局直连，和直接选择直连模式下，秒更新

点击更新，秒出系统通知：Geo 数据库更新成功
然而检查各文件，均还是随安装文件版本，妥妥的虚假通知。既然不能更新，程序内还设置自动更新开关及更新间隔。。。无语了

**Comment by xishang0128** [comment]
@AnyWAT 了解一下什么是etag吧

**Comment by KdeInit** [comment]
> V1.5.12便携版点击更新，秒出系统通知：Geo 数据库更新成功 然而检查各文件，均还是随安装文件版本，妥妥的虚假通知。既然不能更新，程序内还设置自动更新开关及更新间隔。。。无语了，还有如下错误？ GeoIP 数据库：...download/latest/geoip-lite.dat（程序内只有 geoip.dat） ASN 数据库：...download/latest/GeoLite2-ASN.mmdb（程序内只有 ASN.mmdb）

你似乎很喜欢在别人的 issues 下面回复，然后暴露自己的智商呢

**Comment by AnyWAT** [comment]
码盲一个。。。

**Comment by AnyWAT** [comment]
> 在 https://github.com/MetaCubeX/meta-rules-dat/releases 手动更新了程序内的
> geoip.metadb
> geosite.dat
> country-lite.mmdb 更名为 country.mmdb
> geoip-lite.dat 更名为 geoip.dat
> GeoLite2-ASN.mmdb 更名为 ASN.mmdb

日更此5文件，批处理自动Curl 下载到 test，再手动复制到 work，极度舒适ing。。。

**Comment by AnyWAT** [comment]
@gsxgmpkt9020 https://github.com/MetaCubeX/meta-rules-dat/releases 上一楼日更的5文件，自动更新或手动更新了吗？

**Comment by AnyWAT** [comment]
@startle09 @Hayxi https://github.com/clash-verge-rev/clash-verge-rev/issues/2985
test 文件夹下的3个文件，貌似网络测试用的，不会自动更新，随程序版本 resources 文件夹中的同名文件更新而更新？或停留在首次运行时从 resources 自动复制而来；
上级目录中的同名文件，貌似程序工作用的，正如Mihomo Party 放在 work 文件夹中，也不会自动更新，随程序版本 resources 文件夹中的同名文件更新而更新，但可以手动更新：
设置—Clash 设置—更新 GeoData，只能更新3个中的2个文件，Country.mmdb 却被更新成了geoip.metadb 的大小。刚刚测试，已是假更新：弹窗提示已更新，但实际并未更新。
官网 https://github.com/MetaCubeX/meta-rules-dat/releases 在每天的6:30稍后是定时更新的，敝人现在手动日更3文件 curl 自动下载到test再手动复制到上一级目录。

**Comment by AnyWAT** [comment]
@MingcongBai https://github.com/clash-verge-rev/clash-verge-rev/issues/3006
？https://github.com/mihomo-party-org/mihomo-party/issues/186#issuecomment-2727161709

**Comment by MingcongBai** [comment]
> [@MingcongBai](https://github.com/MingcongBai) [clash-verge-rev/clash-verge-rev#3006](https://github.com/clash-verge-rev/clash-verge-rev/issues/3006) ？[#186 (comment)](https://github.com/mihomo-party-org/mihomo-party/issues/186#issuecomment-2727161709)

我没明白，#3006 报告的是代码逻辑问题，您这个答复是希望提醒我什么呢？

**Comment by AnyWAT** [comment]
无 GeoIP 数据，手动处理。。。

**Comment by MingcongBai** [comment]
> 无 GeoIP 数据，手动处理、下载3文件？

如 #3006 所说，Clash 在这个条件下对主程序启动的逻辑处理是有问题的

**Comment by AnyWAT** [comment]
@earthjasonlin https://github.com/clash-verge-rev/clash-verge-rev/issues/3070
WIN10为毛要使用 fixed webview 版本？有 webview [安装器，左一下载](https://developer.microsoft.com/en-us/microsoft-edge/webview2) 手动安装或更新

**Comment by AnyWAT** [comment]
@wakakki @Remik1r3n @Tunglies @wonfen @Tychristine @MingcongBai
比较程序更新包自带、手动下载替换、程序内手动更新3文件的不同：
1、Clash.Verge_2.2.3-alpha_x64-setup.exe Created at Tue Apr 1 06:05:52 CST 2025. 使用7-Zip 解压的结果
![Image](https://github.com/user-attachments/assets/b79a37e9-c972-4172-8ddb-91d8df489832)
2、手动在官网 https://github.com/MetaCubeX/meta-rules-dat/releases Curl 自动下载到 test 再手动复制到上一级目录
![Image](https://github.com/user-attachments/assets/371416fb-c707-4349-adda-38ca3a1971c7)
3、启动 clash-verge.exe 在设置—Clash 设置—更新 GeoData 后的结果，country.mmdb 被更新成了 geoip.metadb 文件的大小，此后程序仍旧正常，嘿嘿嘿
![Image](https://github.com/user-attachments/assets/d919e139-8d5f-409b-abd1-38a682a588cd)
参考Mihomo Party 下手动更新的 geoip.metadb 文件的大小
![Image](https://github.com/user-attachments/assets/ded8f0db-9a44-4a10-b002-cc523b6f395c)

**Comment by AnyWAT** [comment]
官网 https://github.com/MetaCubeX/meta-rules-dat/releases 今天下午多更新了一次，发生了什么？

![Image](https://github.com/user-attachments/assets/8bccb0a5-4f6c-400d-ae78-e207837f3ddc)

**Comment by AnyWAT** [comment]
Created at Fri Apr 4 13:51:11 CST 2025. https://github.com/clash-verge-rev/clash-verge-rev/issues/3244 
行动起来？clash-verge-rev 已废弃不能自动更新的 test 目录，其功能由 resources 内与原 test 同名文件替代，即 resources 内3文件做 test 的事。

**Comment by AnyWAT** [comment]
@ly6610111gmail6 @Voisterouslife https://github.com/mihomo-party-org/mihomo-party/issues/667#issuecomment-2799851125
外部资源自动更新、程序内手动更新均无效，手动日更 test 与 work 目录内同名文件：https://github.com/mihomo-party-org/mihomo-party/issues/186#issuecomment-2655780899
