### ISSUE TITLE
[Feature] 能否记录下不同订阅下，global选择的节点

### ISSUE THREAD

**Issue by fresh-men** [pompurin404/mihomo-party#187]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

能否记录下不同订阅下，global选择的节点。
现在切换订阅，然后选择global或者同名的代理组，就会导致其他选的订阅回到direct，很不方便，不知道能不能加这个功能。

**Comment by xishang0128** [comment]
不能,这是内核记录的,记录值没了自然切了
