### ISSUE TITLE
[Bug] 和 zerotier 同时使用有冲突

### ISSUE THREAD

**Issue by meilonme** [pompurin404/mihomo-party#188]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

windows 11

### 发生问题 mihomo-party 版本

1.3.3

### 描述

通过zerotier连接到家里的NAS, mihomo使用tun模式, 两个都启动后, 无法访问 nas ip;
mihomo关闭后能够正常访问 nas; 

### 重现方式

启动 zerotier 并连接;
启动 mihomo 并开启 tun 模式;
尝试连接nas失败;

**Comment by xishang0128** [comment]
https://wiki.metacubex.one/config/inbound/tun/#route-exclude-address
or
https://wiki.metacubex.one/config/proxies/direct/

多看文档

**Comment by meilonme** [comment]
```
+proxies:
  - name: zerotier
    type: direct
    udp: true
    ip-version: ipv4
    interface-name: ZeroTier One [xxxxxxxxx]
+rules:
  - IP-CIDR,10.147.18.0/24,zerotier,no-resolve
```

加了覆写配置, 但是并没有效果
