### ISSUE TITLE
[Bug] 重启软件之后，模块布局会丢失

### ISSUE THREAD

**Issue by psychopasss** [pompurin404/mihomo-party#19]
### Verify steps

- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

macOS 14.5

### 发生问题 mihomo-party 版本

0.52

### 描述

重启软件之后，模块布局会丢失

### 重现方式

重启软件

**Comment by ghost** [comment]
确实，我排查一下

**Comment by ghost** [comment]
修了 https://github.com/pompurin404/mihomo-party/actions/runs/10385205117
