### ISSUE TITLE
[Bug] 虚拟网卡打开,触发自动更新订阅时,断网

### ISSUE THREAD

**Issue by mContext** [pompurin404/mihomo-party#191]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 10 专业版 22H2

### 发生问题 mihomo-party 版本

v1.3.4

### 描述

网虚拟网卡打开,触发自动更新订阅时,出现较长时间网络中断, 导致游戏掉线
比手动更新订阅断网时间明显长很多

### 重现方式

保持虚拟网卡打开, 设置订阅自动更新为5分钟
触发订阅更新时,就会掉线
[2024-9-26 - 副本.log](https://github.com/user-attachments/files/17142381/2024-9-26.-.log)

**Comment by xishang0128** [comment]
预期行为,更新订阅完成后需要重启内核以重载配置

虚拟网卡启动可能快也可能慢,这就是windows

**Comment by mContext** [comment]
好吧  那只能把自动更新订阅关掉玩游戏了~
