### ISSUE TITLE
[Feature] 只在使用tun模式时以管理员权限运行

### ISSUE THREAD

**Issue by Carlos920** [pompurin404/mihomo-party#192]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

电脑域策略无管理员权限，#63 中说到要保证tun可用，但若无需使用tun模式，是否可以默认普通用户权限启动，只有有需要使用tun的使用管理员权限启动。

**Comment by ghost** [comment]
添加了noadmin参数可以直接启动，但不会做相关适配，程序内设置开机启动也是需要管理员权限的，如果要使用只能自己手动设置了
