### ISSUE TITLE
[Bug] 滚轮滚动时，GUI界面整体闪烁

### ISSUE THREAD

**Issue by Nomamuk** [pompurin404/mihomo-party#193]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

22631.4249

### 发生问题 mihomo-party 版本

1.3.4

### 描述

更新22631.4249后，在界面使用滚轮进行滚动时，整个界面出现闪烁

### 重现方式

使用滚轮进行滚动

**Comment by xixu-me** [comment]
@Nomamuk 那就用 CVR 嘛

**Comment by xishang0128** [comment]
无法复现,请提供明确的复现条件,并附加视频

**Comment by Nomamuk** [comment]
https://github.com/user-attachments/assets/cc0496b9-0125-4898-900b-d5a9e24bf5fd

不需要滚动，只需要鼠标移动就会出现闪烁等gui异常

**Comment by Moecg** [comment]
+1
一直会出现

https://github.com/user-attachments/assets/87c910fe-6978-4eb6-abda-191d59162a6f

**Comment by Asteroiddust** [comment]
一样的问题，在设置中开启“使用系统标题栏”后无闪烁，关闭后闪烁消失

**Comment by Nomamuk** [comment]
更新24H2出现了一个其他问题，Alt+Tab切屏可能导致游戏冻屏。重装Nvidia驱动后，测试551.86及之前的版本都能同时解决两个问题。
