### ISSUE TITLE
[Feature] 点击组代理自动展开且定位到当前节点

### ISSUE THREAD

**Issue by Jinx233333** [pompurin404/mihomo-party#195]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [ ] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [ ] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

每次点击代理组都是默认折叠的，想要查看当前节点比较麻烦（先展开节点，再定位节点），希望默认是定位到当前节点。

**Comment by ghost** [comment]
不做
