### ISSUE TITLE
[Feature] 建议托盘菜单显示节点信息配置项增加子菜单选项，否则托盘菜单可能会很长

### ISSUE THREAD

**Issue by guorenjie** [pompurin404/mihomo-party#197]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

<img width="862" alt="image" src="https://github.com/user-attachments/assets/6cacca6b-f6d2-46c7-bc85-d55d1da9397c">

**Comment by gholts** [comment]
可以选择关闭节点信息
![image](https://github.com/user-attachments/assets/de37a7b8-d89a-4f42-8748-f8ff17a2b069)
