### ISSUE TITLE
[Feature] 自定义托盘图标

### ISSUE THREAD

**Issue by ZeonXr** [pompurin404/mihomo-party#198]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

![image](https://github.com/user-attachments/assets/8cf07aef-e149-4cf1-ab47-eeeaf44035fd)
能否增加自定义托盘图标的功能，CFW和verge都有此功能。我平时代理都常驻后台图标放任务栏上，统一用Windows风格的图标能更好看一点

**Comment by ghost** [comment]
不做
