### ISSUE TITLE
[Bug] 任务栏显示网速无法取消掉“上传”

### ISSUE THREAD

**Issue by Zxis233** [pompurin404/mihomo-party#199]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows11 Education

### 发生问题 mihomo-party 版本

1.4.0

### 描述

任务栏开启“显示网速流量”后，自定义显示项目保存后无法取消勾选“上传”
![GIF 2024-10-1 18-00-51](https://github.com/user-attachments/assets/d93aa1aa-31eb-40b8-b3c9-b837b5dc3778)

### 重现方式

1. 右键任务栏网速-选项
2. 任务栏窗口设置-显示设置
3. 勾选上传，确定
4. 应用
5. 取消勾选上传，确定
6. 应用

**Comment by xishang0128** [comment]
TrafficMonitor就是这样子的,得保留一个选项

mihomo-party的流量显示只是作为插件存在

**Comment by ghost** [comment]
把TrafficMonitor的配置文件删了可以恢复初始状态

**Comment by Zxis233** [comment]
请问配置文件在哪里呢

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/af3df26f-3ac5-4981-9dd6-32310c4dd8f1)

**Comment by Zxis233** [comment]
> ![image](https://private-user-images.githubusercontent.com/176902387/372479039-af3df26f-3ac5-4981-9dd6-32310c4dd8f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODgzNzYsIm5iZiI6MTcyNzc4ODA3NiwicGF0aCI6Ii8xNzY5MDIzODcvMzcyNDc5MDM5LWFmM2RmMjZmLTNhYzUtNDk4MS05ZGQ2LTMyMzEwYzRkZDhmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxMzA3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzVjMWJhYWM1NzY5MWY0NjcxM2MzOGNhOTc5ZDM1NjdjZmZlMWQxNjMyZmQ0YjFhZWY3MzQ0NjIxMTVhNWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gV3dvg7ikYxYLuBYpcKoJBMnvJiWDZ7dflcMuYzUljQ)

感谢。

**Comment by Zxis233** [comment]
此外，调整“网速数据宽度”之后显示不生效，依旧会有网速数字被遮挡的情况。
![image](https://github.com/user-attachments/assets/144393c5-31f4-4287-a895-5c0dbde909f6)

**Comment by ghost** [comment]
那个选项调整的是TrafficMonitor自带的网速组件的宽度，mihomo party内置TrafficMonitor只是利用其插件在任务栏展示内核网速，理论上不提供任何自定义选项，我所提供的默认设置是可以正常显示完整的。
