### ISSUE TITLE
[Bug] 订阅永远502...开tun订阅都不行(网址没问题,已在其他浏览器/设备测试)

### ISSUE THREAD

**Issue by cancundeyingzi** [pompurin404/mihomo-party#20]
### Verify steps

- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

26100.1457

### 发生问题 mihomo-party 版本

052

### 描述

![image](https://github.com/user-attachments/assets/da74117b-d2e9-4967-8264-6026f0703aba)

### 重现方式

不论是手动填写地址订阅还是网站上拉起,都可以复现。

**Comment by ghost** [comment]
请求直接从内核走的，重启一下内核
