### ISSUE TITLE
[Feature] 建议在代理组显示。当前选择的节点

### ISSUE THREAD

**Issue by dududuK** [pompurin404/mihomo-party#202]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [ ] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [ ] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

![QQ截图20241001224908](https://github.com/user-attachments/assets/288dd7f2-3868-4046-a0e2-8a31341f02af)

**Comment by xishang0128** [comment]
已有

**Comment by KrisCris** [comment]
请问一下在哪里设置，我没找到

> 已有

**Comment by yangtb2024** [comment]
> 请问一下在哪里设置，我没找到
> 
> > 已有

![Image](https://github.com/user-attachments/assets/3c340981-2c09-4043-9ccc-c440fab307d1)
