### ISSUE TITLE
[Bug] 已经给了管理员权限但还是无法已管理模式启动

### ISSUE THREAD

**Issue by yyqEternal** [pompurin404/mihomo-party#204]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [x] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11 Version 23H2

### 发生问题 mihomo-party 版本

 1.2.23 和1.41

### 描述

绿色版便携版和正常安装版我都试过了全报错
![image](https://github.com/user-attachments/assets/b5ad516f-d720-4207-9042-ef4d5ace0ed5)
 昨天下载调试到十一点今天又调试还是不行，主要问题我问chatgpt 知道报错原因但我不会修使用cmd命令启动会提升缺少组件schtasks.exe「D:\MySoftware\mihomo-party>
'schtasks' 不是内部或外部命令，也不是可运行的程序
或批处理文件。」
询问chatgpt说我是环境变量有问题或者没有schtasks.exe这个软件 我重新检查环境变量 win系统 都是正常的，到这里我就无法解决了

### 重现方式

兼容性设置管理员启动 右键选择管理员启动

**Comment by ghost** [comment]
是正经系统吗

**Comment by yyqEternal** [comment]
哈哈哈哈正经系统，笔记本家庭版win11，msdn下的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月2日(周三) 下午5:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mihomo-party-org/mihomo-party] [Bug] 已经给了管理员权限但还是无法已管理模式启动 (Issue #204)




 
是正经系统吗

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/50c9f774-3e6d-40f0-bdd2-b561441cc391)
有这东西吗

**Comment by yyqEternal** [comment]
有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月2日(周三) 晚上7:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mihomo-party-org/mihomo-party] [Bug] 已经给了管理员权限但还是无法已管理模式启动 (Issue #204)




 
image.png (view on web)
 有这东西吗

**Comment by KleinerSource** [comment]
同样的问题  win11 24h2 专业版 msdn原版 无删减 也是管理员启动提示要管理员

**Comment by yyqEternal** [comment]
> 同样的问题 win11 24h2 专业版 msdn原版 无删减 也是管理员启动提示要管理员

你用clash verge 吧我一直在用，看到这个软件别人推荐说不错结果我自己打不开

**Comment by ghost** [comment]
https://github.com/mihomo-party-org/mihomo-party/actions/runs/11157111240

试试这个

**Comment by KleinerSource** [comment]
> > 同样的问题 win11 24h2 专业版 msdn原版 无删减 也是管理员启动提示要管理员
> 
> 你用clash verge 吧我一直在用，看到这个软件别人推荐说不错结果我自己打不开

我本来就是在用 cv 想换到 mihomo 试试

**Comment by KleinerSource** [comment]
> https://github.com/mihomo-party-org/mihomo-party/actions/runs/11157111240
> 
> 试试这个

这一版没问题了 但是无法勾选 开机自启动
看开还是和计划任务有关
![IMG_3999](https://github.com/user-attachments/assets/33197117-82a1-4edb-8d62-4de83895a67e)
![IMG_4001](https://github.com/user-attachments/assets/996ebdb7-873a-4fcf-87c8-48be716b27c7)
![IMG_4002](https://github.com/user-attachments/assets/5d74f2ad-a67e-4a72-9abd-0dc5a2d6222d)

**Comment by ghost** [comment]
报错的那条命令终端执行看看具体报错

**Comment by KleinerSource** [comment]
> 报错的那条命令终端执行看看具体报错
![image](https://github.com/user-attachments/assets/9d1c578e-7e65-4fc8-b927-841b897707de)

错误: 拒绝访问。

**Comment by ghost** [comment]
用管理员终端跑

**Comment by ghost** [comment]
诶不对，已经是管理员了，奇怪

**Comment by ghost** [comment]
方便的话tg联系我远程看看

**Comment by silver716** [comment]
电脑用了什么 EDR 或杀毒软件？

**Comment by yyqEternal** [comment]
作者把这个话题结束吧 我已经把重装系统家庭版换成专业版已经可以正常用
![image](https://github.com/user-attachments/assets/453ec14f-7ef7-4007-aa98-71de85903897)

**Comment by yyqEternal** [comment]
9

> 方便的话tg联系我远程看看

作者你好请问软件用什么语言写的我只会Javaweb 想为这个项目做贡献

**Comment by KleinerSource** [comment]
> 方便的话tg联系我远程看看

明白了 火绒拦截了 但是很奇怪 他都没记录日志 所以我之前没看出来  停掉就可以正常创建了

**Comment by ghost** [comment]
离谱

**Comment by sdgsgsdf** [comment]
360也是这样，似乎国内那几个都会这么干，拦截了但是也不说，还一直奇怪啥情况呢
