### ISSUE TITLE
[Bug] Linux无法在非Gnome系/KDE桌面环境外启动

### ISSUE THREAD

**Issue by ghost** [pompurin404/mihomo-party#205]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Linux

### 系统版本

NixOS, 24.11

### 发生问题 mihomo-party 版本

v1.4.1

### 描述

启动时发生'应用初始化失败: Error: no such file or directory (os error 2)',原因是mihomo-party-org/sysproxy-rs对于非KDE桌面环境默认使用Gnome的方式设置系统代理，对于一些小众桌面环境和窗口管理器（如Hyprland）应用将无法启动，希望能在上层捕获这个错误。

### 重现方式

在Linux上安装并使用Hyprland，启动应用

**Comment by yuzh496** [comment]
我这里linuxmint系统，使用的默认的Cinnamon 6.4.6 桌面，也无法启动，使用命令行启动，也没有任何提示。

系统信息：

             
![Image](https://github.com/user-attachments/assets/576b6675-a67e-4808-80ca-5b94a0d308ce)

**Comment by Tony15246** [comment]
发行版为archlinux，窗口管理器为hyprland，有同样问题。使用命令行启动，同样没有任何提示

![Image](https://github.com/user-attachments/assets/e2ed2122-7163-4493-aeda-790e093c8a15)

**Comment by wuliuqii** [comment]
请问这个问题解决了吗

**Comment by StevenArai** [comment]
Arch linux & hyprland, failed to start.

![Image](https://github.com/user-attachments/assets/aba5141b-f42c-47c9-906e-187f2f66fdc6)
