### ISSUE TITLE
[Bug] 当节点较多时ping无法一次性显示全部结果

### ISSUE THREAD

**Issue by nv100** [pompurin404/mihomo-party#21]
### Verify steps

- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11 23H2

### 发生问题 mihomo-party 版本

0.5.2

### 描述

当一个订阅的节点较多时，一次ping无法显示所有节点的结果，需要2次ping才能显示全部结果。

### 重现方式

https://github.com/user-attachments/assets/6850eafb-7207-4fa5-8db2-bb345a28119d

**Comment by ghost** [comment]
group测的慢，就这样，虚拟列表只加载了显示出来的节点，其他节点是跟随group一起测的延迟，所以没有动画，等groupdelay全部测完之后再去看就有延迟了
