### ISSUE TITLE
[Feature] 轻量模式下可否保留任务栏小图标？

### ISSUE THREAD

**Issue by hlyyzz** [pompurin404/mihomo-party#214]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

RT 太轻量了 每次想换个节点还得重新从桌面点开软件

**Comment by xishang0128** [comment]
那就别开轻量,electron必须保留一些进程,和你直接关闭窗口不开轻量是一样的

**Comment by AnyWAT** [comment]
进入轻量模式运行后，在系统任务管理器内都看不出是哪些个进程属于本应用。如需要关闭它，得重新启动后再退出才行。
请问，轻量模式下的进程是哪些？

**Comment by AnyWAT** [comment]
> 请问，轻量模式下的进程是哪些？

真科技实狠活：参照 https://github.com/clash-verge-rev/clash-verge-rev/issues/2362 的 netstat -ano | findstr "应用使用端口"
能找到使用对应端口进程的PID，但任务管理器内并没有该PID对应的进程，厉害了。
