### ISSUE TITLE
[Feature] Support vmess protocol

### ISSUE THREAD

**Issue by hsbtr** [pompurin404/mihomo-party#216]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [ ] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

The import of individual vmess protocol nodes failed

**Comment by xishang0128** [comment]
软件支持vmess,请转为mihomo配置格式并导入

**Comment by hsbtr** [comment]
> 软件支持vmess,请转为mihomo配置格式并导入

是否可以给一个参考模板呢？第一次用这个不是很熟悉该怎么配置
