### ISSUE TITLE
[Feature] 希望WebDav备份不自动创建mihomo-party文件夹，增加本地备份

### ISSUE THREAD

**Issue by pigeon-coo** [pompurin404/mihomo-party#217]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

![图片](https://github.com/user-attachments/assets/bdff23ed-3c1d-4daf-b522-1884aba42f6c)
如图，设置项上传到WebDav保存的时候，会自动创建一层“mihomo-party”文件夹，希望可以直接放到选定的目录，不提及mihomo-party字样。
另外如果可以的话，设置项增加导出到本地/从本地导入。
非常感谢！

**Comment by ococl** [comment]
支持！
