### ISSUE TITLE
[Feature] 建议订阅界面增加"最近更新时间"

### ISSUE THREAD

**Issue by wdy3334** [pompurin404/mihomo-party#218]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

如果订阅界面有的话，很直观一看就知道，我该更新一下了，现在基本上就是用着用着不能用了，鼠标悬停一看，好几天没更新，再去更新（电脑不是每天开机，自动更新这玩意好用，但是耐不住有的订阅时不时的需要代理），这个时候有个【最近更新时间】就很直观了

**Comment by xishang0128** [comment]
![image](https://github.com/user-attachments/assets/2c9fc9b7-4c84-48cf-b4fb-a7f1af70f11f)
点击切换
