### ISSUE TITLE
[Bug] mac M3 app改名后，无法静默更新，会弹出磁盘，需要自己拖动

### ISSUE THREAD

**Issue by 1xiaocainiao** [pompurin404/mihomo-party#219]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

15.0.1

### 发生问题 mihomo-party 版本

1.4.4

### 描述

mac M3 app改名后，无法静默更新，会弹出磁盘，需要自己拖动

### 重现方式

点击更新弹窗即可

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/7c7578d4-31a0-4ee6-9136-1ef9784903a5)

**Comment by 1xiaocainiao** [comment]
刚试了，用appcleaner卸载，重新安装1.4.3，点击左上角1.4.4版本更新，还是会弹出磁盘，

**Comment by ghost** [comment]
https://github.com/mihomo-party-org/mihomo-party/actions/runs/11237075033

安装这个更新试试，版本号为1.4.3

**Comment by 1xiaocainiao** [comment]
可以了
