### ISSUE TITLE
[Feature] 是否可以增加忽略指定域名功能

### ISSUE THREAD

**Issue by 1xiaocainiao** [pompurin404/mihomo-party#220]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [ ] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [ ] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

有时候内网访问需要忽略指定ip的域名，没有这个功能，每次都只能关掉代理，希望有这个功能

**Comment by xishang0128** [comment]
@1xiaocainiao 点击系统代理卡片,罚你重看引导
