### ISSUE TITLE
[Feature] 是否可以增加appimage格式

### ISSUE THREAD

**Issue by klx1204** [pompurin404/mihomo-party#221]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Linux

### 描述

是否可考虑增加appimage格式？目前在AUR及flatpak均未见mihomo party包，steam deck无法使用。如果可以增加appimage格式将非常实用。
谢谢！

**Comment by xishang0128** [comment]
@klx1204 不能,appimage对于代理软件来说权限不够,几乎不可用

**Comment by ghost** [comment]
https://aur.archlinux.org/packages?O=0&K=mihomo-party

**Comment by klx1204** [comment]
> https://aur.archlinux.org/packages?O=0&K=mihomo-party

谢谢！

**Comment by wencan** [comment]
@xishang0128 
之前clash-verge-rev就有AppImage版，但有点小bug
QV2ray也一直支持AppImage
