### ISSUE TITLE
[Feature] 我需要频繁的使用sudo才能正常使用,轻量模式因此不好用

### ISSUE THREAD

**Issue by BeyondtheApex** [pompurin404/mihomo-party#222]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

# 我需要频繁的使用sudo才能正常使用,轻量模式不可用

## 频繁进行sudo授权

每次开关应用,内核需要频繁进行sudo授权,更改规则等内容需要8次左右,开启代理必须进行12次授权,关闭应用需要3次授权.我必须使用网卡模式,可能与症状有关,所以万分希望能有解决方式.

## 轻量模式不可用

在自动进入轻量模式时,需要连续三次授权,才能进入轻量模式,有时候mac上轻量模式会失去代理功能,不知道是否和权限有关

我的mac上应该还有其他应用以root身份创建了tun网卡,比如easytier程序,不知道授权次数和网卡数量有没有关系,我对这方面没什么了解

**Comment by BeyondtheApex** [comment]
使用sudo来运行此程序可能可以解决问题,但是这样做不合适并且会导致其他问题,比如用户配置不统一,而且在mac上这样做并不方便

**Comment by ghost** [comment]
是不是装了什么sudo-touchid之类的东西，party调用sudo是通过stdin传递密码的，正常来说对于用户是无感的

**Comment by ghost** [comment]
> 每次开关应用,内核需要频繁进行sudo授权,更改规则等内容需要8次左右,开启代理必须进行12次授权,关闭应用需要3次授权.

除了常规的内核授权以外，为了确保修改DNS成功，在修改dns的时候也是调用了sudo的，在修改dns的操作中，软件没有使用单一脚本文件，而是使用了多条命令逐个执行，每条命令是分别使用sudo授权的，但是都是给sudo传递了密码的，正常来说是不会有感知的，非常不建议对于sudo安装类似上面所说的软件，如果非要用的话应该给对应的软件提交issue，sudo的-S参数传递的密码优先级应该提高，而不是传递了密码之后还需要授权。

**Comment by BeyondtheApex** [comment]
我没有安装过任何有关sudo的其他组件，我怎么得到相关的日志或是任何其他记录来得知频繁授权的原因？

**Comment by BeyondtheApex** [comment]
我使用指纹验证sudo，是不是这个的问题

**Comment by BeyondtheApex** [comment]
如果你使用stdin来得到密码，那么它可能不能得到指纹

**Comment by ghost** [comment]
怎么实现指纹授权sudo的，macos自己有相关的设置吗

**Comment by BeyondtheApex** [comment]
你说的sudo-touchid不会是指纹验证吧

**Comment by ghost** [comment]
据我所知系统默认是没有这种东西的

https://github.com/mattrajca/sudo-touchid

**Comment by BeyondtheApex** [comment]
我使用nix-darwin管理系统，在nix配置中，我启用了指纹验证相关配置，但我不知道它是如何实现的，我从使用mac以来一直使用nix来进行系统设置，所以我不知道原来mac不是用指纹进行sudo验证，我以为这是系统功能。使用nix可以使我只关注描述系统状态而不关心具体如何实现，因此我一直不知道原来这不是系统功能

**Comment by BeyondtheApex** [comment]
但是如何解决呢，我能否有办法把密码传递给stdin来避免授权

**Comment by ghost** [comment]
看issue似乎是可以通过修改pam实现

https://github.com/mattrajca/sudo-touchid/issues/30

你是不是做过相关的修改

**Comment by ghost** [comment]
> 看issue似乎是可以通过修改pam实现
> 
> https://github.com/mattrajca/sudo-touchid/issues/30
> 
> 你是不是做过相关的修改

这个issue下面也有人提到了，使用这种方法会导致sudo没法通过密码来认证，我觉得解决方案就是不去修改他，你也可以搜索一下如何开启他的同时保留sudo原本的功能，我不是mac用户给不了你更多帮助。

**Comment by BeyondtheApex** [comment]
我的sudo仍可以用选择使用密码认证，意思是我只要在启动的时候用密码登录一次就可以避免认证？密码是第一次输入时获取的？我会试一试

**Comment by BeyondtheApex** [comment]
好吧即使我从启动这个软件开始一直选择使用密码，它仍无法获取密码，但是关于相关issue里的无法在ssh中使用sudo，我并没有遇到，我仍可以使用密码。我会在寻找一下解决方法的，谢谢你提供帮助

**Comment by BeyondtheApex** [comment]
经过我的查询，从macos14开始，指纹认证由苹果官方提供，用户可以选择认证顺序，密码和指纹认证分属不同认证模块，如果设置了指纹优先，则不会读取-S参数，因为-S参数由密码模块提供，而密码模块优先级低于指纹模块

**Comment by ghost** [comment]
1.5.0已经删除了所有的sudo操作
