### ISSUE TITLE
[Bug] v1.42以后的Windows版本导入本地配置文件无法激活。

### ISSUE THREAD

**Issue by premierePro0516** [pompurin404/mihomo-party#223]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Win10，Win11

### 发生问题 mihomo-party 版本

1.42 or later

### 描述

v1.42以后的Windows版本可以导入本地配置文件，但无法激活。v1.40以前的版本可以导入并激活，使用正常。v1.40升级到v1.44后，原先已经导入的本地配置文件依然可以使用，但新导入的本地配置文件就无法激活使用了。

### 重现方式

反复对比：用v1.40版导入本地配置文件可以激活并正常使用，用1.42以后的版本可以导入但无法激活使用。把v1.42版卸载，然后重新安装v1.40版，不但原先导入的可以用，而且新导入的也可以激活并正常使用。

**Comment by ghost** [comment]
有视频吗，我这边正常的

**Comment by premierePro0516** [comment]
> 有视频吗，我这边正常的


https://github.com/user-attachments/assets/707e1392-45a9-4978-b552-ca992f1c1aaa

从上传的视频可以看到，导入的本地配置激活不正常。多导入几个文件试试，就不难可以看到。我猜：大概率是UI相关的问题。
