### ISSUE TITLE
[Bug] MAC M1 app改名后打不开了

### ISSUE THREAD

**Issue by edifierx666** [pompurin404/mihomo-party#224]
### Verify steps

- [ ] 我已在标题简短的描述了我所遇到的问题
- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

macos15.0.1

### 发生问题 mihomo-party 版本

1.4.4

### 描述

<img width="106" alt="image" src="https://github.com/user-attachments/assets/749961a5-3bb2-44be-a2a8-83e1ea76cb11">
一直卡在这里无法打开, 也没界面显示, 使用CleanMyMacX卸载后装1.4.1还是同样的问题

安装路径是/Applications/Mihomo\ Party.app

### 重现方式

安装最新版

**Comment by Xuu6770** [comment]
同上，卸载旧版本，安装最新版本，在终端输入代码后，打开程序，主窗口不显示。

**Comment by Xuu6770** [comment]
> 同上，卸载旧版本，安装最新版本，在终端输入代码后，打开程序，主窗口不显示。

经过测试，利用`Pearcleaner`卸载`1.4.4`版本后，安装`1.4.3`、`1.4.2`两个版本也遇到了同样的问题。

**Comment by ghost** [comment]
```bash
rm -r /Applications/mihomo-party.app
```

**Comment by Xuu6770** [comment]
> ```shell
> rm -r /Applications/mihomo-party.app
> ```

原来的`1.4.0`已经卸载了，执行您给的命令已经被提示`No such file or directory`了。并且把`/Users/用户名/Library/Application Support/mihomo-party`目录也删除，全新安装`1.4.5`仍然无法显示界面。

**Comment by ghost** [comment]
从终端直接启动呢

```bash
/Mihomo\ Party.app/Contents/MacOS/Mihomo\ Party
```

**Comment by Xuu6770** [comment]
> 从终端直接启动呢
> 
> ```shell
> /Mihomo\ Party.app/Contents/MacOS/Mihomo\ Party
> ```

还是不行，终端也没输出错误：

```shell
aiden@Aiden-MBP /Applications % cd Mihomo\ Party.app 
aiden@Aiden-MBP Mihomo Party.app % ls
Contents
aiden@Aiden-MBP Mihomo Party.app % cd Contents 
aiden@Aiden-MBP Contents % ls
Frameworks	Info.plist	MacOS		PkgInfo		Resources
aiden@Aiden-MBP Contents % cd MacOS 
aiden@Aiden-MBP MacOS % ls
Mihomo Party
aiden@Aiden-MBP MacOS % ./Mihomo\ Party 

┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅
     Sub-Store -- v2.14.391
┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅

[sub-store] INFO: [BACKEND] :::38324
```

**Comment by Xuu6770** [comment]
> 从终端直接启动呢
> 
> ```shell
> /Mihomo\ Party.app/Contents/MacOS/Mihomo\ Party
> ```

突然想到可能要重启一下电脑，结果重启完就好了，无语。（用 Mac 基本很少重启
