### ISSUE TITLE
[Feature] 有没有考虑开发构建Android版本？

### ISSUE THREAD

**Issue by kiritoko1029** [pompurin404/mihomo-party#225]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [ ] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS, Windows, Linux

### 描述

如标题

**Comment by xishang0128** [comment]
没可能
