### ISSUE TITLE
[Feature] 请增加一个自定义端口的功能，因为客户端也有好几个，cfw,nyan, etc, 不确定他们是否会打架

### ISSUE THREAD

**Issue by Guancheng-Li** [pompurin404/mihomo-party#226]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

没有找到设置带代理端口的地方，官方的文档以及UI都翻了一遍，还是没找到。我目前版本是1.44，系统win10x64(理论上不重要)
![image](https://github.com/user-attachments/assets/8562e17d-bc28-48a5-9c30-921d6f1470ee)

**Comment by xishang0128** [comment]
![image](https://github.com/user-attachments/assets/f2102e07-1268-48e9-a10c-dbb5df767140)

**Comment by fwindpeak** [comment]
需要点左下角，内核设置。软件UI不符合直觉，楼上的截图回复过于傲慢了。
![Image](https://github.com/user-attachments/assets/330e14f6-8df3-4f88-a020-f856a95803df)

**Comment by Guancheng-Li** [comment]
多谢两位，能回答就好，我见过更傲慢的回答...不过是别的软件

**Comment by AnyWAT** [comment]
来个更直观的V1.5.12
![Image](https://github.com/user-attachments/assets/61e25f3c-b600-4180-9881-6071feb7c549)
新软件在手，难道不是东戳戳西瞧瞧。。。

> 更傲慢的

太低级了，直接拉黑。。。嘿嘿嘿
