### ISSUE TITLE
[Feature] 打开订阅官网功能

### ISSUE THREAD

**Issue by howareyouo** [pompurin404/mihomo-party#227]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS, Windows, Linux

### 描述

添加一个类似Clash.for.Windows打开订阅官网的功能:
当从梯子官网导入订阅时,记录官方网站地址
之后右键订阅-打开官网

**Comment by xishang0128** [comment]
![image](https://github.com/user-attachments/assets/c7fad323-c667-46bc-8250-30d3f0b96960)
