### ISSUE TITLE
[Feature] 支持Mac顶部状态栏

### ISSUE THREAD

**Issue by Bitcion** [pompurin404/mihomo-party#23]
### Verify steps

- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 我已在标题简短的描述了我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

算是mac延续下来的使用习惯，在顶部状态栏切换以及退出应用

**Comment by ghost** [comment]
是bug，托盘图标没有创建成功
