### ISSUE TITLE
> 有视频吗，我这边正常的

### ISSUE THREAD

**Issue by premierePro0516** [pompurin404/mihomo-party#230]
> 有视频吗，我这边正常的

https://github.com/user-attachments/assets/707e1392-45a9-4978-b552-ca992f1c1aaa

从上传的视频可以看到，导入的本地配置激活不正常。多导入几个文件试试，就不难可以看到。我猜：大概率是UI相关的问题。

_Originally posted by @premierePro0516 in https://github.com/mihomo-party-org/mihomo-party/issues/223#issuecomment-2403555529_

**Comment by premierePro0516** [comment]
提问“> 有视频吗，我这边正常的”，回复并提供视频后，Issue竟然被关闭，这是怎么回事？

**Comment by xishang0128** [comment]
https://github.com/mihomo-party-org/mihomo-party/commit/b1e39ab4b36fb1732c265df2a9e39c6e514f41e6
不会看引用?不会看commit?

![image](https://github.com/user-attachments/assets/e120f33c-aabc-48c8-a648-2c278f4e64b2)

**Comment by premierePro0516** [comment]
抱歉，还真没看到有关的引用和commit。
