### ISSUE TITLE
Arch Linux KDE桌面下内核启动错误。

### ISSUE THREAD

**Issue by olivezane** [pompurin404/mihomo-party#231]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Linux

### 系统版本

Arch Linux

### 发生问题 mihomo-party 版本

mihomo-party-bin 1.4.5

### 描述

kde下打开软件就会显示 内核启动错误 Error:Profile Check Failed: msg="proxy 10: invalid REALITY short ID",第一次进入侧边栏会显示内核版本信息，退出后再进入就没了

### 重现方式

打开软件或进行内核相关操作。

**Comment by silver716** [comment]
> 打开软件或进行内核相关操作。

刚好在用 KDE，我不能复现。

建议：

1. 命令行启动，看输出什么。
2. 卸载后重装，看是否解决。

```
Error:Profile Check Failed: msg="proxy 10: invalid REALITY short ID"
```

这个看起来是配置问题。

**Comment by xishang0128** [comment]
第十一个节点配置错误,检查配置

另外,这不是客户端本身产生的问题
