### ISSUE TITLE
[Bug] 程序会被误识别为游戏

### ISSUE THREAD

**Issue by xyq060101** [pompurin404/mihomo-party#233]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Winodws11

### 发生问题 mihomo-party 版本

1.4.5

### 描述

运行软件时,GamePP和NVIDIA GeForce Experience都会识别为游戏

### 重现方式

打开程序后复现

**Comment by xishang0128** [comment]
经测试,不会,请检查你的PC
