### ISSUE TITLE
[Bug] 连接一直为 0 kb/s

### ISSUE THREAD

**Issue by windwhim** [pompurin404/mihomo-party#234]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11 24H2

### 发生问题 mihomo-party 版本

1.4.5

### 描述

连接页面中上传和下载速度为0，也没有连接记录（可以访问twitter等网站）
![image](https://github.com/user-attachments/assets/7e0a5293-be61-403c-b6de-d8933d286a38)

### 重现方式

启动软件

**Comment by xishang0128** [comment]
请提供更多信息,否则issues将被视为无效并关闭

**Comment by lanceyliao** [comment]
#1149 #1207
