### ISSUE TITLE
[Bug] 开了虚拟网卡+全局模式之后，有的连接还是走直连

### ISSUE THREAD

**Issue by MMMMMoris** [pompurin404/mihomo-party#236]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11 24H2

### 发生问题 mihomo-party 版本

1.4.7

### 描述

![image](https://github.com/user-attachments/assets/7c8ed5f2-2632-47fc-9061-0baf49f3c2dd)

如图，开了虚拟网卡+全局模式之后，有的连接还是走直连

### 重现方式

按照图中设置

**Comment by MMMMMoris** [comment]
再请教一个问题

![image](https://github.com/user-attachments/assets/bc731dfc-6523-483d-be09-863d65bbdd69)

重设防火墙和Tun模式堆栈的三个选项（gVisor, Mixed, System）有什么影响？

似乎我开了严格路由，并改为规则模式之后，又都按照走节点了

**Comment by xishang0128** [comment]
1,连接问题请检查规则/策略组,并且连接问题不是gui程序的问题,不要瞎勾巴勾
2,查看文档

**Comment by MMMMMoris** [comment]
> 1,连接问题请检查规则/策略组,并且连接问题不是gui程序的问题,不要瞎勾巴勾 2,查看文档

这文档你写的？

![image](https://github.com/user-attachments/assets/8683c955-796e-4695-9765-67d0213aba8c)

写真好，看懂了，你可以闭嘴了

**Comment by ghost** [comment]
傻逼
