### ISSUE TITLE
[Bug] 静默启动失效

### ISSUE THREAD

**Issue by imbear** [pompurin404/mihomo-party#237]
### Verify steps

- [ ] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win11

### 发生问题 mihomo-party 版本

1.4.7

### 描述

静默启动无效

### 重现方式

主窗口最大化后，退出应用后重新打开，启动后主窗口最大化显示，静默启动无效
主窗口恢复成通常状态，退出应用后重新打开，启动后主窗口没有显示，静默启动有效

**Comment by xishang0128** [comment]
全屏无法静默,这是预期行为

**Comment by PaTTeeL** [comment]
可否在主窗口最大化时依然支持静默启动吗？尝试了“使用系统标题栏”，主窗口最大化时还是不能静默启动。

**Comment by ioudove** [comment]
请问静默启动是什么意思？
