### ISSUE TITLE
[Bug] 开启虚拟网卡模式后导致tailscale直连打洞失败

### ISSUE THREAD

**Issue by scdyysf** [pompurin404/mihomo-party#239]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 10 专业版 22H2 19045.5011

### 发生问题 mihomo-party 版本

V1.4.7

### 描述

mihomo-party安装在windows电脑上，打开虚拟网卡后，导致手机使用流量通过tailscale与电脑建立链接时基本无法直连（需要依靠国外节点中转），具体表现为打开mihomo和使用系统代理模式下手机使用流量通过tailscale可以与电脑建立直连连接，开启虚拟网卡模式后手机使用流量无法与电脑建立直连（为中转连接），关闭后虚拟网卡模式后恢复。
此外在使用clash for windows V0.20.39时无论开启或者关闭tun模式都可以很顺利的建立直连，未出现过上述问题。

### 重现方式

1.在windows电脑上安装mihomo-party、tailscale最新版，手机上安装tailscale app
2.电脑运行mihomo-party、tailscale，并开启虚拟网卡模式
3.手机使用流量打开tailscale，点击connect建立连接
4.成功后在手机tailscale中点击对应运行mihomo-party的电脑，进入界面后点击右上角ping工具平电脑
5.结果显示为relayed connection为中转，direct connection为直连。开启虚拟网卡后为relayed connection
6.关闭虚拟网卡模式，使用系统代理，重复上述3-4操作，为direct connection
7.关闭mihomo-party，使用clash for windows V0.20.39，打开或关闭tun模式，重复3-4操作，为direct connection

**Comment by ghost** [comment]
嗨，這不是bug噢，這是個feature。

由於本客戶端所整合的代理功能均為 Layer 4 的代理，它只認識TCP和UDP的數據，所以它無法像真VPN一樣「原樣」轉發數據包，所以這就是為什麼會發生您所遇到的現象的原因。

至於您所遇到的這種情況其實其他應用也會存在，目前唯一的解決方法是就是繞過這個應用程式來代理。不過目前本應用還沒完善，所以您需要等待後續更新看看咯。

**Comment by yqs112358** [comment]
配置文件试试在`tun`里面绕过Tailscale网段：
```
tun:
  ...
  route-exclude-address:
    - "100.64.0.0/10"
```

**Comment by xishang0128** [comment]
请确保tailscale流量为直连

**Comment by AnyWAT** [comment]
> 它無法像真VPN一樣「原樣」轉發數據包

V1.5.12便携版虚拟网卡模式下，浏览器“直接连接”或禁用代理扩展就不能连接外网，原来如此。谢谢
