### ISSUE TITLE
[Feature] 这个软件是有什么过人之处吗

### ISSUE THREAD

**Issue by hubumulity** [pompurin404/mihomo-party#24]
### Verify steps

- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [ ] 我已在标题简短的描述了我所需的功能
- [ ] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

相同的节点在rev上面运行油管只能跑4万，而在party上面运行油管能跑10万，着实牛逼！就是图标现在还有点问题，只能重启系统才能打开面板。

**Comment by ghost** [comment]
https://github.com/pompurin404/mihomo-party/issues/18#issuecomment-2289031727
