### ISSUE TITLE
[Bug] WebDav备份时证书验证不过。用的HTTS链接的群晖，浏览器访问没问题的。

### ISSUE THREAD

**Issue by liangddyy** [pompurin404/mihomo-party#242]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [x] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [x] 这是GUI程序的问题,而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Win11

### 发生问题 mihomo-party 版本

1.4.4

### 描述

错误截图：

![image](https://github.com/user-attachments/assets/9a2bfa3f-0f99-4f7f-965e-3a672313b7ef)

### 重现方式

使用webDav备份。

**Comment by xishang0128** [comment]
请确保你的证书有效,mihomo party不支持自签等非权威证书

**Comment by liangddyy** [comment]
好吧。腾讯云的免费证书。已经换用 http了。影响不大。
![image](https://github.com/user-attachments/assets/658e51ce-cc6c-4c88-ae09-1cfb2a301661)

**Comment by ilovesusu** [comment]
cf tunnel 使用的证书也不行吗？
