### ISSUE TITLE
[Bug] win7每次开tun都会取一个新的tun设备名称

### ISSUE THREAD

**Issue by Lichu996** [pompurin404/mihomo-party#243]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

windows7 版本 6.1.7601

### 发生问题 mihomo-party 版本

v1.4.7

### 描述

断开tun后，旧网络适配器会一直存在注册表，但是“ProfileName”每个都不一样
![PixPin_2024-10-15_02-30-27](https://github.com/user-attachments/assets/85b44b5d-1ea0-43f3-8eb9-051a6bdb5f4d)
![PixPin_2024-10-15_02-31-30](https://github.com/user-attachments/assets/7b4a1906-4b8f-4df7-acf8-e253cf1d6883)
![PixPin_2024-10-15_02-31-46](https://github.com/user-attachments/assets/62dcdbd2-08f9-486a-b1dd-2174082170a8)

### 重现方式

win7 tun模式选择gVisor，重复开-关 虚拟网卡按钮

**Comment by xishang0128** [comment]
win7已停止支持,目前win7的release仅保证可以运行,请更换win10/11
