### ISSUE TITLE
[Bug] 多个订阅切换仍无法分别保存选择的节点，且更新订阅后更新间隔会自动恢复默认

### ISSUE THREAD

**Issue by DuskLights** [pompurin404/mihomo-party#244]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Win11 23H2 22635.4367

### 发生问题 mihomo-party 版本

1.4.7

### 描述

多个订阅切换仍无法分别保存选择的节点，即使是更新了支持该功能的1.4.7版本后仍然无法保存，且每个订阅的更新间隔设置好后会在更新订阅后自动恢复默认

### 重现方式

我有三个订阅，每个订阅点开后分别选择好节点，但是切换后仍然会恢复默认节点，而且每个订阅的更新间隔设置好后会在更新订阅后自动恢复默认

**Comment by DuskLights** [comment]
我看到了开发者的解答，说自动会重置1440分钟，但是许多机场的订阅链接用户会拿去转换，而转换出来的更新间隔默认是1440且不易更改，还是希望开发者加入自定义更新间隔的功能

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/26bc88dd-fb2c-466c-ad29-df50feefa258)
