### ISSUE TITLE
新版本在Mac OS10.15.7下无法安装

### ISSUE THREAD

**Issue by lxtx528** [pompurin404/mihomo-party#245]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

10.15.7

### 发生问题 mihomo-party 版本

1.4.8

### 描述

新版本在Mac OS 10.15.7下无法安装X64 dmg
<img width="538" alt="截屏2024-10-15 17 23 06" src="https://github.com/user-attachments/assets/be84a893-8ba7-4481-bfa1-5ae0b789f7d9">

### 重现方式

无

**Comment by ghost** [comment]
1.4.7可以安装吗

**Comment by lxtx528** [comment]
可以

pompurin404 ***@***.***>于2024年10月16日 周三16:23写道：

**Comment by ghost** [comment]
下载 `mihomo-party-catalina-1.5.0-x64.pkg`
