### ISSUE TITLE
[Feature] 前置代理 后置代理

### ISSUE THREAD

**Issue by MavisTok** [pompurin404/mihomo-party#247]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

由于目前要设置后置代理还是比较麻烦，
我再想是否可以做一个功能，只要配置一个节点，然后选择作为前置或者后置即可达到效果

当然我只是提一个建议，还是很感谢开发人员的付出 感谢

**Comment by PctAIGM** [comment]
你是不是要找mihomo内核的dialer-proxy

https://wiki.metacubex.one/config/proxies/dialer-proxy/

**Comment by MavisTok** [comment]
> 你是不是要找mihomo内核的dialer-proxy
> 
> https://wiki.metacubex.one/config/proxies/dialer-proxy/

是的就是这个东西，我现在是用覆写去做，还是比较麻烦，所以想看看能不是实现简单一点的实现方式

**Comment by xishang0128** [comment]
https://wiki.metacubex.one/config/proxy-providers/#override

使用provider,这个客户端不会做
