### ISSUE TITLE
[Bug] app 无法使用app cleaner等干净清理缓存文件

### ISSUE THREAD

**Issue by 1xiaocainiao** [pompurin404/mihomo-party#250]
### Verify steps

- [ ] 我已在标题简短的描述了我所遇到的问题
- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

15.0.1

### 发生问题 mihomo-party 版本

1.5.0

### 描述

app 无法使用app cleaner等清理缓存文件，清理后重新安装，之前的订阅信息等配置都还在，无法清理干净，不知道是否和改名有关，应用目录的文件夹名称还是mihomo-party，这个是路径 /Users/mac/Library/Application\ Support/mihomo-party

### 重现方式

移除重新安装

**Comment by ghost** [comment]
为了不丢失数据，应用目录的路径没有该

**Comment by ghost** [comment]
userData目录本来就不和productName是一致的，应用目录的名称是正常的，app cleaner能不能识别不是软件考虑的事情，应该给app cleaner提交issue
