### ISSUE TITLE
[Bug] 更新后开机自启动失效，双击任务栏网络信息也不能打开程序

### ISSUE THREAD

**Issue by cuteys** [pompurin404/mihomo-party#251]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11 Pro 27723.1000

### 发生问题 mihomo-party 版本

v1.5.1

### 描述

更新 v1.5.1版本 后开机自启动失效，双击任务栏网络信息也不能打开程序，怀疑与修改Windows下的 productName 为 Mihomo Party 有关

### 重现方式

开机后无自启动，双击任务栏网络信息不能打开程序，要手动改路径

**Comment by 387619393566** [comment]
开机自启动失效+1

**Comment by ghost** [comment]
确实有点问题，开机启动的问题，把开机启动的开关重新点一下就可以解决，双击启动的问题我下个版本也改一下默认值，但是应该对已安装的不会生效，需要你自己修改一下trafficMonitor的设置

**Comment by cuteys** [comment]
> 确实有点问题，开机启动的问题，把开机启动的开关重新点一下就可以解决，双击启动的问题我下个版本也改一下默认值，但是应该对已安装的不会生效，需要你自己修改一下trafficMonitor的设置

okok
