### ISSUE TITLE
[Feature] 能否提供一个自定义是否运行TrafficMonitor的选项

### ISSUE THREAD

**Issue by taiwei-t** [pompurin404/mihomo-party#252]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

我的电脑上已经安装了TrafficMonitor，这导致每次运行mihomo-party都会弹出TrafficMonitor的弹窗；
然后我将mihomo-party中的TrafficMonitor删除，运行mihomo-party又会弹一个报错弹窗；
因此，可不可以加一个是否运行TrafficMonitor的选项，或者运行TrafficMonitor前判断文件是否存在，不存在就不去运行TrafficMonitor。

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/9ac1e1f6-380e-48b1-a7e0-077134050968)

**Comment by baize0rzj2** [comment]
不想用就关了，搁着问问问，眉毛下面挂俩蛋，煞笔

**Comment by taiwei-t** [comment]
> ![图像](https://private-user-images.githubusercontent.com/176902387/377863229-9ac1e1f6-380e-48b1-a7e0-077134050968.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjAwMDQsIm5iZiI6MTcyOTI1OTcwNCwicGF0aCI6Ii8xNzY5MDIzODcvMzc3ODYzMjI5LTlhYzFlMWY2LTM4MGUtNDhiMS1hN2UwLTA3NzEzNDA1MDk2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQxMzU1MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2U1NjU5ZWM4OGFhMjNlYjI4OWRlOTE5ZjcxZDI1YjFiMzRkMjRkMDk1OTg0YjcyZDNhZTljNDhiZTg1NzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.weMtFnOiv05o7BwwW1zpgnIuhLAUB4lhLVzqnx7J20k)
对不起，没看见，感谢提醒

**Comment by taiwei-t** [comment]
> 不想用就关了，搁着问问问，眉毛下面挂俩蛋，煞笔

户口本死绝了？戾气这么重
