### ISSUE TITLE
[Bug] Sub-Store的组合节点导入提示内核出错

### ISSUE THREAD

**Issue by proteincontent** [pompurin404/mihomo-party#255]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

版本  Windows 11 专业版 版本号 23H2 操作系统版本  22631.4317

### 发生问题 mihomo-party 版本

mihomo-party-windows-1.5.2

### 描述

无法正确导入组合节点，提示内核问题
![image](https://github.com/user-attachments/assets/4115405a-25b9-40d1-84ab-91e3dcdd38c2)

### 重现方式

利用sub-store导入组合节点的时候，始终无法正确导入，并提示内核问题
![image](https://github.com/user-attachments/assets/d620b086-3f41-4fee-a051-b66cfc1b458c)

**Comment by PctAIGM** [comment]
看看你的配置吧，报错信息很明显了
`port: 47382,20000-30000`

clash 没这种端口配置

**Comment by xream** [comment]
可以看下你生成的那个节点的数据. 最好能提供原始输入, 看看是 Sub-Store 转错了还是别的问题
