### ISSUE TITLE
[Feature] 可不可以增加一个隐藏不可选择节点的开关。

### ISSUE THREAD

**Issue by qasd93991** [pompurin404/mihomo-party#256]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

![PixPin_2024-10-21_17-23-43](https://github.com/user-attachments/assets/b1307d5b-f8e9-45e3-8d3d-8b9208aca278)
如题

**Comment by xishang0128** [comment]
没有节点会是"不可选择"

**Comment by qasd93991** [comment]
url-test、fallback、load-balance、relay  这几个都是不可选择的组，只有 select 是可以选择的组

**Comment by chaeolus** [comment]
hidden: true 自己加上，去看看文档
