### ISSUE TITLE
[Bug] 自定义悬浮窗图标加载不出,显示空白

### ISSUE THREAD

**Issue by wxchil** [pompurin404/mihomo-party#257]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS, Windows

### 系统版本

Win11

### 发生问题 mihomo-party 版本

V1.5.3

### 描述

悬浮窗的自定义图秒,似乎没有建立缓存,需要多主题切换,才能正常显示,否则就是空白

### 重现方式

每次软件重新启动后

**Comment by xishang0128** [comment]
未提供标题
