### ISSUE TITLE
[Bug] 订阅配置中只有proxies字段时，会提示内核启动错误，并且无法正确识别规则

### ISSUE THREAD

**Issue by sdgsgsdf** [pompurin404/mihomo-party#258]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

windows 10

### 发生问题 mihomo-party 版本

1.5.3

### 描述

启动，导入订阅，切换目标订阅出现报错，规则无法被识别

### 重现方式

配置文件是这样的
![图片](https://github.com/user-attachments/assets/a964eefd-1043-4a65-b905-5340b0e37e21)
可以添加订阅，但是切换订阅时会提示内核启动出错
![图片](https://github.com/user-attachments/assets/325257ea-c98e-4eed-bc12-bf0d6e0ee5e4)
规则部似乎也没有正常识别
![图片](https://github.com/user-attachments/assets/97f1636e-5dc0-4b16-ae93-b2505b0ad4ee)
订阅连接：https://mxlsub.me/newfull

**Comment by ghost** [comment]
报错说的很清楚，short-id格式不对
