### ISSUE TITLE
[Bug] mac 终端代理失效了吗，必须开tun模式才有速度了

### ISSUE THREAD

**Issue by 1xiaocainiao** [pompurin404/mihomo-party#259]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

15.0.1

### 发生问题 mihomo-party 版本

1.5.3

### 描述

如题

### 重现方式

以前系统代理下速度很快，现在必须开tun模式，同样的节点

**Comment by xishang0128** [comment]
@1xiaocainiao 终端一直都不吃系统代理
