### ISSUE TITLE
[Bug] 修改节点更新间隔不生效

### ISSUE THREAD

**Issue by iWenhao** [pompurin404/mihomo-party#267]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [ ] 我已在 [Issue Tracker](./?q=is%3Aissue) 中找到我要提出的问题
- [ ] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中找到我要提出的问题
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11 IoT 企业版/23H2/22631.4391

### 发生问题 mihomo-party 版本

v1.18.9

### 描述

在修改完更新间隔时间后，点击保存，再打开编辑信息，更新间隔时间回到默认值

### 重现方式

在修改完更新间隔时间后，点击保存，再打开编辑信息，更新间隔时间回到默认值

**Comment by xishang0128** [comment]
该 issue 需要被关闭，因为用户未完全遵循验证步骤。具体原因如下：1. 用户未在 Issue Tracker 中查找是否存在类似问题。2. 用户未查看常见问题文档。3. 用户未确认这是 GUI 程序的问题而非内核程序的问题。这些步骤是为了避免重复问题和确保问题的准确性。建议用户完成这些步骤后再重新提交 issue。

**Comment by iWenhao** [comment]
![image](https://github.com/user-attachments/assets/941547ed-9f09-41fe-9370-a9b3759a450f)

复现步骤：
1. 打开编辑信息，修改更新间隔，点击保存
2. 手动点击刷新按钮
![image](https://github.com/user-attachments/assets/26285601-02ff-4099-be92-74f07f931718)
3. 再次打开编辑信息，发现更新间隔变成默认值
