### ISSUE TITLE
[Bug] 修改节点更新间隔不生效

### ISSUE THREAD

**Issue by iWenhao** [pompurin404/mihomo-party#268]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在 [Issue Tracker](./?q=is%3Aissue) 中找到我要提出的问题
- [X] 我未在 [常见问题](https://mihomo.party/docs/issues/common) 中找到我要提出的问题
- [X] 这是 GUI 程序的问题，而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11 IoT 企业版/23H2/22631.4391

### 发生问题 mihomo-party 版本

v1.18.9

### 描述

在修改完更新间隔时间后，点击保存，再打开编辑信息，更新间隔时间回到默认值

### 重现方式

![image](https://github.com/user-attachments/assets/60e93b49-5b26-4cd0-9d2e-a6681d5eb900)
复现步骤：

1. 打开编辑信息，修改更新间隔，点击保存
2. 手动点击刷新按钮
![image](https://github.com/user-attachments/assets/50ca7f52-dd08-477c-a859-32ff98a987b9)

3. 再次打开编辑信息，发现更新间隔变成默认值

**Comment by ghost** [comment]
历史issue搜一下能死不

**Comment by iWenhao** [comment]
怎么还带骂人的呢，我是觉得这个项目不错才来提issue的，有的项目我连搭理都不搭理，加上我在open的issue 里面没有找到类似的，就提了

**Comment by ghost** [comment]
Verify steps难道是给你勾着好玩的吗，上一个issue自动回复已经给你说了问题，还在这提

**Comment by iWenhao** [comment]
确认了啊，open 的issue 里面没有啊，这是个bug , 软件更新到最新版了，还是存在，总不能这个bug 还存在，结果issue 被关闭了吧，唉，还真是

**Comment by morytyann** [comment]
@iWenhao 😅这个人意思是，我看的起你你别给脸不要脸？

**Comment by iWenhao** [comment]
您是来拱火的嘛？ 我那句话单纯表达了对作者项目的欣赏，有任何问题嘛 ？

**Comment by tanwov** [comment]
为啥只看open的issue，请用“更新间隔”搜索，然后看第四个issue
