### ISSUE TITLE
[Feature] Mac dock 不能隐藏

### ISSUE THREAD

**Issue by jony4** [pompurin404/mihomo-party#27]
### Verify steps

- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 我已在标题简短的描述了我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

Mac dock 不能隐藏

**Comment by ghost** [comment]
加了开关

**Comment by jony4** [comment]
这个发版是什么时候，自动发版？

**Comment by hbprotoss** [comment]
> 加了开关

能否改成，激活主窗口的时候显示dock图标；关闭主窗口的时候隐藏dock图标
