### ISSUE TITLE
[Feature] 建议 URLTest 类型的代理组内的节点无法手动切换

### ISSUE THREAD

**Issue by Vixb1122** [pompurin404/mihomo-party#274]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [X] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

目前 URLTest 代理组内的节点可以手动切换，与代理组类型冲突

**Comment by ghost** [comment]
点击固定选择是临时的，用完取消固定就好了，这是内核支持的正经功能
