### ISSUE TITLE
[Bug] 下载主题报错

### ISSUE THREAD

**Issue by lixxu** [pompurin404/mihomo-party#278]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [ ] 我已在 [Issue Tracker](./?q=is%3Aissue) 中找到我要提出的问题
- [ ] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中找到我要提出的问题
- [X] 这是 GUI 程序的问题，而不是内核程序的问题
- [ ] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

windows 11

### 发生问题 mihomo-party 版本

1.5.4

### 描述

下载主题时报错, 1.5.3版本没问题:
![图片](https://github.com/user-attachments/assets/5417d18a-2a32-4d56-8ce8-83b979a0ef0e)

### 重现方式

下载主题, 弹出错误

**Comment by ghost** [comment]
1.5.5已修复，从有问题的版本可能无法直接更新，需要手动下载更新
