### ISSUE TITLE
[Bug] 添加BPB的clash链接时报错

### ISSUE THREAD

**Issue by beyond333350** [pompurin404/mihomo-party#279]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中找到我要提出的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中找到我要提出的问题
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

23H2

### 发生问题 mihomo-party 版本

1.5.4

### 描述

添加bpb的clash订阅链接时报错 
 The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
![1](https://github.com/user-attachments/assets/2c785cde-bc13-4af4-acbd-d6e50a0441a2)
![2](https://github.com/user-attachments/assets/98fdb41a-3d15-47b0-9ad9-2c9c3fa45c52)

### 重现方式

添加bpb的clash订阅链接时报错

**Comment by fatinghenji** [comment]
遇到了相同的问题，这个issue不应该被关闭

**Comment by beyond333350** [comment]
> 遇到了相同的问题，这个issue不应该被关闭

#291
