### ISSUE TITLE
[Feature] 优化大窗口的浏览体验

### ISSUE THREAD

**Issue by wordpure** [pompurin404/mihomo-party#282]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [X] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

窗口最大化时，UI 一侧左对齐，一侧右对齐的浏览体验就会很差，视线移动范围很大，而且很难分清右侧对应的是左侧的哪一条目。希望有空能优化一下。

PS：为什么要最大化窗口？因为有时要编辑订阅规则，小窗口看起来不方便，改完又忘记把界面调回来了😂

另外建议像 Clash Verge Rev 那样，给编辑器加个最大化按钮，临时想编辑的时候更方便。

![图片](https://github.com/user-attachments/assets/ccc0b076-81d1-4e59-b8d2-ce8ea63b1871)

![图片](https://github.com/user-attachments/assets/1f4bfa2e-d939-4f4d-b0af-bb804a7c1558)

**Comment by ghost** [comment]
1. 不管
2. verge的最大化按钮被对话框挡住了，所以才需要那玩意

**Comment by wordpure** [comment]
> verge的最大化按钮被对话框挡住了，所以才需要那玩意

感谢提醒，才发现编辑窗口也可以用 Mihomo 的窗口按钮切换最大化状态😂

不过试了下，在编辑窗口打开的时候最大化 Mihomo，代码编辑区域的高度不会和宽度一样自动扩大，还是保持原来的高度

在 Mihomo 最大化之后，再打开编辑窗口，编辑区域的高度就正常

![图片](https://github.com/user-attachments/assets/2a7e6ed4-40a3-4a5d-9811-87167addb683)
