### ISSUE TITLE
[Bug] Error:read ECONNRESET

### ISSUE THREAD

**Issue by DuskLights** [pompurin404/mihomo-party#287]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [X] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [X] 这是 GUI 程序的问题，而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Win11 23H2 22635.4435

### 发生问题 mihomo-party 版本

1.5.5

### 描述

没有开启代理时在更新订阅时出现Error:read ECONNRESET，开启代理后问题消失。三个订阅均会出现这个问题，且使用Clash Verge REV没有出现这个问题。

### 重现方式

没有开启代理时在更新订阅时出现Error:read ECONNRESET

**Comment by ghost** [comment]
> 没有开启代理时在更新订阅时出现

怎么叫开启代理

**Comment by DuskLights** [comment]
> > 没有开启代理时在更新订阅时出现
> 
> 怎么叫开启代理

就是没有开启系统代理或者虚拟网卡，刚测试了，开启系统代理更新订阅一样会出现错误，开启虚拟网卡才能正常更新订阅

**Comment by ghost** [comment]
那就是你的订阅直连更新不了呗，订阅信息把用代理更新勾上

**Comment by DuskLights** [comment]
> 那就是你的订阅直连更新不了呗，订阅信息把用代理更新勾上

三个订阅都更新不了？这不太可能吧。。。

**Comment by ghost** [comment]
勾上用代理更新能不能解决，能解决就不是问题

**Comment by xumofenfei** [comment]
和你一样情况，我的订阅链接是可以直接放在浏览器访问打开的。但是放这个软件也是报这个错。
我的解决方法：
1、使用代理更新订阅
2、换个宽带运营商试一试
3、或者使用蜂窝网络试一试
4、DNS 要换用 阿里 dnspod 等

**Comment by DuskLights** [comment]
> 和你一样情况，我的订阅链接是可以直接放在浏览器访问打开的。但是放这个软件也是报这个错。 我的解决方法： 1、使用代理更新订阅 2、换个宽带运营商试一试 3、或者使用蜂窝网络试一试 4、DNS 要换用 阿里 dnspod 等

是的，使用代理更新就没问题，而且并不是每次都会报错
