### ISSUE TITLE
[Feature] 托盘图标，代理时修改颜色，通过托盘图标可以节点

### ISSUE THREAD

**Issue by xiaoxiao188** [pompurin404/mihomo-party#29]
### Verify steps

- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [ ] 我已在标题简短的描述了我所需的功能
- [ ] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

1.图标很不错，建议在启用代理，规则、全局时，建议更换不通颜色，便于区分代理模式
2.可以直接在托盘上选择自己需要的节点，并节点可以显示ping值

**Comment by xishang0128** [comment]
需求1不会做,需要重新设计icon,现有icon变色不美观

**Comment by xiaoxiao188** [comment]
也是，这个没有发现，那就不动了吧，需求2希望可以有吧
