### ISSUE TITLE
[Bug] 添加bpb的clash订阅链接时报错

### ISSUE THREAD

**Issue by beyond333350** [pompurin404/mihomo-party#291]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [X] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [X] 这是 GUI 程序的问题，而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

23H2

### 发生问题 mihomo-party 版本

1.5.5

### 描述

添加bpb的clash订阅链接时报错
The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
1
![image](https://github.com/user-attachments/assets/a8e517c2-8bee-4bf9-81b8-fd35a633f7ee)

2
![image](https://github.com/user-attachments/assets/5a76b1c7-aabd-48fe-bdf2-015ca908d2fd)

重现方式
添加bpb的clash订阅链接时报错

### 重现方式

添加bpb的clash订阅链接时报错

**Comment by xishang0128** [comment]
请确保链接提供的是正确的mihomo格式配置,这里不负责解决链接提供的配置格式问题

**Comment by fatinghenji** [comment]
请问哪里可以看到正确的mihomo格式的示例配置？

**Comment by PctAIGM** [comment]
> 请问哪里可以看到正确的mihomo格式的示例配置？

https://wiki.metacubex.one/config/
