### ISSUE TITLE
[Bug] 订阅管理每次更新订阅会重置设置好的更新间隔时间

### ISSUE THREAD

**Issue by LeungPok** [pompurin404/mihomo-party#294]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [X] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [X] 这是 GUI 程序的问题，而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

14.2.1 (23C71)

### 发生问题 mihomo-party 版本

v1.5.5

### 描述

订阅管理每次更新订阅会重置设置好的更新间隔时间，我在订阅的时候设置间隔时间是300分钟，当我更新该订阅后更新间隔时间变成1440分钟，测试了多次都一样问题。
更新订阅前：
<img width="800" alt="image" src="https://github.com/user-attachments/assets/ed71973e-21ae-4ae0-ab0c-2ff3ac0439e3">
更新订阅后：
<img width="800" alt="image" src="https://github.com/user-attachments/assets/38ece381-6f49-40e4-b766-aaa33c98c3c0">

### 重现方式

订阅管理>编辑订阅信息>修改更新间隔>300分钟>保存信息>更新该订阅>再次打开该订阅编辑信息>更新间隔不是之前修改保存的300

**Comment by xishang0128** [comment]
@Robo5412 预期行为,会基于响应头覆盖

**Comment by Leskur** [comment]
> [@Robo5412](https://github.com/Robo5412) 预期行为,会基于响应头覆盖

@xishang0128 这是不是违背了 GUI 优先？如果是尊重响应头，用户修改它有什么意义呢，不如做成不可修改？
