### ISSUE TITLE
[Bug] 获取订阅经常502

### ISSUE THREAD

**Issue by icowme** [pompurin404/mihomo-party#30]
### Verify steps

- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [ ] 我已在标题简短的描述了我所遇到的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win11

### 发生问题 mihomo-party 版本

最新版

### 描述

获取订阅提示502,在其他软件上都能获取成功,

### 重现方式

获取订阅提示502,在其他软件上都能获取成功

**Comment by Zstasi** [comment]
hysteria 2好像用稳定版内核才能订阅，然后预览版内核才能连接
