### ISSUE TITLE
[Bug] 轻量模式下，重新打开GUI，网络连接会短暂中断。

### ISSUE THREAD

**Issue by akdriver** [pompurin404/mihomo-party#301]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [X] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [X] 这是 GUI 程序的问题，而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

macos sonoma 14.7

### 发生问题 mihomo-party 版本

1.5.5

### 描述

轻量模式状态下，重新打开程序会导致连接短暂中断一下，应该是重新打开app的时候，重启了clash内核。

补充：设置 **自动开启轻量模式**后，当时间条件满足自动退出GUI的时候，网络也会短暂中断一下。

### 重现方式

开启轻量模式，Mihomo Party GUI退出后，重新打开Mihomo Party，连接就会短暂中断。

**Comment by ghost** [comment]
正常

**Comment by MelanPrince** [comment]
Windows 同样问题。

**Comment by link-fgfgui** [comment]
这个问题一定程度上影响用户体验,且为party独占问题
使用`wmic process where caption="mihomo.exe" get caption,commandline,ParentProcessId,ProcessId /value`查询
mihomo.exe的commandline,ParentProcessId一致,ProcessId不一致,说明在GUI退出同时,重启了新的mihomo实例

**Comment by AnyWAT** [comment]
https://github.com/mihomo-party-org/mihomo-party/issues/606#issuecomment-2731170337
