### ISSUE TITLE
[Bug] 1.5.6版本点开内核设置与外部资源后窗口白屏

### ISSUE THREAD

**Issue by KannaSakura** [pompurin404/mihomo-party#302]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [X] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [X] 这是 GUI 程序的问题，而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11 pro 23h2

### 发生问题 mihomo-party 版本

1.5.6

### 描述

1.5.6版本点开内核设置与外部资源后窗口白屏

### 重现方式

点开内核设置与外部资源后窗口白屏

**Comment by clikader** [comment]
我这里点开软件设置或者查看订阅-编辑信息白屏，降级到1.5.3就没问题了

**Comment by KrisCris** [comment]
可以复现，点击【虚拟网卡】也会白屏。

**Comment by KannaSakura** [comment]
我是回退到1.5.5就没问题，1.5.6/1.5.7都有这个问题，感觉是和AppData\Roaming\mihomo-party里的mihomo.yaml有一定关系，之前就是手动修改这个文件出现过点击内核设置后窗口变成空白

**Comment by 7c9** [comment]
v1.5.10下外部资源窗口不会白屏，但内核设置、虚拟网卡、订阅管理页面的”编辑信息“会白屏

**Comment by love1017best** [comment]
v1.5.11，内核设置、虚拟网卡会白屏，必须回退到v1.5.5以前版本才可以

**Comment by codingFerryman-backup** [comment]
我在v1.5.6及之后也发生了这个问题，经过测试，把在v1.5.6的 57142e2  (#298) 里加的
https://github.com/mihomo-party-org/mihomo-party/blob/f20f15df85fb110554290fe3262cd85a200dce77/electron-builder.yml#L3
给删掉，重新build就不再出现白屏问题了（至少在我本地不会，测试了v1.5.6和v1.5.11），加回去问题就重新出现。

具体原因的话，**可能**和操作系统设置的显示语言有关。在我这边v1.5.11如果把系统语言设为中文就不会出现问题，而改成英文则可复现白屏问题。

**Comment by Magicdover** [comment]
v1.7.6还是存在这个问题，虚拟网卡开启后一段时间会直接白屏，重启后恢复。
