### ISSUE TITLE
[Feature] 关于节点列表优化建议

### ISSUE THREAD

**Issue by icowme** [pompurin404/mihomo-party#31]
### Verify steps

- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 我已在标题简短的描述了我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

建议节点文字缩小一些,便于区分 分组和节点  ,  
建议节点列表改成3列式 , 有点订阅节点较多 , 单列的不利于选择查看. 参考 clash verge的三列式

![微信截图_20240815115624](https://github.com/user-attachments/assets/e8b24911-671f-4d80-9362-ac2d273ef9e4)

**Comment by ghost** [comment]
无此计划 #17
