### ISSUE TITLE
[Bug] 搜索节点时界面布局异常和标签重叠问题

### ISSUE THREAD

**Issue by SammySnake-d** [pompurin404/mihomo-party#313]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win10

### 发生问题 mihomo-party 版本

最新版本

### 描述

关于即使搜索
问题：使用搜索功能，当未搜索到节点时，由于节点列表突然消失，导致页面刷新，代理组标签相对位置变动，搜索输入框消失且属于应用状态
期望：节点消失时输入框不会消失，且代理组的标签相对位置不变

关于页面优化
问题：标签之间有重叠情况，这有可能会出现点击标签错误的情况。
期望：标签之间不发生重叠，可以考虑填充标签背景，不留空隙

#### 最后，是否可以在效率不受很大影响的情况下，当使用搜索时，显示的是过滤后的节点数量，而不是一直是总结点数？

![Image](https://github.com/user-attachments/assets/eddb54cc-0cc4-4872-b82e-947f0521e898)

### 重现方式

页面重叠：节点标签、代理组标签，两两之间都可发生重叠，三者也可重叠

![Image](https://github.com/user-attachments/assets/5522c70f-7e0b-43b8-ac3d-2bd7bd658461)

搜索问题：

![Image](https://github.com/user-attachments/assets/4d8ccecc-91e4-4cb4-a40b-3c13c5c0fc98)

输入第一个X的情况

![Image](https://github.com/user-attachments/assets/677dcf0f-bcc0-4f4a-9e60-0119b837c4ff)

输入第二个X的情况，代理组标签变动+搜索输入框消失。

**Comment by ghost** [comment]
无法复现

https://github.com/user-attachments/assets/0a59f969-1e83-486b-9cd5-68beea659dda


重叠不是bug，是正常的粘性布局动画，上下拖动滚动条可以观察到

**Comment by SammySnake-d** [comment]
您好，在您的视频中输入第二个1的时候，页面布局跳动了，
第二个问题的复现过程：

https://github.com/user-attachments/assets/6ef7ffd0-1d85-4bfb-8c8d-815ed075ff26


需要您在输入前先下滑到节点选择的区域，然后再进行过滤
