### ISSUE TITLE
[Bug] WebDAV恢复後，再按设定齿轮，整个视窗变空白

### ISSUE THREAD

**Issue by adsbin** [pompurin404/mihomo-party#314]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win11 10.0.22631 Build 22631

### 发生问题 mihomo-party 版本

v1.18.9

### 描述

在另一台电脑，用WebDAV恢复後，再按设定齿轮，整个视窗变空白，必需重启软件才回到main。安装版或便携版皆是。

### 重现方式

在另一台电脑，用WebDAV恢复後，再按设定齿轮，整个视窗变空白，必需重启软件才回到main。安装版或便携版皆是。

**Comment by xishang0128** [comment]
没有这个版本
