### ISSUE TITLE
[Feature] 优化代理组界面：调整 GLOBAL 和订阅分组的显示逻辑

### ISSUE THREAD

**Issue by bingotl** [pompurin404/mihomo-party#315]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

代理组自带的这个GLOBAL有点迷惑性，建议：
选择“规则”的时候，不显示“GLOBAL”分组，
选择“全局”的时候，不显示订阅名称分组。因为全部分组展开后，会重复显示很多相同的节点。特别节点很多的机场
（个人建议，不喜直接close）

**Comment by xishang0128** [comment]
global作为“策略组”自然也有显示的必要,并且它也可以直接使用在rules,这对使用在rules的人来说是不好的

**Comment by cdwmhcc** [comment]
这个 GLOBAL 组很有迷惑性，看文档也不太好理解。特别是在切换的时候在第一位有时候在第二位老是搞错。非常建议用不同的样式或者重新设计这个逻辑。
