### ISSUE TITLE
[Bug] 特定 SSID 下切换直连会导致反复的 Gist 文件同步

### ISSUE THREAD

**Issue by faceair** [pompurin404/mihomo-party#316]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

无

### 发生问题 mihomo-party 版本

v1.5.6

### 描述

![Image](https://github.com/user-attachments/assets/646e246e-df14-4493-8d02-064d1c27d9fc)

配置 SSID 直连以后直连的配置也会被同步到 Gist，会导致：
1. 反复的配置变更，生成冗余的 commit 记录
2. 多端同步配置的时候逻辑混乱

是否考虑同步字段的黑名单？比如完全跳过 rule 的同步？

### 重现方式

打开在特定 SSID 下直连，打开 Gist 配置同步

**Comment by ghost** [comment]
功能就是同步运行时配置，自然包含所有字段，至于gist的提交记录，有什么所谓呢。
