### ISSUE TITLE
[Feature] 链接页面增加每个链接的速度显示

### ISSUE THREAD

**Issue by jony4** [pompurin404/mihomo-party#32]
### Verify steps

- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 我已在标题简短的描述了我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

目前在左侧区域可以看到链接的总体速度，但是点进去后看不到每个链接的具体速度，以及最好加上速度排序逻辑

**Comment by MartinDai** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
#89
