### ISSUE TITLE
[Bug] ”查看当前运行时配置“的编辑框可调整后面侧边栏宽度

### ISSUE THREAD

**Issue by ArcSurge** [pompurin404/mihomo-party#322]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11

### 发生问题 mihomo-party 版本

v1.5.6

### 描述

在`查看当前运行时配置`弹框，在调整侧边栏位置的地方，鼠标图标会变化，鼠标左击，弹框会关闭

### 重现方式

打开`查看当前运行时配置`弹框，移动到调整侧边栏位置的地方（就是下图红线的位置），鼠标图标就会变化，鼠标左击，弹框就会关闭![Image](https://github.com/user-attachments/assets/ecc75a3d-6ed7-4e6c-ad76-b9af1685d1cc)

**Comment by SammySnake-d** [comment]
补充：实际是当鼠标移动到面板的分界线位置点击，“查看当前运行时配置页面”关闭
![Image](https://github.com/user-attachments/assets/b546c852-a82c-4e44-9260-c7af1c77f15f)

图中红色位置，处于查看配置页面时，移动到当前位置，点击，会关闭
