### ISSUE TITLE
[Bug] 更新内核报错，app无法打开

### ISSUE THREAD

**Issue by keethebest** [pompurin404/mihomo-party#324]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

12.7.1

### 发生问题 mihomo-party 版本

1.5.6

### 描述

1. 点更新，更新内核报错，代理无法访问
2. 关掉app后，无法打开  不显示主界面，顶部菜单栏也不显示图标

![Image](https://github.com/user-attachments/assets/13fcbe50-5ef5-487c-b0f0-cc65d0872328)
![Image](https://github.com/user-attachments/assets/2c6a1de1-e49b-40eb-bcbd-ef7d7f6b6970)

### 重现方式

点击内核更新按钮

**Comment by SeqCrafter** [comment]
1.5.11 我更新后也出现同样问题了，现在是启动后提示内核启动出错
Error: Profile Check Failed:
msg="proxy group[5]: GLOBAL: 'Auto Choose' not found"

点下载内核也报错

**Comment by SeqCrafter** [comment]
疑似是覆写规则引起的！！软件重置即可恢复

**Comment by LukaTF** [comment]
软件打开后不显示界面怎么解决的？我关掉进程之后重新打开也不行
