### ISSUE TITLE
[Feature] 添加延迟测试结果排序功能

### ISSUE THREAD

**Issue by zhonggy** [pompurin404/mihomo-party#325]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

可以添加延迟测试排序功能吗，把超时的排到后面去

**Comment by xishang0128** [comment]
已有
