### ISSUE TITLE
[Feature] mac 状态栏图标会根据开启状态而变化（颜色或者图案）

### ISSUE THREAD

**Issue by fengzai6** [pompurin404/mihomo-party#327]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

能否当开启代理的时候，变化mihomo图标的颜色或者明显图案，这样能够更好的了解开启状态，能够一眼看出是否打开了代理
![Image](https://github.com/user-attachments/assets/08ed4bd3-d6ba-48bd-b24d-176424c404a3)

**Comment by ghost** [comment]
不做
