### ISSUE TITLE
[Bug] 命令行执行请求，代理绕过不生效

### ISSUE THREAD

**Issue by keethebest** [pompurin404/mihomo-party#330]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

12.7.1

### 发生问题 mihomo-party 版本

1.5.7

### 描述

1. 代理绕过配置： *.a.com
2. 浏览器访问 x.y.a.com, 代理绕过生效， 日志里看不到请求
3. 命令行执行 curl http://x.y.a.com/, 代理绕过没有生效， 日志里看到请求记录

### 重现方式

1. 代理绕过配置： *.a.com
2. 命令行执行 curl http://x.y.a.com

**Comment by xishang0128** [comment]
绕过指的是系统代理绕过,直接使用http port会无视
