### ISSUE TITLE
[Feature Request] Add MITM (Man-in-the-Middle) Proxy Support

### ISSUE THREAD

**Issue by linitfor** [pompurin404/mihomo-party#334]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

請問未來有計畫提供MITM 的功能嗎?

**Comment by linitfor** [comment]
在 mac 上，使用的是loon app / quantum x vpn ， 內部有提供MITM 方式

以下是Loon app mitm 的解釋
MitM （Man in the Middle Attack） 中间人攻击方式解密https的请求。
Loon会根据配置的hostname和信任的CA证书解密相应的https请求和响应，解密后可以配合Rule和URL Rewrite进行分流。

此項功能的應用是
有些線上影片播放過程中，會穿插加入廣告影片
可以利用MITM 解開HTTPS f請求
搭配 JS 腳本，進行Re-write，可以幫忙移除影片內部廣告。

**Comment by xream** [comment]
@linitfor 上面是 bot 回复的...mihomo 的开发者(们)也使用其他 App. 非常清楚 MitM 是什么以及其他其他 App 中的常用使用场景. 甚至已经尝试过 在 mihomo 中添加 MitM. 但是具体如何还得等开发者(们) 决断. 顺便 你不应该在 GUI repo 里发

**Comment by linitfor** [comment]
> [@linitfor](https://github.com/linitfor) 上面是 bot 回复的...mihomo 的开发者(们)也使用其他 App. 非常清楚 MitM 是什么以及其他其他 App 中的常用使用场景. 甚至已经尝试过 在 mihomo 中添加 MitM. 但是具体如何还得等开发者(们) 决断. 顺便 你不应该在 GUI repo 里发

這裡不能發表問題嗎? 那就關閉這串討論吧 ~
