### ISSUE TITLE
[Feature] 增加覆写优先级的颗粒度

### ISSUE THREAD

**Issue by SammySnake-d** [pompurin404/mihomo-party#336]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 期望新特性：能够设置YAML>JS的优先级。YAML先应用，JS后应用，让JS能够根据同级的YAML的配置进行修改。

目前版本：
当同是全局时，YAML和JS如果发生配置冲突，使用的是YAML覆盖，JS不起作用，而我又希望JS是全局的
例如：
我在YAML中配置代理组
![Image](https://github.com/user-attachments/assets/1a5c032f-9d86-431d-9a7d-bdf4bc958987)

然后在JS中对YAML的代理组进行修改操作，
![Image](https://github.com/user-attachments/assets/bde8d2d3-1922-4018-8704-a21d5e85e63e)

同时全局，YAML会覆盖JS的冲突操作导致JS不起作用：

![Image](https://github.com/user-attachments/assets/65886aa4-d6b6-4520-be6f-71987eb40ae9)

图中没有修改成功。

**Comment by ghost** [comment]
覆写页面是可以拖动排序的

**Comment by SammySnake-d** [comment]
> 覆写页面是可以拖动排序的

请问排序顺序是从左到右还是从上到下呢？
