### ISSUE TITLE
[Feature] 希望在展示流量图表的时候可以有个选项只展示代理流量

### ISSUE THREAD

**Issue by tangxiaoqi-tangxiao** [pompurin404/mihomo-party#337]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

因为我大部分情况只关注代理流量的情况，没有走代理的浏览量我不是很关心，希望可以实现这个功能

主要涉及这两个流量展示图
![Image](https://github.com/user-attachments/assets/4c1712f7-ff5c-41e4-aeff-77765a3ac763)

![Image](https://github.com/user-attachments/assets/9d227c1a-430f-445e-bb5b-ff0d99b266d0)

**Comment by xishang0128** [comment]
做不到
