### ISSUE TITLE
[Bug] 悬浮图标开机自启动，会将图标重置到左上角，不论之前在那个位置

### ISSUE THREAD

**Issue by tangxiaoqi-tangxiao** [pompurin404/mihomo-party#342]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

22631.4391

### 发生问题 mihomo-party 版本

v1.5.7

### 描述

![Image](https://github.com/user-attachments/assets/507946a3-168d-4122-8b42-2616bc46c208)

这个悬浮图标开机自启动位置不是之前设置的位置

### 重现方式

打开悬浮图标，拖动到任意位置，使用一段时间关机重启会将图标重置到左上角

经过我测试，立即重启不会重置到左上角，而我正常使用一段时间关机，第二天开机就会重置到左上角，遇到这个bug几次了

**Comment by xishang0128** [comment]
尝试新的测试版

**Comment by tangxiaoqi-tangxiao** [comment]
> 尝试新的测试版

请问在哪里下载呢

**Comment by xishang0128** [comment]
@tangxiaoqi-tangxiao "我已经使用最新的测试版本测试过，问题依旧存在"
呃呃
