### ISSUE TITLE
[Bug] Linux下日志应该放在cache目录，而不是config目录

### ISSUE THREAD

**Issue by witt-bit** [pompurin404/mihomo-party#346]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Linux

### 系统版本

Manjaro 24.1.2 Xahea

### 发生问题 mihomo-party 版本

1.5.7

### 描述

目前我的日志存放路径是`/home/witt/.config/mihomo-party/logs/`

正常在Linux系统中，日志应该在`${HOME}/.cache`下，或者跟随`syslog`，放在`${HOME}/.config`目录下，会导致同步配置时携带日志，或者自动释放空间时，忽略了`mihomo-party`日志

### 重现方式

无

**Comment by ghost** [comment]
软件会自己清理
