### ISSUE TITLE
[Bug] 升级1.5.8版本后打开软件显示内核启动错误

### ISSUE THREAD

**Issue by lingxingcr** [pompurin404/mihomo-party#349]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [ ] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

15.1

### 发生问题 mihomo-party 版本

1.5.8

### 描述

使用homebrew升级至1.5.8版本，打开软件后弹窗提示“内核启动出错”，并附带如下错误代码：SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_setpriority returned EPERM (operation not permitted)

### 重现方式

使用homebrew升级至1.5.8版本随后打开软件，即显示此错误

**Comment by xmshaka** [comment]
OSX 10.15.7 更新15.8 intel pkg 后启动出现同样的问题

**Comment by ghost** [comment]
升级
