### ISSUE TITLE
[Feature] 托盘上的网速显示可以通过开关控制

### ISSUE THREAD

**Issue by MartinDai** [pompurin404/mihomo-party#35]
### Verify steps

- [x] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [x] 我已在标题简短的描述了我所需的功能
- [x] 这是向GUI程序提出的功能请求,而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

现在没有开关可以控制是否显示，我有其他组件专门显示网速的，所以不需要这边显示，而且这边的显示也有问题，占用的宽度不是固定的，会导致状态栏一直左右跳，很影响观感

**Comment by keethebest** [comment]
另外建议：显示网速的话，最好是固定的宽度，不然宽度一直在变，所有的图标也一直换位置，看起来很怪

**Comment by ghost** [comment]
加了开关，调了字体
