### ISSUE TITLE
添加局域网连接允许列表和自定义系统代理端口设置

### ISSUE THREAD

**Issue by Kusabier** [pompurin404/mihomo-party#356]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

- 麻烦添加允许局域网连接的功能
- 麻烦添加允许手动设置系统代理的端口的功能

**Comment by xishang0128** [comment]
已有

**Comment by Kusabier** [comment]
道歉我并没有找到，可以告诉我吗？

**Comment by cn-tre-lfp** [comment]
> 道歉我并没有找到，可以告诉我吗？

在内核设置中
