### ISSUE TITLE
[Feature] 希望增加状态栏的打开代理之后的图标变化

### ISSUE THREAD

**Issue by LeedyJon** [pompurin404/mihomo-party#357]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

mac系统中，打开系统代理之后图标可以变化，而不是现在这样无变化，否则不能一眼看到是否开启了代理，可以通过图标的变化来区分是否打开了代理

**Comment by Kiritocyz** [comment]
@LeedyJon 未来可期

**Comment by gxx2778** [comment]
这个功能的确是很方便的，要是能加上就好了。
