### ISSUE TITLE
[Bug]Windows Server 2022无法启用GUI，后台可查看进程占用，且占用值较高，已经授予管理员权限

### ISSUE THREAD

**Issue by AkihaZhang** [pompurin404/mihomo-party#36]
### Verify steps

- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows Server  2022

### 发生问题 mihomo-party 版本

0.55 0.54 0.53

### 描述

Windows Server 2022安装后无法启用GUI，后台可看到进程占用CPU
![屏幕截图 2024-08-15 194621](https://github.com/user-attachments/assets/3b525c6f-5c7c-4a2d-9bc1-b8b1ef411f92)
![屏幕截图 2024-08-15 194640](https://github.com/user-attachments/assets/c237688f-d982-483e-aeb4-46610b24c47a)

### 重现方式

非个例，Windows Server 2022安装100%复现 手里多台不同的win server均出现相同问题

**Comment by ghost** [comment]
应该可以了
