### ISSUE TITLE
[Feature] 建议增加外部资源中 provider 内容预览

### ISSUE THREAD

**Issue by zuluion** [pompurin404/mihomo-party#362]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Linux, Windows, MacOS

### 描述

# 建议增加外部资源中 provider 内容预览

当前版本只能进入工作目录中查看，不能像配置文件直接查看运行配置 
![Image](https://github.com/user-attachments/assets/d872963b-04a0-4df8-96cc-c37dccb585bb)

例如yacd面板 
![Image](https://github.com/user-attachments/assets/f466efa9-6190-4f1f-8095-e016042d0472)

CFW也可以通过 edit file 按钮直接在GUI中查看 
![Image](https://github.com/user-attachments/assets/6b965508-19a6-4ae5-9984-7f81534cda3b)

--- 

主要是方便用户排查 provider 是否依照预期加载到正确配置

**Comment by xishang0128** [comment]
加了
