### ISSUE TITLE
[Bug] Windows 系统下 mihomo-party 开机自启动设置无法生效

### ISSUE THREAD

**Issue by MissToT** [pompurin404/mihomo-party#370]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11 24H2  26100.2314

### 发生问题 mihomo-party 版本

v1.5.11，v1.5.10，v1.5.2

### 描述

添加开机启动项失效

### 重现方式

添加开机启动项失效

**Comment by hjqys03** [comment]
1.通过软件内的设置选项
2.完全没有启动
3.在任务管理器的启动项中没有 mihomo-party
4.没有
5.之前没有使用 mihomo-party

**Comment by MissToT** [comment]
> 感谢您提交的问题报告。为了更好地帮助排查问题，请补充以下信息：
> 
> 1. 您是通过什么方式设置的开机启动？（例如：通过软件内的设置选项、手动添加注册表等）
> 2. 开机启动失效的具体表现是什么？（例如：完全没有启动、启动后立即关闭等）
> 3. 在任务管理器的"启动"选项卡中是否能看到 mihomo-party？如果能看到，显示的状态是什么？
> 4. 您是否有查看过系统的事件查看器，是否有相关的错误日志？
> 5. 之前的版本是否正常工作？如果是，最后一个正常工作的版本是多少？
> 
> 请提供这些信息以助于我们更好地排查问题。

1.通过软件内的设置选项
2.完全没有启动
3.在任务管理器的"启动"选项卡中没有看到 mihomo-party
4.看不太懂
5.以前没有使用过 mihomo-party

**Comment by xishang0128** [comment]
打开 计划任务程序,找mihomo-party-run

**Comment by MissToT** [comment]
卸载重装软件后此问题已得到解决
