### ISSUE TITLE
[Bug] tun模式在切换网络时偶发dns问题

### ISSUE THREAD

**Issue by chenjunjie45** [pompurin404/mihomo-party#372]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [ ] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

macos 13.7.1 (22H221)

### 发生问题 mihomo-party 版本

v1.5.11

### 描述

使用背景：
我使用的是tun模式，有一个socks5节点是用来访问公司内网用的，通过配置分流 公司内网的域名会走代理去解析
问题现象：
在切换网络时有概率会出现 内网dns解析失败，此时我的公司内网域名无法访问，但是通过公司的内网IP可以访问
网络切换回来dns解析问题也解决不了，重启软件也解决不了，只能重启电脑（想尝试找到内核进程杀掉重试，没找到）

### 重现方式

使用背景：
我使用的是tun模式，有一个socks5节点是用来访问公司内网用的，通过配置分流 公司内网的域名会走代理去解析
问题现象：
在切换网络时有概率会出现 内网dns解析失败，此时我的公司内网域名无法访问，但是通过公司的内网IP可以访问
网络切换回来dns解析问题也解决不了，重启软件也解决不了，只能重启电脑（想尝试找到内核进程杀掉重试，没找到）

**Comment by chenjunjie45** [comment]
![Image](https://github.com/user-attachments/assets/ed081b17-d14c-4804-a108-4d63548249ae)
ping公司内网域名提示没有路由，重启软件，重启内核也解决不了

**Comment by xishang0128** [comment]
只处理gui程序问题
