### ISSUE TITLE
[Bug] 上下行网速无法正常波动

### ISSUE THREAD

**Issue by LinFengLF** [pompurin404/mihomo-party#378]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows10

### 发生问题 mihomo-party 版本

1.5.12

### 描述

![Image](https://github.com/user-attachments/assets/814bb6e8-34b4-4ab7-90ae-d47776b3ca12)
在正常访问网页的时候，网速栏位无法正常波动

### 重现方式

必现

**Comment by xishang0128** [comment]
请确保流量正常进入内核
