### ISSUE TITLE
[Feature] Consider using tauri for UI solution

### ISSUE THREAD

**Issue by haobibo** [pompurin404/mihomo-party#38]
### Verify steps

- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 我已在标题简短的描述了我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

Use tauri may significantly reduce the size of the program.
reference: https://github.com/clash-verge-rev/clash-verge-rev

**Comment by ghost** [comment]
无此计划，相比于tauri的各种兼容性问题，大小问题也叫个事？

**Comment by haobibo** [comment]
sorry to see your arrogance

**Comment by ghost** [comment]
装你妈呢
