### ISSUE TITLE
[Bug] 普通用户权限运行时窗口不自动显示

### ISSUE THREAD

**Issue by Give-pixel** [pompurin404/mihomo-party#386]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows11 家庭中文版 23H2

### 发生问题 mihomo-party 版本

1.5.12

### 描述

我是在目前所使用的设备上出现该问题，具体描述就是当我以普通方式运行软件后只会在任务栏出现图标需要我手动去点击图标或者右键又或者按Tab键才会弹出应用窗口，尝试过去“属性”那给予应用在该账户下完全控制的权限也没用，只能以管理员身份运行才能使应用窗口自动弹出（之前在另一台设备上就没有该问题，系统和软件版本一样，区别是之前那台是轻薄本现在的是游戏本）
![Image](https://github.com/user-attachments/assets/cac5b09b-6985-4473-922f-be49d223322d)

### 重现方式

只要是非管理员身份运行就会有这个问题

**Comment by xishang0128** [comment]
https://github.com/user-attachments/assets/1ab30427-e938-40c6-b31a-0d0a17f0ce12

无法复现,请确保不是设备的问题

**Comment by Give-pixel** [comment]
并不是设备的问题，我其他应用都能正常自动弹窗，唯独mihomo必须以管理员身份运行才行

**Comment by Give-pixel** [comment]
具体如视频所示

**Comment by Give-pixel** [comment]
你好，我又发现了新的状况，那就是当我直接在应用文件夹中以普通方式运行里面的程序文件就可以自动打开窗口，就是这快捷方式不行，这里面有什么关联吗
