### ISSUE TITLE
[Bug] Windows 11 系统代理流量未被正确捕获

### ISSUE THREAD

**Issue by qiushiyinghuo** [pompurin404/mihomo-party#389]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

windows11专业版

### 发生问题 mihomo-party 版本

v1.5.12

### 描述

将软件下载，加入订阅之后，打开系统代理查看日志信息没有任何报错，都是显示正常代理输出信息，但是用chrome浏览器仍然是无法访问，似乎流量并没有走代理。

### 重现方式

我的win11电脑运行clash verge rev很正常，但是换到mihomo party就出现了所述的问题，但是我在另外一台win10电脑上运行mihomo party就是正常运行，正常代理。
![Image](https://github.com/user-attachments/assets/3f467429-d84e-490f-accc-d457848e3c79)
win11电脑上运行的日志信息就是这种，显示输出只和github和微软有关，但实际上我浏览器也在浏览其他需要代理的界面，但是日志没有显示（也无法代理）。

**Comment by qiushiyinghuo** [comment]
另外当我启用虚拟网卡时会出现 [TUN] default interface changed by monitor, => 以太网 的报错信息

**Comment by xishang0128** [comment]
@qiushiyinghuo warn≠错误

**Comment by qiushiyinghuo** [comment]
> 感谢您提交问题报告。为了更好地帮助您解决问题，请提供以下额外信息：
> 
> 1. Chrome 浏览器版本
> 2. 系统代理设置的具体配置截图
> 3. 是否尝试过其他浏览器，结果如何？
> 4. 能否提供完整的配置文件（请记得去除敏感信息）
> 
> 此外，建议：
> 
> 1. 检查 Chrome 是否有设置特殊的代理配置
> 2. 确认系统代理设置是否正确应用
> 3. 尝试使用 curl 或其他工具测试代理是否生效
> 
> 期待您的补充信息，这将有助于我们更准确地定位问题。

1.我的chrome版本是131.0.6778.86
2.![Image](https://github.com/user-attachments/assets/6631278e-9200-43fe-9dae-cdcb15c2ec8c)
软件自动设置，应该是已经开启了端口代理服务
3.使用edge浏览器是正常代理的没有什么问题
4.![Image](https://github.com/user-attachments/assets/882a9a76-c07d-4013-8996-bcad5515fc99)

软件代理运行正常，但是无法代理chrome

**Comment by qiushiyinghuo** [comment]
> [@qiushiyinghuo](https://github.com/qiushiyinghuo) warn≠错误

好的，谢谢您，我以为这是一个有问题信息输出，除了一开始中间会有这样一个警告，后面虚拟网卡启动正常，可以正常访问网络

**Comment by qiushiyinghuo** [comment]
感谢帮助！问题已解决！mihomo party软件代理与chrome的一个插件冲突，导致一直无法成功代理，关闭了插件之后就可以正常代理了，我一直以为是软件在本地的代理服务器的问题，换过软件版本重置过网卡，一直没有发现是浏览器的问题。
