### ISSUE TITLE
[Bug] 轻量模式下pac server自动关闭

### ISSUE THREAD

**Issue by JiyongShi** [pompurin404/mihomo-party#390]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 24H2

### 发生问题 mihomo-party 版本

v1.5.12

### 描述

系统代理使用PAC模式，mihomo-party 会启动pac server，监听端口10000
启动轻量模式时，pac server会跟随mihomo-party 主程序一起退出

### 重现方式

1. mihomo-party启动
2. 启动系统代理并配置为使用PAC模式
3. mihomo-party启动轻量模式或者自动轻量模式
4. netstat检查监听无10000端口，浏览器访问http://127.0.0.1:10000/pac无法访问

**Comment by xishang0128** [comment]
预期行为,pac server由gui程序提供
