### ISSUE TITLE
请求功能：为 Mihomo Party 添加多语言（国际化）支持

### ISSUE THREAD

**Issue by likeleegit** [pompurin404/mihomo-party#392]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

找遍了软件的所有地方，都没有找到设置语言的地方。是不是mihomo party 不支持多语言显示？

**Comment by xishang0128** [comment]
仅支持中文
