### ISSUE TITLE
[Bug] 覆写规则 process-name 不生效

### ISSUE THREAD

**Issue by ayuayue** [pompurin404/mihomo-party#394]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win11 

### 发生问题 mihomo-party 版本

1.5.12

### 描述

仅开启tun模式，对那些应用可以生效，单独配置覆写规则，不会走规则的代理
![Image](https://github.com/user-attachments/assets/27d75c3d-7f96-4723-aa56-b414ab94b877)

### 重现方式

比如启动 ChatGPT 客户端，非tun模式因为没走代理，会打不开

**Comment by xishang0128** [comment]
@ayuayue 客户端不遵守系统代理无关本软件

**Comment by ayuayue** [comment]
> [@ayuayue](https://github.com/ayuayue) 客户端不遵守系统代理无关本软件

没用系统代理啊，clash的规则中不是可以设置针对哪些进程吗，是设置的进程规则，这个规则设置没有生效

**Comment by PctAIGM** [comment]
> > [@ayuayue](https://github.com/ayuayue) 客户端不遵守系统代理无关本软件
> 
> 没用系统代理啊，clash的规则中不是可以设置针对哪些进程吗，是设置的进程规则，这个规则设置没有生效

你理解错了，网络流量能进到内核才进行规则判断（包括进程规则）
你又不开tun，又不用系统代理，流量怎么进到内核，怎么给你代理
