### ISSUE TITLE
[Feature] 添加订阅时，希望支持添加远程订阅

### ISSUE THREAD

**Issue by uyoufu** [pompurin404/mihomo-party#396]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

目前添加远程订阅只能通过 `Sub-Store` 来实现，但是 `Sub-Store` 只保留了节点相关的信息，节点组和规则无法保留，导致在使用时不是很方便。
虽然可以覆写，但是覆写的时候，需要知道节点名称，由于订阅节点的名称可能会变动，就会导致规则要经常变

**Comment by PctAIGM** [comment]
“导入”按钮左侧的输入框是可以输入订阅地址的

**Comment by uyoufu** [comment]
原来如此，谢谢！
建议在框里增加一个 placeholder 类似的东西，这样就知道它的作用了

**Comment by gengjiawen** [comment]
> “导入”按钮左侧的输入框是可以输入订阅地址的

哈哈哈，我找了 10 分钟。。。确实加个 placeholder 会好很多
