### ISSUE TITLE
添加github加速选项

### ISSUE THREAD

**Issue by likeleegit** [pompurin404/mihomo-party#398]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

如下图所示，为加速Geo数据库和规则组的数据更新，需要在每个数据网址前添加加速代理地址；因为有时需要手动切换这个加速代理，这时就要对每个数据地址修改一遍，十分烦琐且为大量的体力劳动。希望能在mihomo party中添加一个选项，启用时填入一个加速地址即可，不启用时就保持默认。
图1
![Image](https://github.com/user-attachments/assets/1c5fb5dd-424c-4e2b-a6eb-bc5edcd2a5c2)

图2
![Image](https://github.com/user-attachments/assets/6773c66f-337b-40a1-94b4-3e57c67cdd6b)

**Comment by AnyWAT** [comment]
V1.5.12便携版貌似虚假更新呢 https://github.com/mihomo-party-org/mihomo-party/issues/186#issuecomment-2516052236

**Comment by likeleegit** [comment]
> V1.5.12难道只有便携版才是虚假更新？[#186 (comment)](https://github.com/mihomo-party-org/mihomo-party/issues/186#issuecomment-2516052236)

看了你的回复，我又测了一下，结果是：用我的设置（使用github加速的方法）是可以成功更新geo信息和代理规则集数据的。安装环境：
windows 10
mihomo party V1.5.12 安装版
更新方式 手动点击更新按钮

现在的需求是：添加一个 自定义添加github加速 的开关

**Comment by xishang0128** [comment]
默认经过内核内部匹配rules连接,所以无需
