### ISSUE TITLE
请问可以增加安卓版吗

### ISSUE THREAD

**Issue by Xuleileon** [pompurin404/mihomo-party#400]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Linux

### 描述

windows端体验下来感觉比其他GUI和客户端体验都要更好，想法也更先进，想知道有没有开发安卓端的计划

**Comment by ghost** [comment]
没有，桌面端的逻辑在移动端没有借鉴意义，开发成员也没有移动端开发经验。
