### ISSUE TITLE
[Feature] 类似 clash 的仅托盘模式

### ISSUE THREAD

**Issue by CloudyAnt** [pompurin404/mihomo-party#402]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

对于”轻量模式“，因为偶尔需要检查连接状态，所以一般不会使用此功能

对于”一般模式“，因为在 Mac 上经常使用 Command + tab/~ 切换应用，而 miho 出现应用列表中，一是略微增加了切换应用的时间，二是在正常状态下不用一直去关注 miho 的状态，而对于一直不打开而在列表的应用，总有想关掉的冲动……
![Image](https://github.com/user-attachments/assets/e443d2d9-c861-47b2-9cab-1d1580e8e2b9)

所以希望有一个”仅托盘模式“，这样在有需要时可以通过托盘查看简单的状态，而正常工作状态下也不会受到干扰。当有修改配置等的需求时，再调出 UI 操作。

**Comment by latte03** [comment]
![Image](https://github.com/user-attachments/assets/3dea1c5d-8d5e-432b-b299-09d1d090aa30)
关闭dock图标后，重启应用就可以了

**Comment by CloudyAnt** [comment]
多谢！没有注意到这个开关~
