### ISSUE TITLE
[Bug] 打开悬浮窗后，kde系统任务栏有图标

### ISSUE THREAD

**Issue by allenzt** [pompurin404/mihomo-party#403]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [ ] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [ ] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [ ] 这是 GUI 程序的问题，而不是内核程序的问题
- [ ] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Linux

### 系统版本

Kubuntu 24.04

### 发生问题 mihomo-party 版本

1.5.12

### 描述

在打开炫富窗后，任务栏一个有图标

### 重现方式

在设置中打开悬浮窗，看任务栏是否有图标, 具体操作请看如下动图
![Image](https://github.com/user-attachments/assets/af6065c7-5763-4417-af38-0042e16c8d09)

**Comment by allenzt** [comment]
补充系统版本信息
![Image](https://github.com/user-attachments/assets/9ad8d172-29a1-488b-8ff2-43d4b88d688d)

**Comment by xishang0128** [comment]
悬浮窗也是一个窗口自然会有
