### ISSUE TITLE
[Feature] 请求来自局域网的连接功能

### ISSUE THREAD

**Issue by maru7777** [pompurin404/mihomo-party#406]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [ ] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Linux

### 描述

可以加入新功能:允许来自局域网的连接 功能吗
我局域网里的其他机器想通过当前主机上网

**Comment by AnyWAT** [comment]
![Image](https://github.com/user-attachments/assets/b6278c57-f666-4690-a165-e1b1398c712b)

**Comment by maru7777** [comment]
谢谢 我还以为那个是不可交互的 😆

**Comment by forose** [comment]
> 谢谢 我还以为那个是不可交互的 😆

比较隐藏啊

**Comment by tdsq369** [comment]
怎么解决的？？ 我没看到其他内容啊

**Comment by Memory2314** [comment]
内核设置不是有开关吗...

**Comment by hi94740** [comment]
真没想到藏在内核设置里，我还在代理设置里找呢，感觉设置东一块西一块的，文档上也没写，找东西真不好找，希望未来能完善文档，或者把设置项整理的更清楚一些

**Comment by locagdgz** [comment]
我去，我今天才发现，之前一直切到clash for windows去开局域网连接哈哈哈哈哈
