### ISSUE TITLE
[Feature] 希望代理节点可以显示到期时间

### ISSUE THREAD

**Issue by EdwardOwl** [pompurin404/mihomo-party#41]
### Verify steps

- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 我已在标题简短的描述了我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

目前的只能显示节点剩余流量，而没有显示到期时间。希望可以加上这个功能

**Comment by geeklihui** [comment]
现在其实是有的，点击编辑信息，里面会显示到期时间。不过我也希望能直接显示在订阅列表里。

**Comment by freeok** [comment]
该功能实现了吗？还是不打算支持

**Comment by ihua4k** [comment]
> 该功能实现了吗？还是不打算支持

相关或者类似功能已经实现，查看以下链接及图片https://github.com/mihomo-party-org/mihomo-party/issues/218#issuecomment-2399392519

![Image](https://github.com/user-attachments/assets/8521fb7a-5e5d-487c-bdbc-045855ac60b6)

**Comment by freeok** [comment]
默认显示为最近更新时间，如何设置为订阅到期时间呢

**Comment by ihua4k** [comment]
> 默认显示为最近更新时间，如何设置为订阅到期时间呢
目前效果如gif所示，前面一条引用开发者评论也说了，可以点击订阅卡片上的时间进行切换
![Image](https://github.com/user-attachments/assets/6691ed5f-3ad8-48a6-944b-36eb6de013a7)
