### ISSUE TITLE
[Feature] 更新后请保留之前的设置

### ISSUE THREAD

**Issue by linrongbin16** [pompurin404/mihomo-party#42]
### Verify steps

- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 我已在标题简短的描述了我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

操作系统：MacOS M1 芯片

直接重新安装了（目前最新的）0.5.5 之后，之前添加过的订阅，包括一些设置都没了。
希望每次更新可以考虑一下保持上一次的设置（除非是巨大break changes）。

**Comment by MartinDai** [comment]
我更新了 还是有的呀

**Comment by xishang0128** [comment]
安装版不要将配置存放在应用目录

**Comment by ghost** [comment]
更新并不会动配置，无法复现
