### ISSUE TITLE
[Feature] English language for UI

### ISSUE THREAD

**Issue by APT-ZERO** [pompurin404/mihomo-party#420]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

Hello
Could you please add English language for UI?
Thank you

**Comment by xishang0128** [comment]
No, Chinese only
