### ISSUE TITLE
[Bug] MiHoMo真是权力滔天啊？TG上面

### ISSUE THREAD

**Issue by adminwh** [pompurin404/mihomo-party#421]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

x

### 发生问题 mihomo-party 版本

x

### 描述

tg群把用户当傻逼，推荐的梯子不负责任，创始，管理一边倒。
假官方网站自己不解决怪用户，我笑死了。

### 重现方式

tg群把用户当傻逼，推荐的梯子不负责任，创始，管理一边倒。
假官方网站自己不解决怪用户，我笑死了。

**Comment by adminwh** [comment]
还他妈的把我踢了，笑死了，在web2 你试试。

**Comment by adminwh** [comment]
假官方网站自己解决不了，ban用户，<img width="873" alt="Image" src="https://github.com/user-attachments/assets/e1a7aab9-46a3-47f4-aca0-7615ee30a125" />

出来的第一个就是你们假的mihomo

**Comment by adminwh** [comment]
来来来 继续ban我

**Comment by adminwh** [comment]
不给用户解决问题，还嘲讽用户，阴阳怪气？

术业有专攻，你开车、摩托车，你开个飞机我看看？

假官方网站不解决，解决用户 好好好牛逼的Mihomo

**Comment by 6ur9er** [comment]
你这样，你不是看的.net那个吗，你要不把.net改成.org再看看呢
