### ISSUE TITLE
[Feature] 悬浮窗能否在开启代理时才出现，未开启代理则消失

### ISSUE THREAD

**Issue by fengyulll** [pompurin404/mihomo-party#424]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

需求如标题所示，或者是悬浮窗可以贴边吸附，或者可以调整透明度，能否新增类似功能

**Comment by xishang0128** [comment]
应用启动＝开启代理
