### ISSUE TITLE
退出时保留状态栏图标和网速

### ISSUE THREAD

**Issue by deajax** [pompurin404/mihomo-party#429]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

退出时保留状态栏图标的显示，只是不在dock栏显示，想完全退出从状态栏点退出。

现在是只要cmd+w 的话，dock 栏就会一直显示图标，
如果是cmd+q 的话就完全退出了，
轻量模式下，状态栏图标也不会留存。

希望可以增加相关配置，比如轻量模式下保留状态栏图标。

**Comment by ZHOUXING1997** [comment]
如何开启这个功能？
