### ISSUE TITLE
[Bug] 订阅无法显示总量和用量

### ISSUE THREAD

**Issue by allmors** [pompurin404/mihomo-party#43]
### Verify steps

- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [X] 我已在标题简短的描述了我所遇到的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win10企业版 19045

### 发生问题 mihomo-party 版本

0.5.2

### 描述

订阅连接提供有用量和总量，应用无法显示总量和用量
![image](https://github.com/user-attachments/assets/de29e620-2693-435d-a484-3bd7cc7fa304)

### 重现方式

任何一个订阅链接

**Comment by ghost** [comment]
tg私信发我订阅链接
