### ISSUE TITLE
[Bug] 显示主窗口时，会导致屏幕闪烁

### ISSUE THREAD

**Issue by aglsv** [pompurin404/mihomo-party#435]
### Verify steps

- [ ] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [ ] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

windows 11 24h2 

### 发生问题 mihomo-party 版本

1.5.12

### 描述

主窗口打开时，会导致屏幕闪烁，不确定是否和显卡有关，显卡为4070，驱动版本为552.22

### 重现方式

打开主窗口

**Comment by AnyWAT** [comment]
试试：检查并修复系统，尝试以管理员身份打开命令提示符，输入以下指令：
Dism /Online /Cleanup-Image /CheckHealth
Dism /Online /Cleanup-Image /ScanHealth
Dism /Online /Cleanup-Image /RestoreHealth
sfc /scannow
扫描后重启电脑查看是否能正常运行。
