### ISSUE TITLE
[Feature] 添加订阅更新方式配置

### ISSUE THREAD

**Issue by ShiGuangAlex** [pompurin404/mihomo-party#44]
### Verify steps

- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 我已在标题简短的描述了我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

发现一个问题，目前拉取订阅的方式是跟随代理配置走的，有的订阅挂了梯子拉不了，有的订阅不挂梯子拉不了，会导致更新订阅的时候要一个一个手动切网络配置才行，能不能给个设置设定一下订阅的拉取方式，这个功能clash-verge-rev是有的，可以借鉴一下

**Comment by xishang0128** [comment]
![image](https://github.com/user-attachments/assets/e377e79e-c98d-4bc1-8d64-031ea5b457a0)
有了
