### ISSUE TITLE
[Bug] Mac托盘图标兼容Ice

### ISSUE THREAD

**Issue by linrongbin16** [pompurin404/mihomo-party#45]
### Verify steps

- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

Sonoma 14.6.1

### 发生问题 mihomo-party 版本

0.5.5

### 描述

[Ice](https://github.com/jordanbaird/Ice) 是mac上一款可以隐藏右上角托盘图标的小工具，因为安装过多的后台工具后，右上角的托盘图标会特别多，就需要这类工具进行隐藏。

没有运行Ice的时候，party是正常显示托盘图标的，但是启动了Ice之后，就不显示了，即使展开所有隐藏的托盘图标也没有。

<img width="644" alt="image" src="https://github.com/user-attachments/assets/0ab6e3fe-9b24-4f80-b65a-d18f4428df81">

clash-verge-rev则没有这个问题。

<img width="854" alt="image" src="https://github.com/user-attachments/assets/d2ff1b09-630d-44de-b337-831e45286403">

若打开Ice里的隐藏图标的section进行设置，则party会显示是个invalid的托盘图标。

**Comment by ghost** [comment]
你把网速显示关了试试呢

**Comment by linrongbin16** [comment]
> 你把网速显示关了试试呢

确实，我还启动了这个 [Stats](https://github.com/exelban/stats).

但关掉了还是一样：

<img width="1391" alt="image" src="https://github.com/user-attachments/assets/f6e6d2a5-e7d6-4be4-bf1b-e8ead70d113e">

**Comment by ghost** [comment]
我说party的网速显示

**Comment by geeklihui** [comment]
> 我说party的网速显示

实测关闭网速显示，ice 正常。

**Comment by geeklihui** [comment]
不过 ice 是真好用啊， 还有没有类似的 macOS 小工具推荐下，感谢

**Comment by linrongbin16** [comment]
> 不过 ice 是真好用啊， 还有没有类似的 macOS 小工具推荐下，感谢

Stats

**Comment by linrongbin16** [comment]
> 我说party的网速显示

嗯，关掉party网速显示就可以了。
