### ISSUE TITLE
[Bug]电脑拨号时启用系统代理无效

### ISSUE THREAD

**Issue by kirito201711** [pompurin404/mihomo-party#47]
### Verify steps

- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [X] 我已在标题简短的描述了我所遇到的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 10 专业版 22H2 19045.4780

### 发生问题 mihomo-party 版本

v0.5.6

### 描述

电脑拨号时启用系统代理无效

### 重现方式

1.电脑拨号
2.启用Mihomo Party 系统代理
3.打开Telegram的系统代理或者浏览器均无效
4.Telegram设置sock5代理有效

**Comment by kirito201711** [comment]
补充：已经把PPPOE名称设置成英文了，Nekoray通过此方式可以解决，但Mihomo Party和Clash Verge都失败了

**Comment by ghost** [comment]
https://github.com/pompurin404/mihomo-party/actions/runs/10519404989 麻烦试试这个版本
