### ISSUE TITLE
[Bug] 无法使用ipv6

### ISSUE THREAD

**Issue by Kernel-cmd** [pompurin404/mihomo-party#49]
### Verify steps

- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [X] 我已在标题简短的描述了我所遇到的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

14.5

### 发生问题 mihomo-party 版本

0.5.7

### 描述

ipv6的timeout，换别的同类型软件可以用。也没找到ipv6的开关在哪打开

### 重现方式

配置中有任何的ipv6节点

**Comment by xishang0128** [comment]
![image](https://github.com/user-attachments/assets/3b3330b7-6738-44a3-bc53-dad2a764fe80)
