### ISSUE TITLE
[Bug] 我系统代理设置的绕过总是莫名重置为最初状态

### ISSUE THREAD

**Issue by Stardustll** [pompurin404/mihomo-party#50]
### Verify steps

- [x] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [X] 我已在标题简短的描述了我所遇到的问题
- [x] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11 专业版 22621.3296

### 发生问题 mihomo-party 版本

v0.5.6

### 描述

我系统代理设置的绕过总是莫名重置为最初状态，添加的网站全没了

### 重现方式

无，点开查看时有时候突然重置

**Comment by xishang0128** [comment]
请确保数据目录没有被清空(如果是安装版,更新时会清空安装目录,不要将数据目录放在安装目录)

**Comment by Stardustll** [comment]
软件正常运行，数据目录不在安装目录，并且配置无变化

**Comment by xishang0128** [comment]
> 软件正常运行，数据目录不在安装目录，并且配置无变化

查看数据目录的config.yaml,看看和app设置对不对的上,对不上可能是没读出来重启就好了

**Comment by Stardustll** [comment]
目前未复现，config.yaml配置对得上

**Comment by Stardustll** [comment]
刚才复现了，确实重启就好，但这个bug很麻烦

**Comment by ghost** [comment]
关闭窗口的时候页面保持在代理页面然后reload导致的，你切换到其他页面再切回来就正常了，想想也没必要reload，下个版本把reload逻辑删了就好了

**Comment by Stardustll** [comment]
好的，谢谢🙏
