### ISSUE TITLE
[Feature] 在连接模块中显示流量使用量

### ISSUE THREAD

**Issue by nv100** [pompurin404/mihomo-party#51]
### Verify steps

- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 我已在标题简短的描述了我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS, Windows, Linux

### 描述

连接模块当前只显示上传与下载速度，可否增加显示使用的流量数。
![data](https://github.com/user-attachments/assets/d901ac1b-3880-47f1-bd64-988d1259d051)

**Comment by psychopasss** [comment]
<img width="1050" alt="image" src="https://github.com/user-attachments/assets/4d0696c2-45c0-42bc-80af-ed3d2212316d">
图中1的位置有总的流量，图里2的位置，每个连接使用的流量可以显示吗？

**Comment by nv100** [comment]
我知道图1位置有使用流量显示，我希望的是在连接模块显示流量，而不是点进去查看。图2位置没有任何显示。

**Comment by ghost** [comment]
没有必要，内核流量统计会在重启内核后清零，软件操作过程中有很多重启内核的操作，统计这个没有意义。

**Comment by nv100** [comment]
原本只是想方便看个每次连接后的大概使用量，毕竟其它软件提供这个数据像flclash与gui for cores，但要是觉得没必要也无妨，也不是很重要的功能。
