### ISSUE TITLE
[Bug] Mac尝试开启tun后无法使用软件

### ISSUE THREAD

**Issue by PantiPenti** [pompurin404/mihomo-party#54]
### Verify steps

- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

15.1

### 发生问题 mihomo-party 版本

0.5.8

### 描述

Mac在尝试开启Tun模式后只能修改应用设置（例如系统代理、Tun设置），进行其他操作（例如导入新的配置、重启内核、手动授权内核等）均会提示报错：
<img width="800" alt="截屏2024-08-17 18 50 40" src="https://github.com/user-attachments/assets/d3c6b8c0-ba38-4548-a46e-152fe040dc9b">

此外，无论重启应用、仅重装应用均无法解决该问题，但使用应用管理工具彻底删除该应用后重新安装或者切换电脑用户后可以再次正常使用除了Tun模式之外的所有功能。

已知：我已启用root用户，且Tun功能在clash-verge-rev中能够正常使用。

能否提供应用日志目录？我只能找到内核日志目录，如果可能我将尽快提供应用日志。

### 重现方式

该问题能够在我的电脑上稳定复现。

在新电脑用户中或者在彻底删除应用后新安装应用后，无论是否先正常导入配置，进行正常使用，只要尝试打开Tun模式，按要求输入root密码后，点击确认后无反应，反复点击后依然无反应，点击取消，即可复现该错误。

补充：

使用终端启动应用程序在复现时没有异常显示，在复现后首次重启前进行任何会报错的操作也不会有异常显示。在之后的重启中使用终端打开会提示：
<img width="567" alt="截屏2024-08-17 19 14 03" src="https://github.com/user-attachments/assets/6ade09ad-7437-4509-b384-ccdbacb6a287">

如果不尝试打开Tun模式，先手动授权内核，完成系统弹窗任务后，尝试打开Tun模式依然会要求输入root密码，且该bug仍然会出现。

**Comment by PantiPenti** [comment]
该问题在6.0.0版本依然存在
<img width="776" alt="截屏2024-08-18 10 30 24" src="https://github.com/user-attachments/assets/e83a6bae-fe04-4f45-9cc7-eb995f74ff69">

**Comment by ghost** [comment]
看看应用目录下的config.yaml

**Comment by PantiPenti** [comment]
是这个吗/Users/{whoami}/Library/Application Support/mihomo-party/config.yaml：
```
core: mihomo
silentStart: false
appTheme: system
proxyDisplayMode: simple
proxyDisplayOrder: default
autoCheckUpdate: true
autoCloseConnection: true
useNameserverPolicy: false
controlDns: true
controlSniff: true
nameserverPolicy: {}
siderOrder:
  - mode
  - sysproxy
  - tun
  - profile
  - proxy
  - mihomo
  - connection
  - dns
  - sniff
  - log
  - rule
  - resource
  - override
sysProxy:
  enable: false
  mode: manual
encryptedPassword:
  "0": 118
  "1": 49
  "2": 48
  "3": 9
  "4": 130
  "5": 132
  "6": 212
  "7": 175
  "8": 29
  "9": 171
  "10": 244
  "11": 79
  "12": 18
  "13": 173
  "14": 140
  "15": 180
  "16": 202
  "17": 204
  "18": 107
useDockIcon: false
showTraffic: false
```

**Comment by PantiPenti** [comment]
草等等这个config.yaml貌似包括我的电脑root密码，能放出来吗？

**Comment by ghost** [comment]
没有加密吗？

**Comment by ghost** [comment]
可以tg私信发我

**Comment by PantiPenti** [comment]
有加密，我估计问题主要出在这一方面，因为删掉那个encryptedPassward后就又可以正常使用了

**Comment by ghost** [comment]
encryptedPassword是什么格式

**Comment by PantiPenti** [comment]
encryptedPassword:
  "序号": 一个值

**Comment by PantiPenti** [comment]
<img width="201" alt="截屏2024-08-18 11 19 04" src="https://github.com/user-attachments/assets/613d74dd-fc97-4d93-a731-1553af99f5f5">

**Comment by ghost** [comment]
不太对，正常应该是个数组

**Comment by PantiPenti** [comment]
> 不太对，正常应该是个数组

而且使用手动授权内核后也要求输入root密码，导致这个Tun模式根本没办法使用。

**Comment by ghost** [comment]
https://github.com/pompurin404/mihomo-party/actions/runs/10437581899

试试这个，把之前的encryptedPassword删了再试

**Comment by PantiPenti** [comment]
目前来看是修复了，没有那个问题了。
