### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by HelplessMan** [pompurin404/mihomo-party#55]
### Verify steps

- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Window 10 22H2 

### 发生问题 mihomo-party 版本

v0.5.7

### 描述

电脑关机前不退出mihomo-party，在开机后会导致无法连接网络

### 重现方式

在昨天关机的时候，电脑的 mihomo-party 客户端还处于系统代理状态， 然后直接关机。

今天早上的时候，一直无法进入游戏、打开网页， 总是反馈无法连接网络

然后尝试重新打开了客户端，然后游戏也可以重新连接 以及网页也恢复访问

**Comment by xishang0128** [comment]
系统代理在关机前没法清空,代理软件都这样,没救
