### ISSUE TITLE
[Bug] v0.6.0版本原本的js文件复写失效了

### ISSUE THREAD

**Issue by ai365vip** [pompurin404/mihomo-party#56]
### Verify steps

- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win10

### 发生问题 mihomo-party 版本

v0.6.0

### 描述

v0.6.0版本原本js文件的复写失效了

### 重现方式

原本js文件的复写失效了

**Comment by ghost** [comment]
重新导入一下试试，新版本对覆写配置有所调整

**Comment by luxlzz6** [comment]
重新导入 再重新关联可以了
