### ISSUE TITLE
[Feature] 可以支持添加哪些网址使用代理吗

### ISSUE THREAD

**Issue by luxlzz6** [pompurin404/mihomo-party#57]
### Verify steps

- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 我已在标题简短的描述了我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

有些网址需要代理才能使用，现在都是需要在订阅规则里面添加，可以在软件直接添加吗。因为看到了已经支持添加绕过的地址。

**Comment by ghost** [comment]
绕过是针对系统代理的，对于内核规则使用覆写功能自定义规则就好了
