### ISSUE TITLE
[Bug] 因配置文件错误导致客户端未启动，但程序会一直存在后台运行和异常高的CPU占用

### ISSUE THREAD

**Issue by QAQ-Huaxia** [pompurin404/mihomo-party#60]
### Verify steps

- [x] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [x] 我已在标题简短的描述了我所遇到的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win10-21H2

### 发生问题 mihomo-party 版本

v0.6.1

### 描述

因配置文件错误导致客户端未能成功启动（？），但是客户端未成功启动而被杀死，会一直存在后台运行和异常高的CPU占用

ps:我测试了2次错误启动程序后台也会存在个2客户端程序运行，可能每次错误启动重启都会留下一个CPU占用较高的客户端程序（配置文件是我故意写错反馈这个问题的）

### 重现方式

<img width="962" alt="Snipaste_2024-08-18_16-45-05" src="https://github.com/user-attachments/assets/196cb856-12c2-481a-9913-8f52537e2b61">

**Comment by ghost** [comment]
对话框阻塞了进程，点击确认即可关闭

**Comment by QAQ-Huaxia** [comment]
哦哦，好的，但是好像会在后台一直占用较高的CPU

**Comment by ghost** [comment]
关了对话框进程也一直存在？

**Comment by QAQ-Huaxia** [comment]
对的，我这里进程会一直存在，然后一个进程占用10-15%的CPU

**Comment by ghost** [comment]
已经修改了内核启动时机
