### ISSUE TITLE
[Bug] 便携版升级版本后配置文件会读取AppData下的

### ISSUE THREAD

**Issue by lakevilladom** [pompurin404/mihomo-party#61]
### Verify steps

- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows11

### 发生问题 mihomo-party 版本

v0.6.1

### 描述

1. 便携版，配置数据存储为：安装目录
2. 升级便携版，解压到安装目录
3. 启动程序，发现配置数据存储为：AppData，加载的数据自然也是AppData的配置

应该是配置数据存储默认值为AppData，所以升级后会自动切换到AppData，建议便携版启动检测当前目录，如果有data目录，则自动设置配置数据存储为：安装目录

### 重现方式

升级便携版

**Comment by ghost** [comment]
怎么升级的，不要删除目录下的PORTABLE文件

**Comment by lakevilladom** [comment]
是我错了，没看到PORTABLE文件
