### ISSUE TITLE
[Bug] debian里运行的时候系统代理无效, tun 模式显示要给内核进行手动授权

### ISSUE THREAD

**Issue by Venompool888** [pompurin404/mihomo-party#62]
### Verify steps

- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [X] 我已在标题简短的描述了我所遇到的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Linux

### 系统版本

debian11

### 发生问题 mihomo-party 版本

0.6.2

### 描述

![image](https://github.com/user-attachments/assets/b1b33624-500c-4a41-bf09-a0faa7c53aae)

### 重现方式

安装完以后，启动导入订阅以后，开启系统代理,浏览器访问谷歌无法进入百度正常. 打开 tun 模式，显示图上错误

**Comment by xishang0128** [comment]
https://mihomo.party/guides/issue/linux/
