### ISSUE TITLE
[Feature] 希望平时以普通用户权限运行，非必要不特权

### ISSUE THREAD

**Issue by suiahae** [pompurin404/mihomo-party#63]
### Verify steps

- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 我已在标题简短的描述了我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

![图片](https://github.com/user-attachments/assets/e986875c-45d4-45cb-be6b-18f2e9fd4fc0)

希望平时以普通用户身份运行，仅在必要时申请切换至管理员权限进行相应操作，降低潜在的风险和责任。

**Comment by ghost** [comment]
软件要确保tun模式的可用性
