### ISSUE TITLE
[Feature] MacOS菜单栏优化

### ISSUE THREAD

**Issue by JE2Se** [pompurin404/mihomo-party#64]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

当前程序显示如下(也有可能是我的电脑的问题)
![image](https://github.com/user-attachments/assets/f1e6734d-acaf-4d20-88d9-ed15461446ba)
1、能否调整一下间距修改为类似原clash那种上下流量分别显示上传下载一级调整下与图标间距
2、另外建议能否增加全局模式，直连模式，规则模式菜单栏中icon的显示形态 以方柏霓在非点击情况下快速知悉当前程序的网络连接形态。
3、在菜单栏选项可否添加节点自动测速
感谢作者无私奉献！

**Comment by S1xOn6** [comment]
也遇到一个样的问题，Intel 版本的 MacBookpro

**Comment by SherlockGougou** [comment]
同求，状态栏空间挺稀缺的，现在没办法调整展示，我只能暂时关闭网速显示了。

**Comment by ghost** [comment]
#90

**Comment by S1xOn6** [comment]
> #90

这里描述了多个需求，但其中一个应该是 bug，就是速度显示的图标和应用的图标间距非常大。希望这个可以调整下。

**Comment by ghost** [comment]
已经调整过了
