### ISSUE TITLE
[Feature] 连接视图增加按照链路排序

### ISSUE THREAD

**Issue by Allen1iu99** [pompurin404/mihomo-party#65]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [ ] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

连接视图增加按照链路排序，这样连接比较多的时候可以快速找到需要的信息

**Comment by ghost** [comment]
#89
