### ISSUE TITLE
[Bug] 更新间隔设置后会自动恢复1440分钟

### ISSUE THREAD

**Issue by felix-klk** [pompurin404/mihomo-party#67]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win11

### 发生问题 mihomo-party 版本

v1.0.0

### 描述

更新间隔设置后会自动恢复1440分钟

### 重现方式

修改后无效自动变回1440分钟

**Comment by ghost** [comment]
这不是bug，就是这么设计的，mihomo party尊重机场设置的更新间隔，如果机场设置了更新间隔则以机场设置的为准，机场设置1440说明其配置不会频繁变动，所以没有必要设置比这小的值，这样设计可以避免用户太过频繁的更新订阅而给机场带来不必要的压力，另外，无论更新间隔设置为多少，软件启动时都会更新一次订阅，所以没有必要手动设置太小的值。

**Comment by misakaok** [comment]
无论更新间隔设置为多少，软件启动时都会更新一次订阅。
优秀 这软件越来越棒了

**Comment by witt-bit** [comment]
> 这不是bug，就是这么设计的，mihomo party尊重机场设置的更新间隔，如果机场设置了更新间隔则以机场设置的为准，机场设置1440说明其配置不会频繁变动，所以没有必要设置比这小的值，这样设计可以避免用户太过频繁的更新订阅而给机场带来不必要的压力，另外，无论更新间隔设置为多少，软件启动时都会更新一次订阅，所以没有必要手动设置太小的值。

这么说就可以理解，目前我也碰到了这个问题,

我尝试排查 #159 的原因，我不确定是机场配置变更导致无网络还是内核授权问题，设置了120分钟被重置
