### ISSUE TITLE
[Feature] 快捷键设置

### ISSUE THREAD

**Issue by lakevilladom** [pompurin404/mihomo-party#68]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

居然到1.0版本了，是不是缺了快捷键配置，还是我没找到

**Comment by ghost** [comment]
确实，还没做
