### ISSUE TITLE
[Bug] 深色和浅色模式不能自动切换

### ISSUE THREAD

**Issue by redfrog999** [pompurin404/mihomo-party#69]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11 23H2

### 发生问题 mihomo-party 版本

1.0.0

### 描述

我用的是便携版，0.63版可以随系统自动切换深色和浅色模式，1.0.0版一直保持深色模式不变，除非你手动换成浅色模式，这蛮影响使用的。不知道是我设置不对还是程序bug，反馈一下，希望开发者看看。thx

### 重现方式

直接使用即可发现。

**Comment by ghost** [comment]
重新下载安装一下，已经修复了，重发了1.0
