### ISSUE TITLE
[Feature] 希望增加局域网代理

### ISSUE THREAD

**Issue by idontwanttosayaword** [pompurin404/mihomo-party#71]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

希望增加局域网代理

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/cd29ea4d-32a4-4b52-8f07-1504c19ebc9c)
