### ISSUE TITLE
[Feature] 求解，windows 哪个版本支持应用内更新

### ISSUE THREAD

**Issue by anghunk** [pompurin404/mihomo-party#72]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

x64-portable.7z
x64-setup.exe

这两个版本我都下载过，然后更新时提示我

![image](https://github.com/user-attachments/assets/0ede9f0e-7086-41fd-9622-f3651ddb1348)

**Comment by lukesyy** [comment]
setup
