### ISSUE TITLE
[Feature] MacOS 上能否支持关闭程序坞程序，仅在菜单栏显示，可以降低gui内存

### ISSUE THREAD

**Issue by Amnesiash** [pompurin404/mihomo-party#73]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

MacOS 上能否支持关闭程序坞程序，仅在菜单栏显示，可以降低gui内存

**Comment by geeklihui** [comment]
不是老早就有了吗 
<img width="710" alt="图片" src="https://github.com/user-attachments/assets/2eb2c82d-c21b-47e5-b407-fd671d1927f9">
