### ISSUE TITLE
[Bug] window无法导入订阅

### ISSUE THREAD

**Issue by Jonnyan404** [pompurin404/mihomo-party#74]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [x] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [x] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

10.0.19045.4780

### 发生问题 mihomo-party 版本

1.0.2

### 描述

![image](https://github.com/user-attachments/assets/4ef03289-31a4-4081-9589-d98dfa1de639)

### 重现方式

1, 有其它代理软件开着,保证网络访问通畅
2, x64-setup.exe  首次安装
3, 首次导入订阅

**Comment by Jonnyan404** [comment]
1, 我把文件下载下来,并加上yaml后缀,
2, 以本地文件方式导入后,
3, 关闭其它代理软件
4, 开启party代理
5, 再次以链接订阅导入才正常

**Comment by Jonnyan404** [comment]
不知道算不算Bug, 算则优化,无则请关闭此issue

**Comment by ghost** [comment]
说明你的订阅链接无法直连导入

**Comment by ghost** [comment]
从你的描述来看就是订阅被墙了

**Comment by Jonnyan404** [comment]
> 从你的描述来看就是订阅被墙了

我们的软件不会通过系统代理读取链接吗? (因为我开的有其它代理软件)
也就意味着首次导入的地址,必须能**直连**,或者像我一样先下载下来把party开起来之后,再导入了.
