### ISSUE TITLE
[Feature] 希望和 meta 一样可以有直接复写手动忽略的主机名的代理配置

### ISSUE THREAD

**Issue by ljy-life** [pompurin404/mihomo-party#75]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

<img width="652" alt="image" src="https://github.com/user-attachments/assets/41730cd8-7599-4efb-8749-cc0d7a1bcdb0">
![Snipaste_2024-08-21_16-52-51](https://github.com/user-attachments/assets/b6f41f07-e833-40f1-a40f-49f3d5a502e7)

**Comment by Jonnyan404** [comment]
点击系统代理图标,就能看到了....

**Comment by ghost** [comment]
> 点击系统代理图标,就能看到了....

<img width="800" alt="image" src="https://github.com/user-attachments/assets/6494b44a-6103-4787-b3df-4164c62d58b4">
发现了，感谢
