### ISSUE TITLE
[Feature] webdav 同步功能删除历史备份和命名优化

### ISSUE THREAD

**Issue by anghunk** [pompurin404/mihomo-party#77]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

有两点小建议：
1. webdav 同步功能是否可以新增删除历史备份功能，有时候备份多了很乱，需要去网盘中手动删除
2. 备份的压缩包名能否优化下，`backup-2024-08-21T07-13-48.185Z.zip` 小时和分没有转化好看起来怪怪的，`backup-2024-08-21 10:33:08.zip` 这样挺好的

**Comment by ghost** [comment]
文件名是不能有冒号的

**Comment by anghunk** [comment]
> 文件名是不能有冒号的

就类似这个意思其他符号也可以代替，主要是想把 T07-13-48.185Z 时间格式转化成可读性强一点的样子
