### ISSUE TITLE
[Feature] 优化连接里的各个链路显示

### ISSUE THREAD

**Issue by Moxi007** [pompurin404/mihomo-party#78]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

可以像verge那样显示各个链接的实时速度
<img width="775" alt="微信图片_20240822174353" src="https://github.com/user-attachments/assets/7d60662f-0b0a-4505-a677-153188156228">

**Comment by ghost** [comment]
#89
