### ISSUE TITLE
[Bug] 无法实现开机自启

### ISSUE THREAD

**Issue by yesircl** [pompurin404/mihomo-party#79]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win11

### 发生问题 mihomo-party 版本

1.0.3

### 描述

已经在设置中勾选了开机自启，但开机后仍然无法启动

### 重现方式

开机无法自启

**Comment by ghost** [comment]
是偶发现象还是每次都无法自启，开机后看看任务管理器是否存在mihomo party的进程

**Comment by yesircl** [comment]
每次都无法自启，而且我勾选开机自启后程序没法自动添加到启动项，我自己手动把程序添加到启动项也无法自启，下次开机我观察下进程中是否有mihomo party
![2024-08-23_100654](https://github.com/user-attachments/assets/d603c7fe-33f8-4cee-9abc-ad07c1850de2)

**Comment by ghost** [comment]
软件使用任务计划进行开机启动，不会出现在启动项里面

**Comment by yesircl** [comment]
好的，明白了，这个问题可以关闭了
