### ISSUE TITLE
[Feature] 开启TUN模式，使用本地DNS时，DNS劫持无法正常生效，并且域名嗅探也无法正常完成

### ISSUE THREAD

**Issue by ShiGuangAlex** [pompurin404/mihomo-party#80]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

开启TUN模式，使用本地DNS时，DNS劫持无法正常生效，并且域名嗅探也无法正常完成，始终会解析为被污染的DNS，而非faker-ip。需要手动指定DNS为公网DNS才能正常被劫持。有什么办法优化吗？

**Comment by ghost** [comment]
后续会在开启tun的时候自动修改dns

**Comment by dahaha-365** [comment]
现在还是有这个问题，Windows和Mac都有这个现象。具体表现是打开www.google.com，提示隐私设置错误，ssl证书有时是facebook.com，有时是instgram.com，此时查日志并没有www.google.com的入站记录。需要等待dns缓存失效后才能正常访问google。
