### ISSUE TITLE
[Bug]  MacOS 13 开机启动无法打开

### ISSUE THREAD

**Issue by UphkcRNqmafQWcSSSSSS** [pompurin404/mihomo-party#83]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

13.6.5

### 发生问题 mihomo-party 版本

V1.0.4

### 描述

<img width="993" alt="image" src="https://github.com/user-attachments/assets/c2c0cda0-873f-4094-a9a1-df09ede1802e">

https://github.com/user-attachments/assets/464b98ec-b694-4b7a-a4fa-3c2a702d57bf

### 重现方式

应用设置 -》开机启动

**Comment by hanwenhao369** [comment]
请问这个问题解决了吗？

**Comment by ghost** [comment]
我这边没法复现，不知道原因

**Comment by UphkcRNqmafQWcSSSSSS** [comment]
> 我这边没法复现，不知道原因
我手动开机启动了。
怎么看日志？

**Comment by UphkcRNqmafQWcSSSSSS** [comment]
> 我这边没法复现，不知道原因

<img width="1289" alt="image" src="https://github.com/user-attachments/assets/23a6e48d-1ac4-419b-a759-29d13021116b">

权限问题

**Comment by chenxiccc** [comment]
我这里也是一样。
