### ISSUE TITLE
[Feature] 建议日志页面input输入框加个清空内容

### ISSUE THREAD

**Issue by ChaoJieGo** [pompurin404/mihomo-party#88]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

input框加个清空功能
isClearable
onClear={() => console.log("input cleared")}

**Comment by pompurin404** [comment]
49422272578a3df7b81c0cd739d406d3bfe9528f
