### ISSUE TITLE
[Bug] Win系统中,"连接"展示框网络速度经常卡死不动

### ISSUE THREAD

**Issue by wxchil** [pompurin404/mihomo-party#91]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Win11

### 发生问题 mihomo-party 版本

V1.0.8

### 描述

![image](https://github.com/user-attachments/assets/67a5ebf5-d3aa-4145-a869-0af38dc14d3a)
如上图,53.82KB/s这个位置始终不更新

### 重现方式

应该是通过webui更新内核之后,暂时内核已经是最新,待后续再有更新是观察下

**Comment by ghost** [comment]
重启一下内核就好了，这是内核非正常关闭导致的，更新的时候内核重启是不受控的。

**Comment by wxchil** [comment]
OK,谢谢~
