### ISSUE TITLE
[Bug] 无法通过URL Schemes导入配置

### ISSUE THREAD

**Issue by YipSzeho** [pompurin404/mihomo-party#93]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows11 23H2

### 发生问题 mihomo-party 版本

Build #373

### 描述

浏览器可以通过URL Schemes唤起mihomo-party，但mihomo-party没有进一步进行配置的导入

### 重现方式

浏览器访问clash://install-config?url=<URI编码后url>

**Comment by ghost** [comment]
https://github.com/pompurin404/mihomo-party/actions/runs/10580500209

看看这版是否修复

**Comment by YipSzeho** [comment]
未修复，点击链接时流量计有变化，且log可以看出此时为direct连接符合预期，但就是没有导入订阅

**Comment by ghost** [comment]
订阅导入成功有系统通知，导入失败会有弹窗报错，没有反应吗

**Comment by YipSzeho** [comment]
奇怪，没有系统通知，但是有个一闪而过的像是powershell的弹窗

**Comment by ghost** [comment]
怪了，我这边测试没问题了

**Comment by YipSzeho** [comment]
大佬幸苦了，release最新版本已经可以导入了。
但是名称的显示有个小问题，subconvertor配置的名称是Proxy，但程序导入订阅后显示的是"Proxy"; filename*=utf-8''Proxy
![image](https://github.com/user-attachments/assets/29058fb3-f010-4b6b-9249-450c5d3c71f8)

**Comment by ghost** [comment]
https://github.com/pompurin404/mihomo-party/actions/runs/10625960207
