### ISSUE TITLE
[Feature] 建议订阅界面保留"最近更新时间"

### ISSUE THREAD

**Issue by lakevilladom** [pompurin404/mihomo-party#95]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

如标题，建议订阅界面保留"最近更新时间"，之前是有显示"最近更新时间"，最近的更新中用"到期时间"替换了"最近更新时间"，建议同时保留，其他同类某软件同时显示有这俩信息，看着也挺和谐：
![image](https://github.com/user-attachments/assets/ac4bfd18-cf0e-4f73-85bd-6f4bf6bf205f)

场景：对于某些免费订阅，不是特别稳定，经常需要更新连接，这时候"最近更新时间"就能更方便的看到该订阅是不是最新的

**Comment by ghost** [comment]
更新按钮悬停即可看到
