### ISSUE TITLE
[Bug] M3 cpu占用好高啊

### ISSUE THREAD

**Issue by 1xiaocainiao** [pompurin404/mihomo-party#98]
### Verify steps

- [ ] 我已在标题简短的描述了我所遇到的问题
- [ ] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [ ] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [ ] 这是GUI程序的问题,而不是内核程序的问题
- [ ] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

14.6.1

### 发生问题 mihomo-party 版本

1.0.8

### 描述

![QQ_1724752024128](https://github.com/user-attachments/assets/4a6f1a1a-789d-4236-8c37-65e1867bc219)
cpu占用好高啊，观察了一下30 40的占用，甚至50多70

### 重现方式

正常使用，打开软件关闭UI，查看的iStat Menus

**Comment by serious-snow** [comment]
https://github.com/pompurin404/mihomo-party/issues/87

m2 pro也卡，参照这个issue，把网速信息去掉，cpu直接就下来了

**Comment by ghost** [comment]
https://github.com/pompurin404/mihomo-party/actions/runs/10577227103

麻烦试试这一版，看是否有所改善

**Comment by Jonnyan404** [comment]
> https://github.com/pompurin404/mihomo-party/actions/runs/10577227103
> 
> 麻烦试试这一版，看是否有所改善

1.0.9版本解决了高占用问题,已经降到个位数了.
