### ISSUE TITLE
[Bug] 开启虚拟网卡后，电脑启动后网络显示小地球图标，重新开关虚拟网卡后恢复正常

### ISSUE THREAD

**Issue by jasonwei1002** [pompurin404/mihomo-party#99]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win11

### 发生问题 mihomo-party 版本

1.0.8

### 描述

![image](https://github.com/user-attachments/assets/92b163dd-4416-4094-a42d-bd2c05cee71e)

### 重现方式

如题重现

**Comment by ghost** [comment]
windows的问题

**Comment by 0xhelium** [comment]
fake-ip-filter 添加下面两条记录:
- +.msftconnecttest.com
- +.msftncsi.com
